// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/discovery/v1/server.proto (package chatto.discovery.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetServerRequest, GetServerResponse, ListNeighborsRequest, ListNeighborsResponse } from "./server_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * Provides unauthenticated server discovery metadata.
 *
 * @generated from service chatto.discovery.v1.ServerDiscoveryService
 */
export const ServerDiscoveryService = {
  typeName: "chatto.discovery.v1.ServerDiscoveryService",
  methods: {
    /**
     * Returns public server metadata, branding, registration status, and login
     * provider information. This fully public RPC is available before login so
     * clients can render the first server screen and authentication choices.
     *
     * @generated from rpc chatto.discovery.v1.ServerDiscoveryService.GetServer
     */
    getServer: {
      name: "GetServer",
      I: GetServerRequest,
      O: GetServerResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * Returns the public Neighbor directory without requiring a session.
     *
     * @generated from rpc chatto.discovery.v1.ServerDiscoveryService.ListNeighbors
     */
    listNeighbors: {
      name: "ListNeighbors",
      I: ListNeighborsRequest,
      O: ListNeighborsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;
