// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/discovery/v1/server.proto (package chatto.discovery.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { ServerLogin, ServerPublicProfile } from "../../api/v1/server_pb.js";

/**
 * Request for public server metadata.
 *
 * @generated from message chatto.discovery.v1.GetServerRequest
 */
export class GetServerRequest extends Message<GetServerRequest> {
  constructor(data?: PartialMessage<GetServerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.discovery.v1.GetServerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerRequest {
    return new GetServerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerRequest {
    return new GetServerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerRequest {
    return new GetServerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerRequest | PlainMessage<GetServerRequest> | undefined, b: GetServerRequest | PlainMessage<GetServerRequest> | undefined): boolean {
    return proto3.util.equals(GetServerRequest, a, b);
  }
}

/**
 * Public metadata clients need before they can authenticate or render the
 * initial server view.
 *
 * @generated from message chatto.discovery.v1.GetServerResponse
 */
export class GetServerResponse extends Message<GetServerResponse> {
  /**
   * Public server profile and branding.
   *
   * @generated from field: chatto.api.v1.ServerPublicProfile profile = 1;
   */
  profile?: ServerPublicProfile;

  /**
   * Login and registration options.
   *
   * @generated from field: chatto.api.v1.ServerLogin login = 2;
   */
  login?: ServerLogin;

  constructor(data?: PartialMessage<GetServerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.discovery.v1.GetServerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "profile", kind: "message", T: ServerPublicProfile },
    { no: 2, name: "login", kind: "message", T: ServerLogin },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerResponse {
    return new GetServerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerResponse {
    return new GetServerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerResponse {
    return new GetServerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerResponse | PlainMessage<GetServerResponse> | undefined, b: GetServerResponse | PlainMessage<GetServerResponse> | undefined): boolean {
    return proto3.util.equals(GetServerResponse, a, b);
  }
}

/**
 * Request for the public Neighbor directory.
 *
 * @generated from message chatto.discovery.v1.ListNeighborsRequest
 */
export class ListNeighborsRequest extends Message<ListNeighborsRequest> {
  constructor(data?: PartialMessage<ListNeighborsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.discovery.v1.ListNeighborsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListNeighborsRequest {
    return new ListNeighborsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListNeighborsRequest {
    return new ListNeighborsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListNeighborsRequest {
    return new ListNeighborsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListNeighborsRequest | PlainMessage<ListNeighborsRequest> | undefined, b: ListNeighborsRequest | PlainMessage<ListNeighborsRequest> | undefined): boolean {
    return proto3.util.equals(ListNeighborsRequest, a, b);
  }
}

/**
 * Publicly advertised servers. The response has no ordering contract.
 *
 * @generated from message chatto.discovery.v1.ListNeighborsResponse
 */
export class ListNeighborsResponse extends Message<ListNeighborsResponse> {
  /**
   * Canonical origins of the advertised servers.
   *
   * @generated from field: repeated string origins = 1;
   */
  origins: string[] = [];

  constructor(data?: PartialMessage<ListNeighborsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.discovery.v1.ListNeighborsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "origins", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListNeighborsResponse {
    return new ListNeighborsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListNeighborsResponse {
    return new ListNeighborsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListNeighborsResponse {
    return new ListNeighborsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListNeighborsResponse | PlainMessage<ListNeighborsResponse> | undefined, b: ListNeighborsResponse | PlainMessage<ListNeighborsResponse> | undefined): boolean {
    return proto3.util.equals(ListNeighborsResponse, a, b);
  }
}
