// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/auth/v1/external_identity_auth.proto (package chatto.auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { LinkedExternalIdentity } from "../../api/v1/external_identities_pb.js";

/**
 * Mode of a pending external identity confirmation flow.
 *
 * @generated from enum chatto.auth.v1.ExternalIdentityFlowKind
 */
export enum ExternalIdentityFlowKind {
  /**
   * The flow kind was not specified.
   *
   * @generated from enum value: EXTERNAL_IDENTITY_FLOW_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Create a new passwordless account and link the provider identity.
   *
   * @generated from enum value: EXTERNAL_IDENTITY_FLOW_KIND_CREATE_ACCOUNT = 1;
   */
  CREATE_ACCOUNT = 1,

  /**
   * Link the provider identity to the authenticated account.
   *
   * @generated from enum value: EXTERNAL_IDENTITY_FLOW_KIND_LINK_ACCOUNT = 2;
   */
  LINK_ACCOUNT = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(ExternalIdentityFlowKind)
proto3.util.setEnumType(ExternalIdentityFlowKind, "chatto.auth.v1.ExternalIdentityFlowKind", [
  { no: 0, name: "EXTERNAL_IDENTITY_FLOW_KIND_UNSPECIFIED" },
  { no: 1, name: "EXTERNAL_IDENTITY_FLOW_KIND_CREATE_ACCOUNT" },
  { no: 2, name: "EXTERNAL_IDENTITY_FLOW_KIND_LINK_ACCOUNT" },
]);

/**
 * Metadata about a pending external identity flow. The provider subject is not
 * exposed; clients only need user-facing provider/profile hints.
 *
 * @generated from message chatto.auth.v1.PendingExternalIdentity
 */
export class PendingExternalIdentity extends Message<PendingExternalIdentity> {
  /**
   * Pending flow kind.
   *
   * @generated from field: chatto.auth.v1.ExternalIdentityFlowKind kind = 1;
   */
  kind = ExternalIdentityFlowKind.UNSPECIFIED;

  /**
   * Provider ID that produced the identity.
   *
   * @generated from field: string provider_id = 2;
   */
  providerId = "";

  /**
   * Provider type that produced the identity.
   *
   * @generated from field: string provider_type = 3;
   */
  providerType = "";

  /**
   * Provider label shown to the user.
   *
   * @generated from field: string provider_label = 4;
   */
  providerLabel = "";

  /**
   * Verified email supplied by the provider, when available.
   *
   * @generated from field: string verified_email = 5;
   */
  verifiedEmail = "";

  /**
   * Suggested username derived from provider profile hints.
   *
   * @generated from field: string login_hint = 6;
   */
  loginHint = "";

  /**
   * Suggested display name derived from provider profile hints.
   *
   * @generated from field: string display_name_hint = 7;
   */
  displayNameHint = "";

  /**
   * User ID this link flow is bound to. Empty for create flows.
   *
   * @generated from field: string bound_user_id = 8;
   */
  boundUserId = "";

  /**
   * Internal path the client should return to after confirmation.
   *
   * @generated from field: string redirect_path = 9;
   */
  redirectPath = "";

  constructor(data?: PartialMessage<PendingExternalIdentity>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.auth.v1.PendingExternalIdentity";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "kind", kind: "enum", T: proto3.getEnumType(ExternalIdentityFlowKind) },
    { no: 2, name: "provider_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "provider_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "provider_label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "verified_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "login_hint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "display_name_hint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "bound_user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "redirect_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PendingExternalIdentity {
    return new PendingExternalIdentity().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PendingExternalIdentity {
    return new PendingExternalIdentity().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PendingExternalIdentity {
    return new PendingExternalIdentity().fromJsonString(jsonString, options);
  }

  static equals(a: PendingExternalIdentity | PlainMessage<PendingExternalIdentity> | undefined, b: PendingExternalIdentity | PlainMessage<PendingExternalIdentity> | undefined): boolean {
    return proto3.util.equals(PendingExternalIdentity, a, b);
  }
}

/**
 * Request to inspect a pending external identity flow.
 *
 * @generated from message chatto.auth.v1.GetPendingExternalIdentityRequest
 */
export class GetPendingExternalIdentityRequest extends Message<GetPendingExternalIdentityRequest> {
  /**
   * Raw pending flow token from the provider callback redirect.
   *
   * @generated from field: string token = 1;
   */
  token = "";

  constructor(data?: PartialMessage<GetPendingExternalIdentityRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.auth.v1.GetPendingExternalIdentityRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPendingExternalIdentityRequest {
    return new GetPendingExternalIdentityRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPendingExternalIdentityRequest {
    return new GetPendingExternalIdentityRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPendingExternalIdentityRequest {
    return new GetPendingExternalIdentityRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPendingExternalIdentityRequest | PlainMessage<GetPendingExternalIdentityRequest> | undefined, b: GetPendingExternalIdentityRequest | PlainMessage<GetPendingExternalIdentityRequest> | undefined): boolean {
    return proto3.util.equals(GetPendingExternalIdentityRequest, a, b);
  }
}

/**
 * Result of inspecting a pending external identity flow.
 *
 * @generated from message chatto.auth.v1.GetPendingExternalIdentityResponse
 */
export class GetPendingExternalIdentityResponse extends Message<GetPendingExternalIdentityResponse> {
  /**
   * Pending flow metadata.
   *
   * @generated from field: chatto.auth.v1.PendingExternalIdentity pending = 1;
   */
  pending?: PendingExternalIdentity;

  constructor(data?: PartialMessage<GetPendingExternalIdentityResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.auth.v1.GetPendingExternalIdentityResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pending", kind: "message", T: PendingExternalIdentity },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPendingExternalIdentityResponse {
    return new GetPendingExternalIdentityResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPendingExternalIdentityResponse {
    return new GetPendingExternalIdentityResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPendingExternalIdentityResponse {
    return new GetPendingExternalIdentityResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetPendingExternalIdentityResponse | PlainMessage<GetPendingExternalIdentityResponse> | undefined, b: GetPendingExternalIdentityResponse | PlainMessage<GetPendingExternalIdentityResponse> | undefined): boolean {
    return proto3.util.equals(GetPendingExternalIdentityResponse, a, b);
  }
}

/**
 * Request to create a new passwordless account from a pending provider identity.
 *
 * @generated from message chatto.auth.v1.CreateExternalIdentityAccountRequest
 */
export class CreateExternalIdentityAccountRequest extends Message<CreateExternalIdentityAccountRequest> {
  /**
   * Raw pending create token from the provider callback redirect.
   *
   * @generated from field: string token = 1;
   */
  token = "";

  /**
   * Desired username.
   *
   * @generated from field: string login = 2;
   */
  login = "";

  /**
   * Desired display name. When omitted, the server uses a valid provider hint
   * and otherwise falls back to the requested username.
   *
   * @generated from field: string display_name = 3;
   */
  displayName = "";

  constructor(data?: PartialMessage<CreateExternalIdentityAccountRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.auth.v1.CreateExternalIdentityAccountRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "login", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateExternalIdentityAccountRequest {
    return new CreateExternalIdentityAccountRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateExternalIdentityAccountRequest {
    return new CreateExternalIdentityAccountRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateExternalIdentityAccountRequest {
    return new CreateExternalIdentityAccountRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateExternalIdentityAccountRequest | PlainMessage<CreateExternalIdentityAccountRequest> | undefined, b: CreateExternalIdentityAccountRequest | PlainMessage<CreateExternalIdentityAccountRequest> | undefined): boolean {
    return proto3.util.equals(CreateExternalIdentityAccountRequest, a, b);
  }
}

/**
 * Result of creating an account from a pending provider identity.
 *
 * @generated from message chatto.auth.v1.CreateExternalIdentityAccountResponse
 */
export class CreateExternalIdentityAccountResponse extends Message<CreateExternalIdentityAccountResponse> {
  /**
   * Newly created user ID.
   *
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * Newly created username.
   *
   * @generated from field: string login = 2;
   */
  login = "";

  /**
   * Short-lived bearer access token for the new session.
   *
   * @generated from field: string token = 3;
   */
  token = "";

  /**
   * Rotating refresh credential for renewing the bearer session.
   *
   * @generated from field: string refresh_token = 4;
   */
  refreshToken = "";

  /**
   * Lifetime of the access token in seconds.
   *
   * @generated from field: int64 expires_in = 5;
   */
  expiresIn = protoInt64.zero;

  /**
   * Remaining lifetime of the current renewable-session window in seconds.
   * A successful refresh can advance this window for an active session.
   *
   * @generated from field: int64 refresh_token_expires_in = 6;
   */
  refreshTokenExpiresIn = protoInt64.zero;

  constructor(data?: PartialMessage<CreateExternalIdentityAccountResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.auth.v1.CreateExternalIdentityAccountResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "login", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "expires_in", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "refresh_token_expires_in", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateExternalIdentityAccountResponse {
    return new CreateExternalIdentityAccountResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateExternalIdentityAccountResponse {
    return new CreateExternalIdentityAccountResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateExternalIdentityAccountResponse {
    return new CreateExternalIdentityAccountResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateExternalIdentityAccountResponse | PlainMessage<CreateExternalIdentityAccountResponse> | undefined, b: CreateExternalIdentityAccountResponse | PlainMessage<CreateExternalIdentityAccountResponse> | undefined): boolean {
    return proto3.util.equals(CreateExternalIdentityAccountResponse, a, b);
  }
}

/**
 * Request to cancel a pending external identity flow.
 *
 * @generated from message chatto.auth.v1.CancelExternalIdentityFlowRequest
 */
export class CancelExternalIdentityFlowRequest extends Message<CancelExternalIdentityFlowRequest> {
  /**
   * Raw pending flow token.
   *
   * @generated from field: string token = 1;
   */
  token = "";

  constructor(data?: PartialMessage<CancelExternalIdentityFlowRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.auth.v1.CancelExternalIdentityFlowRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelExternalIdentityFlowRequest {
    return new CancelExternalIdentityFlowRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelExternalIdentityFlowRequest {
    return new CancelExternalIdentityFlowRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelExternalIdentityFlowRequest {
    return new CancelExternalIdentityFlowRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancelExternalIdentityFlowRequest | PlainMessage<CancelExternalIdentityFlowRequest> | undefined, b: CancelExternalIdentityFlowRequest | PlainMessage<CancelExternalIdentityFlowRequest> | undefined): boolean {
    return proto3.util.equals(CancelExternalIdentityFlowRequest, a, b);
  }
}

/**
 * Result of cancelling a pending external identity flow.
 *
 * @generated from message chatto.auth.v1.CancelExternalIdentityFlowResponse
 */
export class CancelExternalIdentityFlowResponse extends Message<CancelExternalIdentityFlowResponse> {
  /**
   * True when a pending flow was removed or already absent.
   *
   * @generated from field: bool cancelled = 1;
   */
  cancelled = false;

  constructor(data?: PartialMessage<CancelExternalIdentityFlowResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.auth.v1.CancelExternalIdentityFlowResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cancelled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelExternalIdentityFlowResponse {
    return new CancelExternalIdentityFlowResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelExternalIdentityFlowResponse {
    return new CancelExternalIdentityFlowResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelExternalIdentityFlowResponse {
    return new CancelExternalIdentityFlowResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CancelExternalIdentityFlowResponse | PlainMessage<CancelExternalIdentityFlowResponse> | undefined, b: CancelExternalIdentityFlowResponse | PlainMessage<CancelExternalIdentityFlowResponse> | undefined): boolean {
    return proto3.util.equals(CancelExternalIdentityFlowResponse, a, b);
  }
}

/**
 * Request to confirm a pending provider link using the flow capability token.
 *
 * @generated from message chatto.auth.v1.ConfirmExternalIdentityLinkRequest
 */
export class ConfirmExternalIdentityLinkRequest extends Message<ConfirmExternalIdentityLinkRequest> {
  /**
   * Raw pending link token from the provider callback redirect.
   *
   * @generated from field: string token = 1;
   */
  token = "";

  constructor(data?: PartialMessage<ConfirmExternalIdentityLinkRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.auth.v1.ConfirmExternalIdentityLinkRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ConfirmExternalIdentityLinkRequest {
    return new ConfirmExternalIdentityLinkRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ConfirmExternalIdentityLinkRequest {
    return new ConfirmExternalIdentityLinkRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ConfirmExternalIdentityLinkRequest {
    return new ConfirmExternalIdentityLinkRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ConfirmExternalIdentityLinkRequest | PlainMessage<ConfirmExternalIdentityLinkRequest> | undefined, b: ConfirmExternalIdentityLinkRequest | PlainMessage<ConfirmExternalIdentityLinkRequest> | undefined): boolean {
    return proto3.util.equals(ConfirmExternalIdentityLinkRequest, a, b);
  }
}

/**
 * Result of confirming a provider identity link.
 *
 * @generated from message chatto.auth.v1.ConfirmExternalIdentityLinkResponse
 */
export class ConfirmExternalIdentityLinkResponse extends Message<ConfirmExternalIdentityLinkResponse> {
  /**
   * Linked identity metadata.
   *
   * @generated from field: chatto.api.v1.LinkedExternalIdentity linked_identity = 1;
   */
  linkedIdentity?: LinkedExternalIdentity;

  constructor(data?: PartialMessage<ConfirmExternalIdentityLinkResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.auth.v1.ConfirmExternalIdentityLinkResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "linked_identity", kind: "message", T: LinkedExternalIdentity },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ConfirmExternalIdentityLinkResponse {
    return new ConfirmExternalIdentityLinkResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ConfirmExternalIdentityLinkResponse {
    return new ConfirmExternalIdentityLinkResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ConfirmExternalIdentityLinkResponse {
    return new ConfirmExternalIdentityLinkResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ConfirmExternalIdentityLinkResponse | PlainMessage<ConfirmExternalIdentityLinkResponse> | undefined, b: ConfirmExternalIdentityLinkResponse | PlainMessage<ConfirmExternalIdentityLinkResponse> | undefined): boolean {
    return proto3.util.equals(ConfirmExternalIdentityLinkResponse, a, b);
  }
}
