// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/auth/v1/push_subscription_cleanup.proto (package chatto.auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Capability-authenticated request to remove an exact push subscription.
 *
 * @generated from message chatto.auth.v1.DeleteSubscriptionRequest
 */
export class DeleteSubscriptionRequest extends Message<DeleteSubscriptionRequest> {
  /**
   * Complete push service endpoint URL. Its opaque path identifies the exact
   * browser subscription; a provider host alone is not unique.
   *
   * @generated from field: string endpoint = 1;
   */
  endpoint = "";

  /**
   * Authentication secret from the same browser PushSubscription.
   *
   * @generated from field: string auth = 2;
   */
  auth = "";

  /**
   * Per-save capability supplied with the original Subscribe request. Cleanup
   * is a no-op after any later save replaces this token.
   *
   * @generated from field: string cleanup_token = 3;
   */
  cleanupToken = "";

  constructor(data?: PartialMessage<DeleteSubscriptionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.auth.v1.DeleteSubscriptionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "auth", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "cleanup_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteSubscriptionRequest {
    return new DeleteSubscriptionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteSubscriptionRequest {
    return new DeleteSubscriptionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteSubscriptionRequest {
    return new DeleteSubscriptionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteSubscriptionRequest | PlainMessage<DeleteSubscriptionRequest> | undefined, b: DeleteSubscriptionRequest | PlainMessage<DeleteSubscriptionRequest> | undefined): boolean {
    return proto3.util.equals(DeleteSubscriptionRequest, a, b);
  }
}

/**
 * Response from capability-authenticated subscription cleanup.
 *
 * @generated from message chatto.auth.v1.DeleteSubscriptionResponse
 */
export class DeleteSubscriptionResponse extends Message<DeleteSubscriptionResponse> {
  /**
   * True when the idempotent cleanup request completed. It does not reveal
   * whether a matching subscription existed.
   *
   * @generated from field: bool completed = 1;
   */
  completed = false;

  constructor(data?: PartialMessage<DeleteSubscriptionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.auth.v1.DeleteSubscriptionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "completed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteSubscriptionResponse {
    return new DeleteSubscriptionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteSubscriptionResponse {
    return new DeleteSubscriptionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteSubscriptionResponse {
    return new DeleteSubscriptionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteSubscriptionResponse | PlainMessage<DeleteSubscriptionResponse> | undefined, b: DeleteSubscriptionResponse | PlainMessage<DeleteSubscriptionResponse> | undefined): boolean {
    return proto3.util.equals(DeleteSubscriptionResponse, a, b);
  }
}
