// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/auth/v1/push_subscription_cleanup.proto (package chatto.auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteSubscriptionRequest, DeleteSubscriptionResponse } from "./push_subscription_cleanup_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * Public capability-authenticated cleanup for browser push subscriptions.
 *
 * @generated from service chatto.auth.v1.PushSubscriptionCleanupService
 */
export const PushSubscriptionCleanupService = {
  typeName: "chatto.auth.v1.PushSubscriptionCleanupService",
  methods: {
    /**
     * Removes the exact current subscription when its Push API auth secret and
     * per-save cleanup token match. This public RPC requires those capabilities,
     * not an authenticated account session, and does not reveal whether a match
     * existed.
     *
     * @generated from rpc chatto.auth.v1.PushSubscriptionCleanupService.DeleteSubscription
     */
    deleteSubscription: {
      name: "DeleteSubscription",
      I: DeleteSubscriptionRequest,
      O: DeleteSubscriptionResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
  }
} as const;
