// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/account.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteMyAccountRequest, DeleteMyAccountResponse, RequestAccountDeletionRequest, RequestAccountDeletionResponse, UpdatePasswordRequest, UpdatePasswordResponse, UpdateProfileRequest, UpdateProfileResponse, UpdateSettingsRequest, UpdateSettingsResponse } from "./account_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";
import { DisconnectExternalIdentityRequest, DisconnectExternalIdentityResponse, ListExternalIdentitiesRequest, ListExternalIdentitiesResponse, StartExternalIdentityLinkRequest, StartExternalIdentityLinkResponse } from "./external_identities_pb.js";
import { UpdatePresenceRequest, UpdatePresenceResponse } from "./presence_pb.js";
import { DeleteCustomStatusRequest, DeleteCustomStatusResponse, UpdateCustomStatusRequest, UpdateCustomStatusResponse } from "./user_status_pb.js";

/**
 * Self-service account, profile, display preference, presence,
 * custom-status, external identity, and account lifecycle commands for the
 * authenticated user.
 *
 * @generated from service chatto.api.v1.MyAccountService
 */
export const MyAccountService = {
  typeName: "chatto.api.v1.MyAccountService",
  methods: {
    /**
     * Updates the authenticated user's login, display name, and/or bio.
     *
     * @generated from rpc chatto.api.v1.MyAccountService.UpdateProfile
     */
    updateProfile: {
      name: "UpdateProfile",
      I: UpdateProfileRequest,
      O: UpdateProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates or adds the authenticated user's password.
     *
     * @generated from rpc chatto.api.v1.MyAccountService.UpdatePassword
     */
    updatePassword: {
      name: "UpdatePassword",
      I: UpdatePasswordRequest,
      O: UpdatePasswordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates the authenticated user's display preferences.
     *
     * @generated from rpc chatto.api.v1.MyAccountService.UpdateSettings
     */
    updateSettings: {
      name: "UpdateSettings",
      I: UpdateSettingsRequest,
      O: UpdateSettingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists configured external identity providers and identities linked to the
     * authenticated account.
     *
     * @generated from rpc chatto.api.v1.MyAccountService.ListExternalIdentities
     */
    listExternalIdentities: {
      name: "ListExternalIdentities",
      I: ListExternalIdentitiesRequest,
      O: ListExternalIdentitiesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a short-lived browser handoff URL for linking a provider identity
     * to the authenticated account. The provider callback completes through
     * chatto.auth.v1.ExternalIdentityAuthService.ConfirmExternalIdentityLink.
     *
     * @generated from rpc chatto.api.v1.MyAccountService.StartExternalIdentityLink
     */
    startExternalIdentityLink: {
      name: "StartExternalIdentityLink",
      I: StartExternalIdentityLinkRequest,
      O: StartExternalIdentityLinkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Disconnects a provider identity from the authenticated account.
     *
     * @generated from rpc chatto.api.v1.MyAccountService.DisconnectExternalIdentity
     */
    disconnectExternalIdentity: {
      name: "DisconnectExternalIdentity",
      I: DisconnectExternalIdentityRequest,
      O: DisconnectExternalIdentityResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates the current user's live presence status. This state is transient:
     * clients should refresh it periodically while visible, and should stop
     * calling this RPC when the user chooses to appear offline.
     *
     * @generated from rpc chatto.api.v1.MyAccountService.UpdatePresence
     */
    updatePresence: {
      name: "UpdatePresence",
      I: UpdatePresenceRequest,
      O: UpdatePresenceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates or replaces the current user's custom status. Emoji and text are
     * required, and expires_at must be omitted or in the future.
     *
     * @generated from rpc chatto.api.v1.MyAccountService.UpdateCustomStatus
     */
    updateCustomStatus: {
      name: "UpdateCustomStatus",
      I: UpdateCustomStatusRequest,
      O: UpdateCustomStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes the current user's custom status. The call is idempotent and returns
     * the resulting empty status state.
     *
     * @generated from rpc chatto.api.v1.MyAccountService.DeleteCustomStatus
     */
    deleteCustomStatus: {
      name: "DeleteCustomStatus",
      I: DeleteCustomStatusRequest,
      O: DeleteCustomStatusResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
    /**
     * Issues a short-lived token used to confirm self-deletion. Requires
     * user.delete-self.
     *
     * @generated from rpc chatto.api.v1.MyAccountService.RequestAccountDeletion
     */
    requestAccountDeletion: {
      name: "RequestAccountDeletion",
      I: RequestAccountDeletionRequest,
      O: RequestAccountDeletionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Permanently deletes the authenticated account after token validation.
     * Requires user.delete-self.
     *
     * @generated from rpc chatto.api.v1.MyAccountService.DeleteMyAccount
     */
    deleteMyAccount: {
      name: "DeleteMyAccount",
      I: DeleteMyAccountRequest,
      O: DeleteMyAccountResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
