// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/bots.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BatchGetBotsRequest, BatchGetBotsResponse, CreateBotApiKeyRequest, CreateBotApiKeyResponse, CreateBotIncomingWebhookRequest, CreateBotIncomingWebhookResponse, CreateBotRequest, CreateBotResponse, DeleteBotRequest, DeleteBotResponse, GetBotRequest, GetBotResponse, ListBotsRequest, ListBotsResponse, ReassignBotOwnerRequest, ReassignBotOwnerResponse, RevokeBotApiKeyRequest, RevokeBotApiKeyResponse, RevokeBotIncomingWebhookRequest, RevokeBotIncomingWebhookResponse } from "./bots_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * Creates and manages bot accounts owned by human users. Bot API keys cannot
 * call this service.
 *
 * @generated from service chatto.api.v1.BotService
 */
export const BotService = {
  typeName: "chatto.api.v1.BotService",
  methods: {
    /**
     * Lists bots visible to the authenticated caller.
     *
     * @generated from rpc chatto.api.v1.BotService.ListBots
     */
    listBots: {
      name: "ListBots",
      I: ListBotsRequest,
      O: ListBotsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets one visible bot. Returns NOT_FOUND for an unknown bot. Returns
     * PERMISSION_DENIED when the caller is not the owner and has neither
     * bot.manage nor user.manage-accounts.
     *
     * @generated from rpc chatto.api.v1.BotService.GetBot
     */
    getBot: {
      name: "GetBot",
      I: GetBotRequest,
      O: GetBotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets several visible bots. Missing and inaccessible bots are omitted.
     *
     * @generated from rpc chatto.api.v1.BotService.BatchGetBots
     */
    batchGetBots: {
      name: "BatchGetBots",
      I: BatchGetBotsRequest,
      O: BatchGetBotsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a bot owned by the authenticated human caller. Requires bot.create.
     *
     * @generated from rpc chatto.api.v1.BotService.CreateBot
     */
    createBot: {
      name: "CreateBot",
      I: CreateBotRequest,
      O: CreateBotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes a bot and invalidates all of its API keys.
     *
     * @generated from rpc chatto.api.v1.BotService.DeleteBot
     */
    deleteBot: {
      name: "DeleteBot",
      I: DeleteBotRequest,
      O: DeleteBotResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
    /**
     * Creates one named API key. A bot can have at most 20 active API keys.
     *
     * @generated from rpc chatto.api.v1.BotService.CreateBotApiKey
     */
    createBotApiKey: {
      name: "CreateBotApiKey",
      I: CreateBotApiKeyRequest,
      O: CreateBotApiKeyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Revokes one API key without changing other active keys.
     *
     * @generated from rpc chatto.api.v1.BotService.RevokeBotApiKey
     */
    revokeBotApiKey: {
      name: "RevokeBotApiKey",
      I: RevokeBotApiKeyRequest,
      O: RevokeBotApiKeyResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
    /**
     * Creates a named incoming webhook. A bot can have at most 20 active
     * incoming webhooks.
     *
     * @generated from rpc chatto.api.v1.BotService.CreateBotIncomingWebhook
     */
    createBotIncomingWebhook: {
      name: "CreateBotIncomingWebhook",
      I: CreateBotIncomingWebhookRequest,
      O: CreateBotIncomingWebhookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Revokes one incoming webhook without changing other webhooks.
     *
     * @generated from rpc chatto.api.v1.BotService.RevokeBotIncomingWebhook
     */
    revokeBotIncomingWebhook: {
      name: "RevokeBotIncomingWebhook",
      I: RevokeBotIncomingWebhookRequest,
      O: RevokeBotIncomingWebhookResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
    /**
     * Reassigns a bot to another active human owner. Requires bot.manage. The
     * current API keys and configured permission allowlist remain unchanged,
     * while effective permissions immediately use the new owner's ceiling.
     *
     * @generated from rpc chatto.api.v1.BotService.ReassignBotOwner
     */
    reassignBotOwner: {
      name: "ReassignBotOwner",
      I: ReassignBotOwnerRequest,
      O: ReassignBotOwnerResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
  }
} as const;
