// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/api/v1/messages.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Message as Message$1 } from "./message_types_pb.js";

/**
 * Request to create a message in a room or thread.
 *
 * @generated from message chatto.api.v1.CreateMessageRequest
 */
export class CreateMessageRequest extends Message<CreateMessageRequest> {
  /**
   * Required. Room where the message should be created.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Message body text. Required unless attachment_asset_ids is non-empty.
   *
   * @generated from field: string body = 2;
   */
  body = "";

  /**
   * Completed room-scoped asset IDs uploaded by the caller and not yet attached
   * to a message. The server attaches them exclusively and atomically to this
   * message. At most 10 IDs may be supplied.
   *
   * @generated from field: repeated string attachment_asset_ids = 3;
   */
  attachmentAssetIds: string[] = [];

  /**
   * Event ID of the thread root message when posting a thread reply.
   *
   * @generated from field: string thread_root_event_id = 4;
   */
  threadRootEventId = "";

  /**
   * Event ID this message replies to for attribution.
   *
   * @generated from field: string in_reply_to = 5;
   */
  inReplyTo = "";

  /**
   * True to also echo a thread reply into the main room timeline.
   *
   * @generated from field: bool also_send_to_channel = 6;
   */
  alsoSendToChannel = false;

  /**
   * Short-lived token returned by FetchLinkPreview for the selected URL. The
   * server resolves the token to cached, server-fetched metadata during post.
   *
   * @generated from field: string link_preview_token = 10;
   */
  linkPreviewToken = "";

  /**
   * True to establish the new root message as a thread immediately. Requires
   * both message.post and message.post-in-thread. Channel rooms only; cannot
   * be combined with thread_root_event_id.
   *
   * @generated from field: bool create_thread = 11;
   */
  createThread = false;

  constructor(data?: PartialMessage<CreateMessageRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.CreateMessageRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "body", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "attachment_asset_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "in_reply_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "also_send_to_channel", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 10, name: "link_preview_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "create_thread", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateMessageRequest {
    return new CreateMessageRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateMessageRequest {
    return new CreateMessageRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateMessageRequest {
    return new CreateMessageRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateMessageRequest | PlainMessage<CreateMessageRequest> | undefined, b: CreateMessageRequest | PlainMessage<CreateMessageRequest> | undefined): boolean {
    return proto3.util.equals(CreateMessageRequest, a, b);
  }
}

/**
 * Result of creating a message.
 *
 * @generated from message chatto.api.v1.CreateMessageResponse
 */
export class CreateMessageResponse extends Message<CreateMessageResponse> {
  /**
   * Renderable message created by the request.
   *
   * @generated from field: chatto.api.v1.Message message = 1;
   */
  message?: Message$1;

  constructor(data?: PartialMessage<CreateMessageResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.CreateMessageResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "message", T: Message$1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateMessageResponse {
    return new CreateMessageResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateMessageResponse {
    return new CreateMessageResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateMessageResponse {
    return new CreateMessageResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateMessageResponse | PlainMessage<CreateMessageResponse> | undefined, b: CreateMessageResponse | PlainMessage<CreateMessageResponse> | undefined): boolean {
    return proto3.util.equals(CreateMessageResponse, a, b);
  }
}

/**
 * Request to patch a message.
 *
 * @generated from message chatto.api.v1.UpdateMessageRequest
 */
export class UpdateMessageRequest extends Message<UpdateMessageRequest> {
  /**
   * Required. Room containing the message.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Event ID of the message to edit.
   *
   * @generated from field: string event_id = 2;
   */
  eventId = "";

  /**
   * New message body text. Omit to preserve the current body.
   *
   * @generated from field: optional string body = 3;
   */
  body?: string;

  /**
   * For thread replies, whether a channel echo should exist after saving.
   * Omit to preserve the current echo state.
   *
   * @generated from field: optional bool also_send_to_channel = 4;
   */
  alsoSendToChannel?: boolean;

  constructor(data?: PartialMessage<UpdateMessageRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UpdateMessageRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "body", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "also_send_to_channel", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateMessageRequest {
    return new UpdateMessageRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateMessageRequest {
    return new UpdateMessageRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateMessageRequest {
    return new UpdateMessageRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateMessageRequest | PlainMessage<UpdateMessageRequest> | undefined, b: UpdateMessageRequest | PlainMessage<UpdateMessageRequest> | undefined): boolean {
    return proto3.util.equals(UpdateMessageRequest, a, b);
  }
}

/**
 * Result of editing a message.
 *
 * @generated from message chatto.api.v1.UpdateMessageResponse
 */
export class UpdateMessageResponse extends Message<UpdateMessageResponse> {
  /**
   * Renderable message after the edit.
   *
   * @generated from field: chatto.api.v1.Message message = 2;
   */
  message?: Message$1;

  constructor(data?: PartialMessage<UpdateMessageResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UpdateMessageResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "message", kind: "message", T: Message$1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateMessageResponse {
    return new UpdateMessageResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateMessageResponse {
    return new UpdateMessageResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateMessageResponse {
    return new UpdateMessageResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateMessageResponse | PlainMessage<UpdateMessageResponse> | undefined, b: UpdateMessageResponse | PlainMessage<UpdateMessageResponse> | undefined): boolean {
    return proto3.util.equals(UpdateMessageResponse, a, b);
  }
}

/**
 * Request to retract a message.
 *
 * @generated from message chatto.api.v1.DeleteMessageRequest
 */
export class DeleteMessageRequest extends Message<DeleteMessageRequest> {
  /**
   * Required. Room containing the message.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Event ID of the message to retract.
   *
   * @generated from field: string event_id = 2;
   */
  eventId = "";

  constructor(data?: PartialMessage<DeleteMessageRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.DeleteMessageRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteMessageRequest {
    return new DeleteMessageRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteMessageRequest {
    return new DeleteMessageRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteMessageRequest {
    return new DeleteMessageRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteMessageRequest | PlainMessage<DeleteMessageRequest> | undefined, b: DeleteMessageRequest | PlainMessage<DeleteMessageRequest> | undefined): boolean {
    return proto3.util.equals(DeleteMessageRequest, a, b);
  }
}

/**
 * Result of retracting a message.
 *
 * @generated from message chatto.api.v1.DeleteMessageResponse
 */
export class DeleteMessageResponse extends Message<DeleteMessageResponse> {
  /**
   * True when the delete/retract request was accepted.
   *
   * @generated from field: bool deleted = 1;
   */
  deleted = false;

  constructor(data?: PartialMessage<DeleteMessageResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.DeleteMessageResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteMessageResponse {
    return new DeleteMessageResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteMessageResponse {
    return new DeleteMessageResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteMessageResponse {
    return new DeleteMessageResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteMessageResponse | PlainMessage<DeleteMessageResponse> | undefined, b: DeleteMessageResponse | PlainMessage<DeleteMessageResponse> | undefined): boolean {
    return proto3.util.equals(DeleteMessageResponse, a, b);
  }
}

/**
 * Request to remove one attachment from a message.
 *
 * @generated from message chatto.api.v1.DeleteAttachmentRequest
 */
export class DeleteAttachmentRequest extends Message<DeleteAttachmentRequest> {
  /**
   * Required. Room containing the message.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Event ID of the message containing the attachment.
   *
   * @generated from field: string event_id = 2;
   */
  eventId = "";

  /**
   * Required. Attachment ID to remove from the message.
   *
   * @generated from field: string attachment_id = 3;
   */
  attachmentId = "";

  constructor(data?: PartialMessage<DeleteAttachmentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.DeleteAttachmentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "attachment_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteAttachmentRequest {
    return new DeleteAttachmentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteAttachmentRequest {
    return new DeleteAttachmentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteAttachmentRequest {
    return new DeleteAttachmentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteAttachmentRequest | PlainMessage<DeleteAttachmentRequest> | undefined, b: DeleteAttachmentRequest | PlainMessage<DeleteAttachmentRequest> | undefined): boolean {
    return proto3.util.equals(DeleteAttachmentRequest, a, b);
  }
}

/**
 * Result of removing one attachment from a message.
 *
 * @generated from message chatto.api.v1.DeleteAttachmentResponse
 */
export class DeleteAttachmentResponse extends Message<DeleteAttachmentResponse> {
  /**
   * True when the attachment removal was accepted.
   *
   * @generated from field: bool deleted = 1;
   */
  deleted = false;

  constructor(data?: PartialMessage<DeleteAttachmentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.DeleteAttachmentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteAttachmentResponse {
    return new DeleteAttachmentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteAttachmentResponse {
    return new DeleteAttachmentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteAttachmentResponse {
    return new DeleteAttachmentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteAttachmentResponse | PlainMessage<DeleteAttachmentResponse> | undefined, b: DeleteAttachmentResponse | PlainMessage<DeleteAttachmentResponse> | undefined): boolean {
    return proto3.util.equals(DeleteAttachmentResponse, a, b);
  }
}

/**
 * Request to remove the accepted link preview from a message.
 *
 * @generated from message chatto.api.v1.DeleteLinkPreviewRequest
 */
export class DeleteLinkPreviewRequest extends Message<DeleteLinkPreviewRequest> {
  /**
   * Required. Room containing the message.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Event ID of the message containing the link preview.
   *
   * @generated from field: string event_id = 2;
   */
  eventId = "";

  /**
   * Required. URL of the link preview to remove.
   *
   * @generated from field: string url = 3;
   */
  url = "";

  constructor(data?: PartialMessage<DeleteLinkPreviewRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.DeleteLinkPreviewRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteLinkPreviewRequest {
    return new DeleteLinkPreviewRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteLinkPreviewRequest {
    return new DeleteLinkPreviewRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteLinkPreviewRequest {
    return new DeleteLinkPreviewRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteLinkPreviewRequest | PlainMessage<DeleteLinkPreviewRequest> | undefined, b: DeleteLinkPreviewRequest | PlainMessage<DeleteLinkPreviewRequest> | undefined): boolean {
    return proto3.util.equals(DeleteLinkPreviewRequest, a, b);
  }
}

/**
 * Result of removing a link preview from a message.
 *
 * @generated from message chatto.api.v1.DeleteLinkPreviewResponse
 */
export class DeleteLinkPreviewResponse extends Message<DeleteLinkPreviewResponse> {
  /**
   * True when the link preview removal was accepted.
   *
   * @generated from field: bool deleted = 1;
   */
  deleted = false;

  constructor(data?: PartialMessage<DeleteLinkPreviewResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.DeleteLinkPreviewResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteLinkPreviewResponse {
    return new DeleteLinkPreviewResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteLinkPreviewResponse {
    return new DeleteLinkPreviewResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteLinkPreviewResponse {
    return new DeleteLinkPreviewResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteLinkPreviewResponse | PlainMessage<DeleteLinkPreviewResponse> | undefined, b: DeleteLinkPreviewResponse | PlainMessage<DeleteLinkPreviewResponse> | undefined): boolean {
    return proto3.util.equals(DeleteLinkPreviewResponse, a, b);
  }
}

/**
 * Request to read one visible message.
 *
 * @generated from message chatto.api.v1.GetMessageRequest
 */
export class GetMessageRequest extends Message<GetMessageRequest> {
  /**
   * Required. Room containing the message.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Message event ID.
   *
   * @generated from field: string event_id = 2;
   */
  eventId = "";

  constructor(data?: PartialMessage<GetMessageRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetMessageRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMessageRequest {
    return new GetMessageRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMessageRequest {
    return new GetMessageRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMessageRequest {
    return new GetMessageRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetMessageRequest | PlainMessage<GetMessageRequest> | undefined, b: GetMessageRequest | PlainMessage<GetMessageRequest> | undefined): boolean {
    return proto3.util.equals(GetMessageRequest, a, b);
  }
}

/**
 * Response containing one renderable message.
 *
 * @generated from message chatto.api.v1.GetMessageResponse
 */
export class GetMessageResponse extends Message<GetMessageResponse> {
  /**
   * Renderable message.
   *
   * @generated from field: chatto.api.v1.Message message = 1;
   */
  message?: Message$1;

  constructor(data?: PartialMessage<GetMessageResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetMessageResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "message", kind: "message", T: Message$1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMessageResponse {
    return new GetMessageResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMessageResponse {
    return new GetMessageResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMessageResponse {
    return new GetMessageResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetMessageResponse | PlainMessage<GetMessageResponse> | undefined, b: GetMessageResponse | PlainMessage<GetMessageResponse> | undefined): boolean {
    return proto3.util.equals(GetMessageResponse, a, b);
  }
}

/**
 * Request to read many visible messages in one room.
 *
 * @generated from message chatto.api.v1.BatchGetMessagesRequest
 */
export class BatchGetMessagesRequest extends Message<BatchGetMessagesRequest> {
  /**
   * Required. Room containing the messages.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Message event IDs. Missing, retracted, non-message, and
   * wrong-room event IDs are omitted from the response.
   *
   * @generated from field: repeated string event_ids = 2;
   */
  eventIds: string[] = [];

  constructor(data?: PartialMessage<BatchGetMessagesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.BatchGetMessagesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "event_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchGetMessagesRequest {
    return new BatchGetMessagesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchGetMessagesRequest {
    return new BatchGetMessagesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchGetMessagesRequest {
    return new BatchGetMessagesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: BatchGetMessagesRequest | PlainMessage<BatchGetMessagesRequest> | undefined, b: BatchGetMessagesRequest | PlainMessage<BatchGetMessagesRequest> | undefined): boolean {
    return proto3.util.equals(BatchGetMessagesRequest, a, b);
  }
}

/**
 * Response containing renderable messages.
 *
 * @generated from message chatto.api.v1.BatchGetMessagesResponse
 */
export class BatchGetMessagesResponse extends Message<BatchGetMessagesResponse> {
  /**
   * Renderable messages in first-seen request order.
   *
   * @generated from field: repeated chatto.api.v1.Message messages = 1;
   */
  messages: Message$1[] = [];

  constructor(data?: PartialMessage<BatchGetMessagesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.BatchGetMessagesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "messages", kind: "message", T: Message$1, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchGetMessagesResponse {
    return new BatchGetMessagesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchGetMessagesResponse {
    return new BatchGetMessagesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchGetMessagesResponse {
    return new BatchGetMessagesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BatchGetMessagesResponse | PlainMessage<BatchGetMessagesResponse> | undefined, b: BatchGetMessagesResponse | PlainMessage<BatchGetMessagesResponse> | undefined): boolean {
    return proto3.util.equals(BatchGetMessagesResponse, a, b);
  }
}
