// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/api/v1/push_notifications.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Request to store a PushSubscription returned by the browser Push API.
 *
 * @generated from message chatto.api.v1.SubscribePushRequest
 */
export class SubscribePushRequest extends Message<SubscribePushRequest> {
  /**
   * Absolute HTTPS push service endpoint URL. The server rejects redirects and
   * destinations that resolve to private or other special-use addresses.
   *
   * @generated from field: string endpoint = 1;
   */
  endpoint = "";

  /**
   * Client P-256 ECDH public key from PushSubscription.keys.p256dh.
   *
   * @generated from field: string p256dh = 2;
   */
  p256dh = "";

  /**
   * Authentication secret from PushSubscription.keys.auth.
   *
   * @generated from field: string auth = 3;
   */
  auth = "";

  /**
   * Optional browser user-agent string for device identification.
   *
   * @generated from field: optional string user_agent = 4;
   */
  userAgent?: string;

  /**
   * URL host of the Chatto server that supplied the installed web app. The
   * sending server combines this with its own hostname to reconstruct the
   * client route. A host can include a port but no scheme, path, or user info.
   *
   * @generated from field: string client_host = 5;
   */
  clientHost = "";

  /**
   * Random per-save capability generated by the client. A cancelled save can
   * later remove only the record carrying this exact token, even when the same
   * browser PushSubscription has since moved to another account.
   *
   * @generated from field: string cleanup_token = 6;
   */
  cleanupToken = "";

  constructor(data?: PartialMessage<SubscribePushRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.SubscribePushRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "p256dh", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "auth", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "user_agent", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "client_host", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "cleanup_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribePushRequest {
    return new SubscribePushRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribePushRequest {
    return new SubscribePushRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribePushRequest {
    return new SubscribePushRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribePushRequest | PlainMessage<SubscribePushRequest> | undefined, b: SubscribePushRequest | PlainMessage<SubscribePushRequest> | undefined): boolean {
    return proto3.util.equals(SubscribePushRequest, a, b);
  }
}

/**
 * Response from storing a browser push subscription.
 *
 * @generated from message chatto.api.v1.SubscribePushResponse
 */
export class SubscribePushResponse extends Message<SubscribePushResponse> {
  /**
   * True when the subscription was stored.
   *
   * @generated from field: bool subscribed = 1;
   */
  subscribed = false;

  constructor(data?: PartialMessage<SubscribePushResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.SubscribePushResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscribed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribePushResponse {
    return new SubscribePushResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribePushResponse {
    return new SubscribePushResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribePushResponse {
    return new SubscribePushResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SubscribePushResponse | PlainMessage<SubscribePushResponse> | undefined, b: SubscribePushResponse | PlainMessage<SubscribePushResponse> | undefined): boolean {
    return proto3.util.equals(SubscribePushResponse, a, b);
  }
}

/**
 * Request to remove a browser push subscription.
 *
 * @generated from message chatto.api.v1.UnsubscribePushRequest
 */
export class UnsubscribePushRequest extends Message<UnsubscribePushRequest> {
  /**
   * Push service endpoint URL to remove.
   *
   * @generated from field: string endpoint = 1;
   */
  endpoint = "";

  constructor(data?: PartialMessage<UnsubscribePushRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UnsubscribePushRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnsubscribePushRequest {
    return new UnsubscribePushRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnsubscribePushRequest {
    return new UnsubscribePushRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnsubscribePushRequest {
    return new UnsubscribePushRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UnsubscribePushRequest | PlainMessage<UnsubscribePushRequest> | undefined, b: UnsubscribePushRequest | PlainMessage<UnsubscribePushRequest> | undefined): boolean {
    return proto3.util.equals(UnsubscribePushRequest, a, b);
  }
}

/**
 * Response from removing a browser push subscription.
 *
 * @generated from message chatto.api.v1.UnsubscribePushResponse
 */
export class UnsubscribePushResponse extends Message<UnsubscribePushResponse> {
  /**
   * True when the request completed.
   *
   * @generated from field: bool unsubscribed = 1;
   */
  unsubscribed = false;

  constructor(data?: PartialMessage<UnsubscribePushResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UnsubscribePushResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "unsubscribed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnsubscribePushResponse {
    return new UnsubscribePushResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnsubscribePushResponse {
    return new UnsubscribePushResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnsubscribePushResponse {
    return new UnsubscribePushResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UnsubscribePushResponse | PlainMessage<UnsubscribePushResponse> | undefined, b: UnsubscribePushResponse | PlainMessage<UnsubscribePushResponse> | undefined): boolean {
    return proto3.util.equals(UnsubscribePushResponse, a, b);
  }
}

/**
 * Request to test the current user's registered browser push subscriptions.
 *
 * @generated from message chatto.api.v1.SendTestPushNotificationRequest
 */
export class SendTestPushNotificationRequest extends Message<SendTestPushNotificationRequest> {
  constructor(data?: PartialMessage<SendTestPushNotificationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.SendTestPushNotificationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendTestPushNotificationRequest {
    return new SendTestPushNotificationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendTestPushNotificationRequest {
    return new SendTestPushNotificationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendTestPushNotificationRequest {
    return new SendTestPushNotificationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SendTestPushNotificationRequest | PlainMessage<SendTestPushNotificationRequest> | undefined, b: SendTestPushNotificationRequest | PlainMessage<SendTestPushNotificationRequest> | undefined): boolean {
    return proto3.util.equals(SendTestPushNotificationRequest, a, b);
  }
}

/**
 * Result of sending a test Web Push notification.
 *
 * @generated from message chatto.api.v1.SendTestPushNotificationResponse
 */
export class SendTestPushNotificationResponse extends Message<SendTestPushNotificationResponse> {
  /**
   * True when the push provider accepted the notification.
   *
   * @generated from field: bool sent = 1;
   */
  sent = false;

  constructor(data?: PartialMessage<SendTestPushNotificationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.SendTestPushNotificationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sent", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendTestPushNotificationResponse {
    return new SendTestPushNotificationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendTestPushNotificationResponse {
    return new SendTestPushNotificationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendTestPushNotificationResponse {
    return new SendTestPushNotificationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SendTestPushNotificationResponse | PlainMessage<SendTestPushNotificationResponse> | undefined, b: SendTestPushNotificationResponse | PlainMessage<SendTestPushNotificationResponse> | undefined): boolean {
    return proto3.util.equals(SendTestPushNotificationResponse, a, b);
  }
}
