// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/api/v1/read_state.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * Request to mark a room timeline as read.
 *
 * @generated from message chatto.api.v1.MarkRoomAsReadRequest
 */
export class MarkRoomAsReadRequest extends Message<MarkRoomAsReadRequest> {
  /**
   * Required. Room whose timeline should be marked read.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Highest room event ID the current user has read. When set, the event must
   * exist as a root event in the room timeline. Leave empty to mark through the
   * room's current latest root event.
   *
   * @generated from field: string up_to_event_id = 2;
   */
  upToEventId = "";

  constructor(data?: PartialMessage<MarkRoomAsReadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.MarkRoomAsReadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "up_to_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarkRoomAsReadRequest {
    return new MarkRoomAsReadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarkRoomAsReadRequest {
    return new MarkRoomAsReadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarkRoomAsReadRequest {
    return new MarkRoomAsReadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MarkRoomAsReadRequest | PlainMessage<MarkRoomAsReadRequest> | undefined, b: MarkRoomAsReadRequest | PlainMessage<MarkRoomAsReadRequest> | undefined): boolean {
    return proto3.util.equals(MarkRoomAsReadRequest, a, b);
  }
}

/**
 * Result of marking a room timeline as read.
 *
 * Clients can use the previous timestamp to place a local New messages
 * separator. Notification policy controls room Badge attention separately.
 *
 * @generated from message chatto.api.v1.MarkRoomAsReadResponse
 */
export class MarkRoomAsReadResponse extends Message<MarkRoomAsReadResponse> {
  /**
   * New room read timestamp stored for the current user.
   *
   * @generated from field: google.protobuf.Timestamp last_read_at = 1;
   */
  lastReadAt?: Timestamp;

  /**
   * Previous room read timestamp, when one existed.
   *
   * @generated from field: google.protobuf.Timestamp previous_last_read_at = 2;
   */
  previousLastReadAt?: Timestamp;

  constructor(data?: PartialMessage<MarkRoomAsReadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.MarkRoomAsReadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "last_read_at", kind: "message", T: Timestamp },
    { no: 2, name: "previous_last_read_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarkRoomAsReadResponse {
    return new MarkRoomAsReadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarkRoomAsReadResponse {
    return new MarkRoomAsReadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarkRoomAsReadResponse {
    return new MarkRoomAsReadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MarkRoomAsReadResponse | PlainMessage<MarkRoomAsReadResponse> | undefined, b: MarkRoomAsReadResponse | PlainMessage<MarkRoomAsReadResponse> | undefined): boolean {
    return proto3.util.equals(MarkRoomAsReadResponse, a, b);
  }
}

/**
 * Request to mark a message thread as read.
 *
 * @generated from message chatto.api.v1.MarkThreadAsReadRequest
 */
export class MarkThreadAsReadRequest extends Message<MarkThreadAsReadRequest> {
  /**
   * Required. Room containing the thread.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Event ID of the root message for the thread.
   *
   * @generated from field: string thread_root_event_id = 2;
   */
  threadRootEventId = "";

  /**
   * Highest thread event ID the current user has read. The event should belong
   * to the thread identified by thread_root_event_id.
   *
   * @generated from field: string up_to_event_id = 3;
   */
  upToEventId = "";

  constructor(data?: PartialMessage<MarkThreadAsReadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.MarkThreadAsReadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "up_to_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarkThreadAsReadRequest {
    return new MarkThreadAsReadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarkThreadAsReadRequest {
    return new MarkThreadAsReadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarkThreadAsReadRequest {
    return new MarkThreadAsReadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MarkThreadAsReadRequest | PlainMessage<MarkThreadAsReadRequest> | undefined, b: MarkThreadAsReadRequest | PlainMessage<MarkThreadAsReadRequest> | undefined): boolean {
    return proto3.util.equals(MarkThreadAsReadRequest, a, b);
  }
}

/**
 * Result of marking a message thread as read.
 *
 * @generated from message chatto.api.v1.MarkThreadAsReadResponse
 */
export class MarkThreadAsReadResponse extends Message<MarkThreadAsReadResponse> {
  /**
   * Previous thread read timestamp, when one existed.
   *
   * @generated from field: google.protobuf.Timestamp previous_read_at = 1;
   */
  previousReadAt?: Timestamp;

  constructor(data?: PartialMessage<MarkThreadAsReadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.MarkThreadAsReadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "previous_read_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarkThreadAsReadResponse {
    return new MarkThreadAsReadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarkThreadAsReadResponse {
    return new MarkThreadAsReadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarkThreadAsReadResponse {
    return new MarkThreadAsReadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MarkThreadAsReadResponse | PlainMessage<MarkThreadAsReadResponse> | undefined, b: MarkThreadAsReadResponse | PlainMessage<MarkThreadAsReadResponse> | undefined): boolean {
    return proto3.util.equals(MarkThreadAsReadResponse, a, b);
  }
}
