// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/rooms.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddMemberRequest, AddMemberResponse, ArchiveRoomRequest, ArchiveRoomResponse, BanMemberRequest, BanMemberResponse, CreatePinnedMessageRequest, CreatePinnedMessageResponse, CreateRoomRequest, CreateRoomResponse, DeletePinnedMessageRequest, DeletePinnedMessageResponse, JoinRoomGroupRequest, JoinRoomGroupResponse, JoinRoomRequest, JoinRoomResponse, LeaveRoomRequest, LeaveRoomResponse, ListBansRequest, ListBansResponse, ListPinnedMessagesRequest, ListPinnedMessagesResponse, ListRoomAttachmentsRequest, ListRoomAttachmentsResponse, RemoveMemberRequest, RemoveMemberResponse, StartDMRequest, StartDMResponse, UnarchiveRoomRequest, UnarchiveRoomResponse, UnbanMemberRequest, UnbanMemberResponse, UpdateRoomRequest, UpdateRoomResponse, UpdateTypingIndicatorRequest, UpdateTypingIndicatorResponse } from "./rooms_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { BatchGetRoomMembersRequest, BatchGetRoomMembersResponse, GetRoomMemberRequest, GetRoomMemberResponse, ListRoomMembersRequest, ListRoomMembersResponse } from "./member_directory_pb.js";
import { GetRoomEventsAroundRequest, GetRoomEventsAroundResponse, GetRoomEventsRequest, GetRoomEventsResponse } from "./room_timeline_pb.js";
import { MarkRoomAsReadRequest, MarkRoomAsReadResponse } from "./read_state_pb.js";

/**
 * Manages room-scoped operations for the current user.
 *
 * RoomService owns operations whose authorization and state are primarily scoped
 * to one room, including lifecycle, membership, moderation, room timeline reads,
 * room read state, attachments, and live typing. Resource-specific services
 * should still be preferred when an operation is not naturally room-scoped or
 * when the resource needs an independent CRUD/batch surface.
 *
 * @generated from service chatto.api.v1.RoomService
 */
export const RoomService = {
  typeName: "chatto.api.v1.RoomService",
  methods: {
    /**
     * Creates a new channel room in a room group. The caller must be allowed to
     * create rooms in the target group.
     *
     * @generated from rpc chatto.api.v1.RoomService.CreateRoom
     */
    createRoom: {
      name: "CreateRoom",
      I: CreateRoomRequest,
      O: CreateRoomResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a room's editable metadata. The caller must be allowed to manage
     * rooms. Direct-message rooms cannot be universal.
     *
     * @generated from rpc chatto.api.v1.RoomService.UpdateRoom
     */
    updateRoom: {
      name: "UpdateRoom",
      I: UpdateRoomRequest,
      O: UpdateRoomResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Archives a room so it is hidden from active room lists. The caller must be
     * allowed to manage rooms.
     *
     * @generated from rpc chatto.api.v1.RoomService.ArchiveRoom
     */
    archiveRoom: {
      name: "ArchiveRoom",
      I: ArchiveRoomRequest,
      O: ArchiveRoomResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Restores an archived room to active room lists. The caller must be allowed
     * to manage rooms.
     *
     * @generated from rpc chatto.api.v1.RoomService.UnarchiveRoom
     */
    unarchiveRoom: {
      name: "UnarchiveRoom",
      I: UnarchiveRoomRequest,
      O: UnarchiveRoomResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Joins the room as the current user when room permissions allow it.
     *
     * @generated from rpc chatto.api.v1.RoomService.JoinRoom
     */
    joinRoom: {
      name: "JoinRoom",
      I: JoinRoomRequest,
      O: JoinRoomResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Joins every unarchived room in a group that the current user can join.
     * Already-joined and non-joinable rooms are skipped.
     *
     * @generated from rpc chatto.api.v1.RoomService.JoinRoomGroup
     */
    joinRoomGroup: {
      name: "JoinRoomGroup",
      I: JoinRoomGroupRequest,
      O: JoinRoomGroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Starts a direct-message room for the current human user and the requested
     * participant set, or fetches its existing DM. message.post is required
     * only when the DM must be created. A valid request from a bot receives
     * PERMISSION_DENIED and cannot use this RPC to fetch an existing DM.
     *
     * @generated from rpc chatto.api.v1.RoomService.StartDM
     */
    startDM: {
      name: "StartDM",
      I: StartDMRequest,
      O: StartDMResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Leaves the room as the current user. Direct-message and universal rooms
     * cannot be left.
     *
     * @generated from rpc chatto.api.v1.RoomService.LeaveRoom
     */
    leaveRoom: {
      name: "LeaveRoom",
      I: LeaveRoomRequest,
      O: LeaveRoomResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists effective room members. Existing members and room.manage holders may
     * list a channel room; other nonmembers need both room.list and room.join.
     *
     * @generated from rpc chatto.api.v1.RoomService.ListMembers
     */
    listMembers: {
      name: "ListMembers",
      I: ListRoomMembersRequest,
      O: ListRoomMembersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets one explicit member of a room. Existing members and room.manage
     * holders may read channel-room members; DMs remain membership-only. Returns
     * NOT_FOUND when the target is unknown or not a room member.
     *
     * @generated from rpc chatto.api.v1.RoomService.GetMember
     */
    getMember: {
      name: "GetMember",
      I: GetRoomMemberRequest,
      O: GetRoomMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets explicit room member rows for multiple users. Existing members and
     * room.manage holders may read channel-room members; DMs remain
     * membership-only.
     *
     * @generated from rpc chatto.api.v1.RoomService.BatchGetMembers
     */
    batchGetMembers: {
      name: "BatchGetMembers",
      I: BatchGetRoomMembersRequest,
      O: BatchGetRoomMembersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds a user as an explicit member of a channel room. The caller must be
     * allowed to manage the room. Direct-message and universal rooms cannot be
     * managed this way.
     *
     * @generated from rpc chatto.api.v1.RoomService.AddMember
     */
    addMember: {
      name: "AddMember",
      I: AddMemberRequest,
      O: AddMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Removes a user from a channel room's explicit members. The caller must be
     * allowed to manage the room. Direct-message and universal rooms cannot be
     * managed this way.
     *
     * @generated from rpc chatto.api.v1.RoomService.RemoveMember
     */
    removeMember: {
      name: "RemoveMember",
      I: RemoveMemberRequest,
      O: RemoveMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists active channel room bans. The caller must be allowed to moderate room
     * membership bans.
     *
     * @generated from rpc chatto.api.v1.RoomService.ListBans
     */
    listBans: {
      name: "ListBans",
      I: ListBansRequest,
      O: ListBansResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists current message-owned room attachments. Authentication and room
     * membership are required. Channel-room attachments also require message.read
     * or a matching thread relationship with message.read-interactions. DM
     * membership authorizes DM attachments. The server omits attachments from
     * inaccessible threads. Returns PERMISSION_DENIED when the room is
     * inaccessible to the caller.
     *
     * @generated from rpc chatto.api.v1.RoomService.ListRoomAttachments
     */
    listRoomAttachments: {
      name: "ListRoomAttachments",
      I: ListRoomAttachmentsRequest,
      O: ListRoomAttachmentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists current pinned messages in a channel room. Room membership plus
     * message.read or message.read-interactions are required. The server omits
     * pins from threads that the caller cannot read. Direct-message rooms do not
     * support pins.
     *
     * @generated from rpc chatto.api.v1.RoomService.ListPinnedMessages
     */
    listPinnedMessages: {
      name: "ListPinnedMessages",
      I: ListPinnedMessagesRequest,
      O: ListPinnedMessagesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Pins a current message. The caller must have room.manage and must be able
     * to read the message. Repeating an existing pin is idempotent. Direct-message
     * rooms are rejected.
     *
     * @generated from rpc chatto.api.v1.RoomService.CreatePinnedMessage
     */
    createPinnedMessage: {
      name: "CreatePinnedMessage",
      I: CreatePinnedMessageRequest,
      O: CreatePinnedMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Removes a current pin. The caller must have room.manage. Removing a
     * missing pin is idempotent. Direct-message rooms are rejected.
     *
     * @generated from rpc chatto.api.v1.RoomService.DeletePinnedMessage
     */
    deletePinnedMessage: {
      name: "DeletePinnedMessage",
      I: DeletePinnedMessageRequest,
      O: DeletePinnedMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Refreshes the current user's live-only typing indicator for a room or
     * thread. Room membership is required; message posting permission is not.
     *
     * @generated from rpc chatto.api.v1.RoomService.UpdateTypingIndicator
     */
    updateTypingIndicator: {
      name: "UpdateTypingIndicator",
      I: UpdateTypingIndicatorRequest,
      O: UpdateTypingIndicatorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns one page of room timeline events, including related user data
     * needed to render the page. Room membership is required. Channel-room reads
     * also require message.read or message.read-interactions. The server returns
     * only related thread roots for an interaction-scoped caller. DM membership
     * authorizes DM reads.
     *
     * @generated from rpc chatto.api.v1.RoomService.GetRoomEvents
     */
    getRoomEvents: {
      name: "GetRoomEvents",
      I: GetRoomEventsRequest,
      O: GetRoomEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns a room timeline window centered around a specific event. Use this to
     * open a permalink, search result, or notification target in context. Returns
     * NOT_FOUND when the anchor event is missing or not visible in the room
     * timeline. Returns PERMISSION_DENIED when room membership or both read modes
     * are missing, or when the anchor is in an unrelated thread. DM membership
     * authorizes DM reads.
     *
     * @generated from rpc chatto.api.v1.RoomService.GetRoomEventsAround
     */
    getRoomEventsAround: {
      name: "GetRoomEventsAround",
      I: GetRoomEventsAroundRequest,
      O: GetRoomEventsAroundResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Marks a room timeline as read through the supplied event. Room membership
     * is required. Channel-room reads also require message.read or
     * message.read-interactions. DM membership authorizes DM reads. If no event
     * is supplied, the server marks through the latest root event that the caller
     * can read. Clients
     * usually call this after the user has viewed the latest visible event in the
     * room.
     *
     * @generated from rpc chatto.api.v1.RoomService.MarkRoomAsRead
     */
    markRoomAsRead: {
      name: "MarkRoomAsRead",
      I: MarkRoomAsReadRequest,
      O: MarkRoomAsReadResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Bans a member from a channel room. Direct-message rooms cannot be moderated
     * this way, and the target must currently be a room member.
     *
     * @generated from rpc chatto.api.v1.RoomService.BanMember
     */
    banMember: {
      name: "BanMember",
      I: BanMemberRequest,
      O: BanMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Removes an active channel room ban. Calling this when no active ban exists
     * is allowed and still returns success.
     *
     * @generated from rpc chatto.api.v1.RoomService.UnbanMember
     */
    unbanMember: {
      name: "UnbanMember",
      I: UnbanMemberRequest,
      O: UnbanMemberResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
