// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/api/v1/server_state.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * Request for the authenticated message of the day.
 *
 * @generated from message chatto.api.v1.GetMotdRequest
 */
export class GetMotdRequest extends Message<GetMotdRequest> {
  constructor(data?: PartialMessage<GetMotdRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetMotdRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMotdRequest {
    return new GetMotdRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMotdRequest {
    return new GetMotdRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMotdRequest {
    return new GetMotdRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetMotdRequest | PlainMessage<GetMotdRequest> | undefined, b: GetMotdRequest | PlainMessage<GetMotdRequest> | undefined): boolean {
    return proto3.util.equals(GetMotdRequest, a, b);
  }
}

/**
 * Authenticated message of the day response.
 *
 * @generated from message chatto.api.v1.GetMotdResponse
 */
export class GetMotdResponse extends Message<GetMotdResponse> {
  /**
   * Optional message of the day shown to authenticated members.
   *
   * @generated from field: optional string motd = 1;
   */
  motd?: string;

  constructor(data?: PartialMessage<GetMotdResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetMotdResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "motd", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMotdResponse {
    return new GetMotdResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMotdResponse {
    return new GetMotdResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMotdResponse {
    return new GetMotdResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetMotdResponse | PlainMessage<GetMotdResponse> | undefined, b: GetMotdResponse | PlainMessage<GetMotdResponse> | undefined): boolean {
    return proto3.util.equals(GetMotdResponse, a, b);
  }
}

/**
 * Authenticated server runtime settings used by clients.
 *
 * @generated from message chatto.api.v1.ServerRuntimeConfig
 */
export class ServerRuntimeConfig extends Message<ServerRuntimeConfig> {
  /**
   * Whether Web Push notifications are fully configured.
   *
   * @generated from field: bool push_notifications_enabled = 1;
   */
  pushNotificationsEnabled = false;

  /**
   * Optional VAPID public key for Web Push registration.
   *
   * @generated from field: optional string vapid_public_key = 2;
   */
  vapidPublicKey?: string;

  /**
   * Optional LiveKit URL for voice and video calls.
   *
   * @generated from field: optional string livekit_url = 3;
   */
  livekitUrl?: string;

  /**
   * Whether video processing is enabled.
   *
   * @generated from field: bool video_processing_enabled = 5;
   */
  videoProcessingEnabled = false;

  /**
   * Maximum general upload size in bytes.
   *
   * @generated from field: int64 max_upload_size = 6;
   */
  maxUploadSize = protoInt64.zero;

  /**
   * Maximum video upload size in bytes.
   *
   * @generated from field: int64 max_video_upload_size = 7;
   */
  maxVideoUploadSize = protoInt64.zero;

  /**
   * Message edit window in seconds.
   *
   * @generated from field: int32 message_edit_window_seconds = 8;
   */
  messageEditWindowSeconds = 0;

  constructor(data?: PartialMessage<ServerRuntimeConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ServerRuntimeConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "push_notifications_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "vapid_public_key", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "livekit_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "video_processing_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "max_upload_size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "max_video_upload_size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "message_edit_window_seconds", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerRuntimeConfig {
    return new ServerRuntimeConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerRuntimeConfig {
    return new ServerRuntimeConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerRuntimeConfig {
    return new ServerRuntimeConfig().fromJsonString(jsonString, options);
  }

  static equals(a: ServerRuntimeConfig | PlainMessage<ServerRuntimeConfig> | undefined, b: ServerRuntimeConfig | PlainMessage<ServerRuntimeConfig> | undefined): boolean {
    return proto3.util.equals(ServerRuntimeConfig, a, b);
  }
}

/**
 * Request for authenticated server runtime configuration.
 *
 * @generated from message chatto.api.v1.GetRuntimeConfigRequest
 */
export class GetRuntimeConfigRequest extends Message<GetRuntimeConfigRequest> {
  constructor(data?: PartialMessage<GetRuntimeConfigRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetRuntimeConfigRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRuntimeConfigRequest {
    return new GetRuntimeConfigRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRuntimeConfigRequest {
    return new GetRuntimeConfigRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRuntimeConfigRequest {
    return new GetRuntimeConfigRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRuntimeConfigRequest | PlainMessage<GetRuntimeConfigRequest> | undefined, b: GetRuntimeConfigRequest | PlainMessage<GetRuntimeConfigRequest> | undefined): boolean {
    return proto3.util.equals(GetRuntimeConfigRequest, a, b);
  }
}

/**
 * Authenticated server runtime configuration response.
 *
 * @generated from message chatto.api.v1.GetRuntimeConfigResponse
 */
export class GetRuntimeConfigResponse extends Message<GetRuntimeConfigResponse> {
  /**
   * Authenticated runtime settings used by clients.
   *
   * @generated from field: chatto.api.v1.ServerRuntimeConfig runtime = 1;
   */
  runtime?: ServerRuntimeConfig;

  constructor(data?: PartialMessage<GetRuntimeConfigResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetRuntimeConfigResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "runtime", kind: "message", T: ServerRuntimeConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRuntimeConfigResponse {
    return new GetRuntimeConfigResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRuntimeConfigResponse {
    return new GetRuntimeConfigResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRuntimeConfigResponse {
    return new GetRuntimeConfigResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetRuntimeConfigResponse | PlainMessage<GetRuntimeConfigResponse> | undefined, b: GetRuntimeConfigResponse | PlainMessage<GetRuntimeConfigResponse> | undefined): boolean {
    return proto3.util.equals(GetRuntimeConfigResponse, a, b);
  }
}
