// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/api/v1/server.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { ProviderMetadata } from "./common_pb.js";

/**
 * Policy controlling whether self-service account creation requires an invitation.
 *
 * @generated from enum chatto.api.v1.AccountCreationPolicy
 */
export enum AccountCreationPolicy {
  /**
   * Compatibility value used by older servers. Clients treat it as open.
   *
   * @generated from enum value: ACCOUNT_CREATION_POLICY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Self-service account creation does not require an invitation.
   *
   * @generated from enum value: ACCOUNT_CREATION_POLICY_OPEN = 1;
   */
  OPEN = 1,

  /**
   * Every self-service account creation path requires a valid invitation.
   *
   * @generated from enum value: ACCOUNT_CREATION_POLICY_INVITE_ONLY = 2;
   */
  INVITE_ONLY = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(AccountCreationPolicy)
proto3.util.setEnumType(AccountCreationPolicy, "chatto.api.v1.AccountCreationPolicy", [
  { no: 0, name: "ACCOUNT_CREATION_POLICY_UNSPECIFIED" },
  { no: 1, name: "ACCOUNT_CREATION_POLICY_OPEN" },
  { no: 2, name: "ACCOUNT_CREATION_POLICY_INVITE_ONLY" },
]);

/**
 * Public server profile, identity, and branding fields.
 *
 * @generated from message chatto.api.v1.ServerPublicProfile
 */
export class ServerPublicProfile extends Message<ServerPublicProfile> {
  /**
   * Display name of the Chatto server.
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Server software version.
   *
   * @generated from field: string version = 2;
   */
  version = "";

  /**
   * Optional server logo URL.
   *
   * @generated from field: optional string logo_url = 3;
   */
  logoUrl?: string;

  /**
   * Optional server banner URL.
   *
   * @generated from field: optional string banner_url = 4;
   */
  bannerUrl?: string;

  /**
   * Optional welcome message.
   *
   * @generated from field: optional string welcome_message = 5;
   */
  welcomeMessage?: string;

  /**
   * Optional server description.
   *
   * @generated from field: optional string description = 6;
   */
  description?: string;

  constructor(data?: PartialMessage<ServerPublicProfile>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ServerPublicProfile";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "logo_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "banner_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "welcome_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerPublicProfile {
    return new ServerPublicProfile().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerPublicProfile {
    return new ServerPublicProfile().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerPublicProfile {
    return new ServerPublicProfile().fromJsonString(jsonString, options);
  }

  static equals(a: ServerPublicProfile | PlainMessage<ServerPublicProfile> | undefined, b: ServerPublicProfile | PlainMessage<ServerPublicProfile> | undefined): boolean {
    return proto3.util.equals(ServerPublicProfile, a, b);
  }
}

/**
 * Login and registration options exposed before authentication.
 *
 * @generated from message chatto.api.v1.ServerLogin
 */
export class ServerLogin extends Message<ServerLogin> {
  /**
   * Whether users can create accounts through the public UI.
   *
   * @generated from field: bool direct_registration_enabled = 1;
   */
  directRegistrationEnabled = false;

  /**
   * Configured login providers.
   *
   * @generated from field: repeated chatto.api.v1.ProviderMetadata providers = 2;
   */
  providers: ProviderMetadata[] = [];

  /**
   * URL for the legacy authorization flow, when enabled.
   *
   * @generated from field: string authorize_url = 3;
   */
  authorizeUrl = "";

  /**
   * Admission policy for direct registration and provider auto-provisioning.
   *
   * @generated from field: chatto.api.v1.AccountCreationPolicy account_creation_policy = 4;
   */
  accountCreationPolicy = AccountCreationPolicy.UNSPECIFIED;

  /**
   * Whether users can sign in directly with a username or email address and password.
   * Absent on older servers, where clients should treat direct login as enabled.
   *
   * @generated from field: optional bool direct_login_enabled = 5;
   */
  directLoginEnabled?: boolean;

  constructor(data?: PartialMessage<ServerLogin>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ServerLogin";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "direct_registration_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "providers", kind: "message", T: ProviderMetadata, repeated: true },
    { no: 3, name: "authorize_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "account_creation_policy", kind: "enum", T: proto3.getEnumType(AccountCreationPolicy) },
    { no: 5, name: "direct_login_enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerLogin {
    return new ServerLogin().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerLogin {
    return new ServerLogin().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerLogin {
    return new ServerLogin().fromJsonString(jsonString, options);
  }

  static equals(a: ServerLogin | PlainMessage<ServerLogin> | undefined, b: ServerLogin | PlainMessage<ServerLogin> | undefined): boolean {
    return proto3.util.equals(ServerLogin, a, b);
  }
}
