// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/api/v1/threads.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Message as Message$1, ThreadSummary } from "./message_types_pb.js";
import { RoomSummary } from "./rooms_pb.js";
import { PageInfo, PageRequest } from "./pagination_pb.js";
import { RoomTimelineIncludes } from "./room_timeline_pb.js";

/**
 * Current follow state for one thread and viewer.
 *
 * @generated from message chatto.api.v1.ThreadFollowState
 */
export class ThreadFollowState extends Message<ThreadFollowState> {
  /**
   * Room containing the thread.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Event ID of the root message for the thread.
   *
   * @generated from field: string thread_root_event_id = 2;
   */
  threadRootEventId = "";

  /**
   * True when the current user follows the thread.
   *
   * @generated from field: bool following = 3;
   */
  following = false;

  constructor(data?: PartialMessage<ThreadFollowState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ThreadFollowState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "following", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ThreadFollowState {
    return new ThreadFollowState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ThreadFollowState {
    return new ThreadFollowState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ThreadFollowState {
    return new ThreadFollowState().fromJsonString(jsonString, options);
  }

  static equals(a: ThreadFollowState | PlainMessage<ThreadFollowState> | undefined, b: ThreadFollowState | PlainMessage<ThreadFollowState> | undefined): boolean {
    return proto3.util.equals(ThreadFollowState, a, b);
  }
}

/**
 * Request to follow one message thread.
 *
 * @generated from message chatto.api.v1.FollowThreadRequest
 */
export class FollowThreadRequest extends Message<FollowThreadRequest> {
  /**
   * Required. Room containing the thread.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Event ID of the root message for the thread.
   *
   * @generated from field: string thread_root_event_id = 2;
   */
  threadRootEventId = "";

  constructor(data?: PartialMessage<FollowThreadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.FollowThreadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FollowThreadRequest {
    return new FollowThreadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FollowThreadRequest {
    return new FollowThreadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FollowThreadRequest {
    return new FollowThreadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: FollowThreadRequest | PlainMessage<FollowThreadRequest> | undefined, b: FollowThreadRequest | PlainMessage<FollowThreadRequest> | undefined): boolean {
    return proto3.util.equals(FollowThreadRequest, a, b);
  }
}

/**
 * Result of following a thread.
 *
 * @generated from message chatto.api.v1.FollowThreadResponse
 */
export class FollowThreadResponse extends Message<FollowThreadResponse> {
  /**
   * True when the current user follows the thread after the operation.
   *
   * @generated from field: bool following = 1;
   */
  following = false;

  /**
   * Current follow state after the operation.
   *
   * @generated from field: chatto.api.v1.ThreadFollowState state = 2;
   */
  state?: ThreadFollowState;

  constructor(data?: PartialMessage<FollowThreadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.FollowThreadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "following", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "state", kind: "message", T: ThreadFollowState },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FollowThreadResponse {
    return new FollowThreadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FollowThreadResponse {
    return new FollowThreadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FollowThreadResponse {
    return new FollowThreadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: FollowThreadResponse | PlainMessage<FollowThreadResponse> | undefined, b: FollowThreadResponse | PlainMessage<FollowThreadResponse> | undefined): boolean {
    return proto3.util.equals(FollowThreadResponse, a, b);
  }
}

/**
 * Request to stop following one message thread.
 *
 * @generated from message chatto.api.v1.UnfollowThreadRequest
 */
export class UnfollowThreadRequest extends Message<UnfollowThreadRequest> {
  /**
   * Required. Room containing the thread.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Event ID of the root message for the thread.
   *
   * @generated from field: string thread_root_event_id = 2;
   */
  threadRootEventId = "";

  constructor(data?: PartialMessage<UnfollowThreadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UnfollowThreadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnfollowThreadRequest {
    return new UnfollowThreadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnfollowThreadRequest {
    return new UnfollowThreadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnfollowThreadRequest {
    return new UnfollowThreadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UnfollowThreadRequest | PlainMessage<UnfollowThreadRequest> | undefined, b: UnfollowThreadRequest | PlainMessage<UnfollowThreadRequest> | undefined): boolean {
    return proto3.util.equals(UnfollowThreadRequest, a, b);
  }
}

/**
 * Result of unfollowing a thread.
 *
 * @generated from message chatto.api.v1.UnfollowThreadResponse
 */
export class UnfollowThreadResponse extends Message<UnfollowThreadResponse> {
  /**
   * True when the current user follows the thread after the operation.
   *
   * @generated from field: bool following = 1;
   */
  following = false;

  /**
   * Current follow state after the operation.
   *
   * @generated from field: chatto.api.v1.ThreadFollowState state = 2;
   */
  state?: ThreadFollowState;

  constructor(data?: PartialMessage<UnfollowThreadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UnfollowThreadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "following", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "state", kind: "message", T: ThreadFollowState },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnfollowThreadResponse {
    return new UnfollowThreadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnfollowThreadResponse {
    return new UnfollowThreadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnfollowThreadResponse {
    return new UnfollowThreadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UnfollowThreadResponse | PlainMessage<UnfollowThreadResponse> | undefined, b: UnfollowThreadResponse | PlainMessage<UnfollowThreadResponse> | undefined): boolean {
    return proto3.util.equals(UnfollowThreadResponse, a, b);
  }
}

/**
 * One followed thread for the current user.
 *
 * @generated from message chatto.api.v1.FollowedThread
 */
export class FollowedThread extends Message<FollowedThread> {
  /**
   * Renderable root message, when the root is still visible.
   *
   * @generated from field: chatto.api.v1.Message root_message = 4;
   */
  rootMessage?: Message$1;

  /**
   * Room containing the thread.
   *
   * @generated from field: chatto.api.v1.RoomSummary room = 8;
   */
  room?: RoomSummary;

  /**
   * Aggregated thread state.
   *
   * @generated from field: chatto.api.v1.ThreadSummary thread = 9;
   */
  thread?: ThreadSummary;

  /**
   * Most recent visible reply, when the thread has one.
   *
   * @generated from field: chatto.api.v1.Message latest_reply = 10;
   */
  latestReply?: Message$1;

  constructor(data?: PartialMessage<FollowedThread>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.FollowedThread";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 4, name: "root_message", kind: "message", T: Message$1 },
    { no: 8, name: "room", kind: "message", T: RoomSummary },
    { no: 9, name: "thread", kind: "message", T: ThreadSummary },
    { no: 10, name: "latest_reply", kind: "message", T: Message$1 },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FollowedThread {
    return new FollowedThread().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FollowedThread {
    return new FollowedThread().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FollowedThread {
    return new FollowedThread().fromJsonString(jsonString, options);
  }

  static equals(a: FollowedThread | PlainMessage<FollowedThread> | undefined, b: FollowedThread | PlainMessage<FollowedThread> | undefined): boolean {
    return proto3.util.equals(FollowedThread, a, b);
  }
}

/**
 * Request for a page of followed threads for the current user.
 *
 * @generated from message chatto.api.v1.ListFollowedThreadsRequest
 */
export class ListFollowedThreadsRequest extends Message<ListFollowedThreadsRequest> {
  /**
   * Page request. Defaults to 20 results when absent or limit is zero.
   *
   * @generated from field: chatto.api.v1.PageRequest page = 3;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListFollowedThreadsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ListFollowedThreadsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListFollowedThreadsRequest {
    return new ListFollowedThreadsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListFollowedThreadsRequest {
    return new ListFollowedThreadsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListFollowedThreadsRequest {
    return new ListFollowedThreadsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListFollowedThreadsRequest | PlainMessage<ListFollowedThreadsRequest> | undefined, b: ListFollowedThreadsRequest | PlainMessage<ListFollowedThreadsRequest> | undefined): boolean {
    return proto3.util.equals(ListFollowedThreadsRequest, a, b);
  }
}

/**
 * Response containing one followed-thread page.
 *
 * @generated from message chatto.api.v1.ListFollowedThreadsResponse
 */
export class ListFollowedThreadsResponse extends Message<ListFollowedThreadsResponse> {
  /**
   * Followed threads in newest-activity-first order.
   *
   * @generated from field: repeated chatto.api.v1.FollowedThread threads = 1;
   */
  threads: FollowedThread[] = [];

  /**
   * Hot-path related entities needed to render this feed page without
   * per-thread hydration.
   *
   * @generated from field: chatto.api.v1.RoomTimelineIncludes includes = 4;
   */
  includes?: RoomTimelineIncludes;

  /**
   * Page metadata.
   *
   * @generated from field: chatto.api.v1.PageInfo page = 5;
   */
  page?: PageInfo;

  constructor(data?: PartialMessage<ListFollowedThreadsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ListFollowedThreadsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "threads", kind: "message", T: FollowedThread, repeated: true },
    { no: 4, name: "includes", kind: "message", T: RoomTimelineIncludes },
    { no: 5, name: "page", kind: "message", T: PageInfo },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListFollowedThreadsResponse {
    return new ListFollowedThreadsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListFollowedThreadsResponse {
    return new ListFollowedThreadsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListFollowedThreadsResponse {
    return new ListFollowedThreadsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListFollowedThreadsResponse | PlainMessage<ListFollowedThreadsResponse> | undefined, b: ListFollowedThreadsResponse | PlainMessage<ListFollowedThreadsResponse> | undefined): boolean {
    return proto3.util.equals(ListFollowedThreadsResponse, a, b);
  }
}
