// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/threads.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FollowThreadRequest, FollowThreadResponse, ListFollowedThreadsRequest, ListFollowedThreadsResponse, UnfollowThreadRequest, UnfollowThreadResponse } from "./threads_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { GetThreadEventsAroundRequest, GetThreadEventsAroundResponse, GetThreadEventsRequest, GetThreadEventsResponse } from "./room_timeline_pb.js";
import { MarkThreadAsReadRequest, MarkThreadAsReadResponse } from "./read_state_pb.js";

/**
 * Manages thread follow state for the current user.
 *
 * @generated from service chatto.api.v1.ThreadService
 */
export const ThreadService = {
  typeName: "chatto.api.v1.ThreadService",
  methods: {
    /**
     * Returns followed threads in rooms where the current user is a member.
     * Channel-room threads also require message.read or an active relationship
     * with message.read-interactions. Historical DM threads use DM membership.
     * The result includes enough root and latest-reply data for clients to render
     * the list without extra per-thread fetches.
     * Activity can reorder the live result between offset pages. After a thread
     * activity update, clients must restart paging at offset zero.
     *
     * @generated from rpc chatto.api.v1.ThreadService.ListFollowedThreads
     */
    listFollowedThreads: {
      name: "ListFollowedThreads",
      I: ListFollowedThreadsRequest,
      O: ListFollowedThreadsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Follows a thread for the current user. Room membership plus message.read or
     * an active relationship with message.read-interactions are required. DMs do
     * not support current thread actions.
     * Followed threads can be surfaced in clients and can participate in thread
     * notification behavior.
     *
     * @generated from rpc chatto.api.v1.ThreadService.FollowThread
     */
    followThread: {
      name: "FollowThread",
      I: FollowThreadRequest,
      O: FollowThreadResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Stops following a thread for the current user. Room membership plus
     * message.read or an active relationship with message.read-interactions are
     * required. DMs do not support current thread actions. The response reports
     * the resulting follow state so clients can update local UI immediately.
     *
     * @generated from rpc chatto.api.v1.ThreadService.UnfollowThread
     */
    unfollowThread: {
      name: "UnfollowThread",
      I: UnfollowThreadRequest,
      O: UnfollowThreadResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns one page of events in a message thread. Room membership is
     * required. Channel-room reads also require message.read or an active
     * relationship with message.read-interactions. Historical DM threads use DM
     * membership. Initial pages include the thread root message; cursor pages
     * return replies in the requested direction.
     *
     * @generated from rpc chatto.api.v1.ThreadService.GetThreadEvents
     */
    getThreadEvents: {
      name: "GetThreadEvents",
      I: GetThreadEventsRequest,
      O: GetThreadEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns a thread timeline window centered around a specific event. Use this
     * to open a reply from a notification or search result in context. Returns
     * NOT_FOUND when the thread root or anchor event is missing or hidden.
     * Returns PERMISSION_DENIED when room membership is missing, both read modes
     * are missing, or an interaction-scoped account has no relationship with the
     * thread. Historical DM threads use DM membership.
     *
     * @generated from rpc chatto.api.v1.ThreadService.GetThreadEventsAround
     */
    getThreadEventsAround: {
      name: "GetThreadEventsAround",
      I: GetThreadEventsAroundRequest,
      O: GetThreadEventsAroundResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Marks a thread timeline as read through the supplied event without changing
     * the room-level read marker. Room membership plus message.read or an active
     * relationship with message.read-interactions are required. DMs do not
     * support current thread actions.
     *
     * @generated from rpc chatto.api.v1.ThreadService.MarkThreadAsRead
     */
    markThreadAsRead: {
      name: "MarkThreadAsRead",
      I: MarkThreadAsReadRequest,
      O: MarkThreadAsReadResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
