// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/user_service.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BatchGetUsersRequest, BatchGetUsersResponse, DeleteAvatarRequest, DeleteAvatarResponse, GetUserRequest, GetUserResponse, ListUsersRequest, ListUsersResponse, UploadAvatarRequest, UploadAvatarResponse } from "./user_service_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * Reads users and manages public user avatars.
 *
 * @generated from service chatto.api.v1.UserService
 */
export const UserService = {
  typeName: "chatto.api.v1.UserService",
  methods: {
    /**
     * Lists users visible to the authenticated user. Admin-sensitive account
     * fields stay out of this public row shape.
     *
     * @generated from rpc chatto.api.v1.UserService.ListUsers
     */
    listUsers: {
      name: "ListUsers",
      I: ListUsersRequest,
      O: ListUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets one visible user by user ID or login. Returns NOT_FOUND when the
     * target is unknown.
     *
     * @generated from rpc chatto.api.v1.UserService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets visible user rows for multiple stable user IDs. Unknown IDs are
     * omitted from the response.
     *
     * @generated from rpc chatto.api.v1.UserService.BatchGetUsers
     */
    batchGetUsers: {
      name: "BatchGetUsers",
      I: BatchGetUsersRequest,
      O: BatchGetUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Uploads and sets an avatar for the target user. Users can update
     * themselves. Updating another human requires user.manage-accounts.
     * Updating a bot requires ownership, user.manage-accounts, or bot.manage.
     * A bot cannot target another account. Unknown or deleted targets return
     * NOT_FOUND. Invalid IDs or missing images return INVALID_ARGUMENT.
     *
     * @generated from rpc chatto.api.v1.UserService.UploadAvatar
     */
    uploadAvatar: {
      name: "UploadAvatar",
      I: UploadAvatarRequest,
      O: UploadAvatarResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes the target user's avatar. Authorization matches UploadAvatar. The
     * call is idempotent. Unknown or deleted targets return NOT_FOUND. An
     * invalid ID returns INVALID_ARGUMENT.
     *
     * @generated from rpc chatto.api.v1.UserService.DeleteAvatar
     */
    deleteAvatar: {
      name: "DeleteAvatar",
      I: DeleteAvatarRequest,
      O: DeleteAvatarResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
  }
} as const;
