// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/api/v1/user_status.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * Custom status shown on a user profile, separate from presence.
 *
 * @generated from message chatto.api.v1.CustomUserStatus
 */
export class CustomUserStatus extends Message<CustomUserStatus> {
  /**
   * Short emoji marker displayed with the status.
   *
   * @generated from field: string emoji = 1;
   */
  emoji = "";

  /**
   * User-written status text.
   *
   * @generated from field: string text = 2;
   */
  text = "";

  /**
   * Optional time after which clients should stop showing the status.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<CustomUserStatus>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.CustomUserStatus";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "emoji", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "expires_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CustomUserStatus {
    return new CustomUserStatus().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CustomUserStatus {
    return new CustomUserStatus().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CustomUserStatus {
    return new CustomUserStatus().fromJsonString(jsonString, options);
  }

  static equals(a: CustomUserStatus | PlainMessage<CustomUserStatus> | undefined, b: CustomUserStatus | PlainMessage<CustomUserStatus> | undefined): boolean {
    return proto3.util.equals(CustomUserStatus, a, b);
  }
}

/**
 * Request to update or replace the current user's custom status.
 *
 * @generated from message chatto.api.v1.UpdateCustomStatusRequest
 */
export class UpdateCustomStatusRequest extends Message<UpdateCustomStatusRequest> {
  /**
   * Short emoji marker displayed with the status.
   *
   * @generated from field: string emoji = 1;
   */
  emoji = "";

  /**
   * User-written status text.
   *
   * @generated from field: string text = 2;
   */
  text = "";

  /**
   * Optional future time after which clients should stop showing the status.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<UpdateCustomStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UpdateCustomStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "emoji", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "expires_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateCustomStatusRequest {
    return new UpdateCustomStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateCustomStatusRequest {
    return new UpdateCustomStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateCustomStatusRequest {
    return new UpdateCustomStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateCustomStatusRequest | PlainMessage<UpdateCustomStatusRequest> | undefined, b: UpdateCustomStatusRequest | PlainMessage<UpdateCustomStatusRequest> | undefined): boolean {
    return proto3.util.equals(UpdateCustomStatusRequest, a, b);
  }
}

/**
 * Result of updating the current user's custom status.
 *
 * @generated from message chatto.api.v1.UpdateCustomStatusResponse
 */
export class UpdateCustomStatusResponse extends Message<UpdateCustomStatusResponse> {
  /**
   * Stored custom status after validation and normalization.
   *
   * @generated from field: chatto.api.v1.CustomUserStatus status = 1;
   */
  status?: CustomUserStatus;

  constructor(data?: PartialMessage<UpdateCustomStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UpdateCustomStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "message", T: CustomUserStatus },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateCustomStatusResponse {
    return new UpdateCustomStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateCustomStatusResponse {
    return new UpdateCustomStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateCustomStatusResponse {
    return new UpdateCustomStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateCustomStatusResponse | PlainMessage<UpdateCustomStatusResponse> | undefined, b: UpdateCustomStatusResponse | PlainMessage<UpdateCustomStatusResponse> | undefined): boolean {
    return proto3.util.equals(UpdateCustomStatusResponse, a, b);
  }
}

/**
 * Request to delete the current user's custom status.
 *
 * @generated from message chatto.api.v1.DeleteCustomStatusRequest
 */
export class DeleteCustomStatusRequest extends Message<DeleteCustomStatusRequest> {
  constructor(data?: PartialMessage<DeleteCustomStatusRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.DeleteCustomStatusRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteCustomStatusRequest {
    return new DeleteCustomStatusRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteCustomStatusRequest {
    return new DeleteCustomStatusRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteCustomStatusRequest {
    return new DeleteCustomStatusRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteCustomStatusRequest | PlainMessage<DeleteCustomStatusRequest> | undefined, b: DeleteCustomStatusRequest | PlainMessage<DeleteCustomStatusRequest> | undefined): boolean {
    return proto3.util.equals(DeleteCustomStatusRequest, a, b);
  }
}

/**
 * Result of deleting the current user's custom status.
 *
 * @generated from message chatto.api.v1.DeleteCustomStatusResponse
 */
export class DeleteCustomStatusResponse extends Message<DeleteCustomStatusResponse> {
  /**
   * Current custom status after the operation. Usually absent after a clear.
   *
   * @generated from field: chatto.api.v1.CustomUserStatus status = 1;
   */
  status?: CustomUserStatus;

  constructor(data?: PartialMessage<DeleteCustomStatusResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.DeleteCustomStatusResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "message", T: CustomUserStatus },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteCustomStatusResponse {
    return new DeleteCustomStatusResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteCustomStatusResponse {
    return new DeleteCustomStatusResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteCustomStatusResponse {
    return new DeleteCustomStatusResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteCustomStatusResponse | PlainMessage<DeleteCustomStatusResponse> | undefined, b: DeleteCustomStatusResponse | PlainMessage<DeleteCustomStatusResponse> | undefined): boolean {
    return proto3.util.equals(DeleteCustomStatusResponse, a, b);
  }
}
