// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/api/v1/voice_calls.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { RoomSummary } from "./rooms_pb.js";
import { User } from "./users_pb.js";

/**
 * Native companion publisher kind.
 *
 * @generated from enum chatto.api.v1.CallMediaPublisherKind
 */
export enum CallMediaPublisherKind {
  /**
   * The publisher kind was not specified.
   *
   * @generated from enum value: CALL_MEDIA_PUBLISHER_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Native game-window video and application audio.
   *
   * @generated from enum value: CALL_MEDIA_PUBLISHER_KIND_GAME_SHARE = 1;
   */
  GAME_SHARE = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(CallMediaPublisherKind)
proto3.util.setEnumType(CallMediaPublisherKind, "chatto.api.v1.CallMediaPublisherKind", [
  { no: 0, name: "CALL_MEDIA_PUBLISHER_KIND_UNSPECIFIED" },
  { no: 1, name: "CALL_MEDIA_PUBLISHER_KIND_GAME_SHARE" },
]);

/**
 * Request for active room call snapshots.
 *
 * @generated from message chatto.api.v1.ListActiveCallsRequest
 */
export class ListActiveCallsRequest extends Message<ListActiveCallsRequest> {
  constructor(data?: PartialMessage<ListActiveCallsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ListActiveCallsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListActiveCallsRequest {
    return new ListActiveCallsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListActiveCallsRequest {
    return new ListActiveCallsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListActiveCallsRequest {
    return new ListActiveCallsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListActiveCallsRequest | PlainMessage<ListActiveCallsRequest> | undefined, b: ListActiveCallsRequest | PlainMessage<ListActiveCallsRequest> | undefined): boolean {
    return proto3.util.equals(ListActiveCallsRequest, a, b);
  }
}

/**
 * Finite runtime snapshot of active room calls.
 *
 * @generated from message chatto.api.v1.ListActiveCallsResponse
 */
export class ListActiveCallsResponse extends Message<ListActiveCallsResponse> {
  /**
   * Active calls in room order returned by the call-state projection.
   *
   * @generated from field: repeated chatto.api.v1.ActiveCall calls = 1;
   */
  calls: ActiveCall[] = [];

  constructor(data?: PartialMessage<ListActiveCallsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ListActiveCallsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "calls", kind: "message", T: ActiveCall, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListActiveCallsResponse {
    return new ListActiveCallsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListActiveCallsResponse {
    return new ListActiveCallsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListActiveCallsResponse {
    return new ListActiveCallsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListActiveCallsResponse | PlainMessage<ListActiveCallsResponse> | undefined, b: ListActiveCallsResponse | PlainMessage<ListActiveCallsResponse> | undefined): boolean {
    return proto3.util.equals(ListActiveCallsResponse, a, b);
  }
}

/**
 * Current active call snapshot for one room.
 *
 * @generated from message chatto.api.v1.ActiveCall
 */
export class ActiveCall extends Message<ActiveCall> {
  /**
   * Room containing the active call.
   *
   * @generated from field: chatto.api.v1.RoomSummary room = 4;
   */
  room?: RoomSummary;

  /**
   * Active call session ID.
   *
   * @generated from field: string call_id = 2;
   */
  callId = "";

  /**
   * Participants currently projected for this call.
   *
   * @generated from field: repeated chatto.api.v1.CallParticipant participants = 3;
   */
  participants: CallParticipant[] = [];

  constructor(data?: PartialMessage<ActiveCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ActiveCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 4, name: "room", kind: "message", T: RoomSummary },
    { no: 2, name: "call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "participants", kind: "message", T: CallParticipant, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ActiveCall {
    return new ActiveCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ActiveCall {
    return new ActiveCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ActiveCall {
    return new ActiveCall().fromJsonString(jsonString, options);
  }

  static equals(a: ActiveCall | PlainMessage<ActiveCall> | undefined, b: ActiveCall | PlainMessage<ActiveCall> | undefined): boolean {
    return proto3.util.equals(ActiveCall, a, b);
  }
}

/**
 * Request for one room's active call snapshot.
 *
 * @generated from message chatto.api.v1.GetActiveCallRequest
 */
export class GetActiveCallRequest extends Message<GetActiveCallRequest> {
  /**
   * Required. Room whose active call should be inspected.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<GetActiveCallRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetActiveCallRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetActiveCallRequest {
    return new GetActiveCallRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetActiveCallRequest {
    return new GetActiveCallRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetActiveCallRequest {
    return new GetActiveCallRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetActiveCallRequest | PlainMessage<GetActiveCallRequest> | undefined, b: GetActiveCallRequest | PlainMessage<GetActiveCallRequest> | undefined): boolean {
    return proto3.util.equals(GetActiveCallRequest, a, b);
  }
}

/**
 * Response for one room's active call snapshot.
 *
 * @generated from message chatto.api.v1.GetActiveCallResponse
 */
export class GetActiveCallResponse extends Message<GetActiveCallResponse> {
  /**
   * Current active call.
   *
   * @generated from field: chatto.api.v1.ActiveCall call = 1;
   */
  call?: ActiveCall;

  constructor(data?: PartialMessage<GetActiveCallResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetActiveCallResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "call", kind: "message", T: ActiveCall },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetActiveCallResponse {
    return new GetActiveCallResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetActiveCallResponse {
    return new GetActiveCallResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetActiveCallResponse {
    return new GetActiveCallResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetActiveCallResponse | PlainMessage<GetActiveCallResponse> | undefined, b: GetActiveCallResponse | PlainMessage<GetActiveCallResponse> | undefined): boolean {
    return proto3.util.equals(GetActiveCallResponse, a, b);
  }
}

/**
 * Request active call snapshots for many rooms.
 *
 * @generated from message chatto.api.v1.BatchGetActiveCallsRequest
 */
export class BatchGetActiveCallsRequest extends Message<BatchGetActiveCallsRequest> {
  /**
   * Required room IDs. Unknown, inaccessible, and inactive rooms are omitted.
   *
   * @generated from field: repeated string room_ids = 1;
   */
  roomIds: string[] = [];

  constructor(data?: PartialMessage<BatchGetActiveCallsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.BatchGetActiveCallsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchGetActiveCallsRequest {
    return new BatchGetActiveCallsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchGetActiveCallsRequest {
    return new BatchGetActiveCallsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchGetActiveCallsRequest {
    return new BatchGetActiveCallsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: BatchGetActiveCallsRequest | PlainMessage<BatchGetActiveCallsRequest> | undefined, b: BatchGetActiveCallsRequest | PlainMessage<BatchGetActiveCallsRequest> | undefined): boolean {
    return proto3.util.equals(BatchGetActiveCallsRequest, a, b);
  }
}

/**
 * Active call batch response.
 *
 * @generated from message chatto.api.v1.BatchGetActiveCallsResponse
 */
export class BatchGetActiveCallsResponse extends Message<BatchGetActiveCallsResponse> {
  /**
   * Active calls in first-seen request order.
   *
   * @generated from field: repeated chatto.api.v1.ActiveCall calls = 1;
   */
  calls: ActiveCall[] = [];

  constructor(data?: PartialMessage<BatchGetActiveCallsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.BatchGetActiveCallsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "calls", kind: "message", T: ActiveCall, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchGetActiveCallsResponse {
    return new BatchGetActiveCallsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchGetActiveCallsResponse {
    return new BatchGetActiveCallsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchGetActiveCallsResponse {
    return new BatchGetActiveCallsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BatchGetActiveCallsResponse | PlainMessage<BatchGetActiveCallsResponse> | undefined, b: BatchGetActiveCallsResponse | PlainMessage<BatchGetActiveCallsResponse> | undefined): boolean {
    return proto3.util.equals(BatchGetActiveCallsResponse, a, b);
  }
}

/**
 * Request for participants in a room call.
 *
 * @generated from message chatto.api.v1.ListCallParticipantsRequest
 */
export class ListCallParticipantsRequest extends Message<ListCallParticipantsRequest> {
  /**
   * Required. Room whose active call should be inspected.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<ListCallParticipantsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ListCallParticipantsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListCallParticipantsRequest {
    return new ListCallParticipantsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListCallParticipantsRequest {
    return new ListCallParticipantsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListCallParticipantsRequest {
    return new ListCallParticipantsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListCallParticipantsRequest | PlainMessage<ListCallParticipantsRequest> | undefined, b: ListCallParticipantsRequest | PlainMessage<ListCallParticipantsRequest> | undefined): boolean {
    return proto3.util.equals(ListCallParticipantsRequest, a, b);
  }
}

/**
 * Finite runtime snapshot of participants in one room call.
 *
 * @generated from message chatto.api.v1.ListCallParticipantsResponse
 */
export class ListCallParticipantsResponse extends Message<ListCallParticipantsResponse> {
  /**
   * Participants currently projected for the room call.
   *
   * @generated from field: repeated chatto.api.v1.CallParticipant participants = 1;
   */
  participants: CallParticipant[] = [];

  constructor(data?: PartialMessage<ListCallParticipantsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.ListCallParticipantsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "participants", kind: "message", T: CallParticipant, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListCallParticipantsResponse {
    return new ListCallParticipantsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListCallParticipantsResponse {
    return new ListCallParticipantsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListCallParticipantsResponse {
    return new ListCallParticipantsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListCallParticipantsResponse | PlainMessage<ListCallParticipantsResponse> | undefined, b: ListCallParticipantsResponse | PlainMessage<ListCallParticipantsResponse> | undefined): boolean {
    return proto3.util.equals(ListCallParticipantsResponse, a, b);
  }
}

/**
 * User currently participating in a room call.
 *
 * @generated from message chatto.api.v1.CallParticipant
 */
export class CallParticipant extends Message<CallParticipant> {
  /**
   * Participant user.
   *
   * @generated from field: chatto.api.v1.User user = 1;
   */
  user?: User;

  /**
   * When the user joined this call.
   *
   * @generated from field: google.protobuf.Timestamp joined_at = 2;
   */
  joinedAt?: Timestamp;

  /**
   * Active call session ID.
   *
   * @generated from field: string call_id = 3;
   */
  callId = "";

  constructor(data?: PartialMessage<CallParticipant>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.CallParticipant";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user", kind: "message", T: User },
    { no: 2, name: "joined_at", kind: "message", T: Timestamp },
    { no: 3, name: "call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CallParticipant {
    return new CallParticipant().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CallParticipant {
    return new CallParticipant().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CallParticipant {
    return new CallParticipant().fromJsonString(jsonString, options);
  }

  static equals(a: CallParticipant | PlainMessage<CallParticipant> | undefined, b: CallParticipant | PlainMessage<CallParticipant> | undefined): boolean {
    return proto3.util.equals(CallParticipant, a, b);
  }
}

/**
 * Request to record joining a room call.
 *
 * @generated from message chatto.api.v1.JoinCallRequest
 */
export class JoinCallRequest extends Message<JoinCallRequest> {
  /**
   * Required. Room whose call is being joined.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<JoinCallRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.JoinCallRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JoinCallRequest {
    return new JoinCallRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JoinCallRequest {
    return new JoinCallRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JoinCallRequest {
    return new JoinCallRequest().fromJsonString(jsonString, options);
  }

  static equals(a: JoinCallRequest | PlainMessage<JoinCallRequest> | undefined, b: JoinCallRequest | PlainMessage<JoinCallRequest> | undefined): boolean {
    return proto3.util.equals(JoinCallRequest, a, b);
  }
}

/**
 * Response from recording a join intent.
 *
 * @generated from message chatto.api.v1.JoinCallResponse
 */
export class JoinCallResponse extends Message<JoinCallResponse> {
  /**
   * True when a join fact was recorded.
   *
   * @generated from field: bool joined = 1;
   */
  joined = false;

  constructor(data?: PartialMessage<JoinCallResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.JoinCallResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "joined", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): JoinCallResponse {
    return new JoinCallResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): JoinCallResponse {
    return new JoinCallResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): JoinCallResponse {
    return new JoinCallResponse().fromJsonString(jsonString, options);
  }

  static equals(a: JoinCallResponse | PlainMessage<JoinCallResponse> | undefined, b: JoinCallResponse | PlainMessage<JoinCallResponse> | undefined): boolean {
    return proto3.util.equals(JoinCallResponse, a, b);
  }
}

/**
 * Request for a LiveKit token for a room call.
 *
 * @generated from message chatto.api.v1.GetCallTokenRequest
 */
export class GetCallTokenRequest extends Message<GetCallTokenRequest> {
  /**
   * Required. Room whose active call should be joined.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<GetCallTokenRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetCallTokenRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCallTokenRequest {
    return new GetCallTokenRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCallTokenRequest {
    return new GetCallTokenRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCallTokenRequest {
    return new GetCallTokenRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetCallTokenRequest | PlainMessage<GetCallTokenRequest> | undefined, b: GetCallTokenRequest | PlainMessage<GetCallTokenRequest> | undefined): boolean {
    return proto3.util.equals(GetCallTokenRequest, a, b);
  }
}

/**
 * LiveKit token details for joining a room call.
 *
 * @generated from message chatto.api.v1.GetCallTokenResponse
 */
export class GetCallTokenResponse extends Message<GetCallTokenResponse> {
  /**
   * LiveKit JWT token.
   *
   * @generated from field: string token = 1;
   */
  token = "";

  /**
   * Shared E2EE key for this active call.
   *
   * @generated from field: string e2ee_key = 2;
   */
  e2eeKey = "";

  /**
   * Active call session ID.
   *
   * @generated from field: string call_id = 3;
   */
  callId = "";

  constructor(data?: PartialMessage<GetCallTokenResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetCallTokenResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "e2ee_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCallTokenResponse {
    return new GetCallTokenResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCallTokenResponse {
    return new GetCallTokenResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCallTokenResponse {
    return new GetCallTokenResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetCallTokenResponse | PlainMessage<GetCallTokenResponse> | undefined, b: GetCallTokenResponse | PlainMessage<GetCallTokenResponse> | undefined): boolean {
    return proto3.util.equals(GetCallTokenResponse, a, b);
  }
}

/**
 * Request for a native companion publisher credential.
 *
 * @generated from message chatto.api.v1.CreateCallMediaPublisherTokenRequest
 */
export class CreateCallMediaPublisherTokenRequest extends Message<CreateCallMediaPublisherTokenRequest> {
  /**
   * Required. Room whose active call receives the media.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Kind of native media publisher being started.
   *
   * @generated from field: chatto.api.v1.CallMediaPublisherKind kind = 2;
   */
  kind = CallMediaPublisherKind.UNSPECIFIED;

  constructor(data?: PartialMessage<CreateCallMediaPublisherTokenRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.CreateCallMediaPublisherTokenRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "kind", kind: "enum", T: proto3.getEnumType(CallMediaPublisherKind) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateCallMediaPublisherTokenRequest {
    return new CreateCallMediaPublisherTokenRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateCallMediaPublisherTokenRequest {
    return new CreateCallMediaPublisherTokenRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateCallMediaPublisherTokenRequest {
    return new CreateCallMediaPublisherTokenRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateCallMediaPublisherTokenRequest | PlainMessage<CreateCallMediaPublisherTokenRequest> | undefined, b: CreateCallMediaPublisherTokenRequest | PlainMessage<CreateCallMediaPublisherTokenRequest> | undefined): boolean {
    return proto3.util.equals(CreateCallMediaPublisherTokenRequest, a, b);
  }
}

/**
 * Credential for one native companion publisher connection.
 *
 * @generated from message chatto.api.v1.CreateCallMediaPublisherTokenResponse
 */
export class CreateCallMediaPublisherTokenResponse extends Message<CreateCallMediaPublisherTokenResponse> {
  /**
   * Short-lived LiveKit JWT token.
   *
   * @generated from field: string token = 1;
   */
  token = "";

  /**
   * Shared E2EE key for this active call.
   *
   * @generated from field: string e2ee_key = 2;
   */
  e2eeKey = "";

  /**
   * Active call session ID.
   *
   * @generated from field: string call_id = 3;
   */
  callId = "";

  constructor(data?: PartialMessage<CreateCallMediaPublisherTokenResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.CreateCallMediaPublisherTokenResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "e2ee_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "call_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateCallMediaPublisherTokenResponse {
    return new CreateCallMediaPublisherTokenResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateCallMediaPublisherTokenResponse {
    return new CreateCallMediaPublisherTokenResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateCallMediaPublisherTokenResponse {
    return new CreateCallMediaPublisherTokenResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateCallMediaPublisherTokenResponse | PlainMessage<CreateCallMediaPublisherTokenResponse> | undefined, b: CreateCallMediaPublisherTokenResponse | PlainMessage<CreateCallMediaPublisherTokenResponse> | undefined): boolean {
    return proto3.util.equals(CreateCallMediaPublisherTokenResponse, a, b);
  }
}

/**
 * Request to record leaving a room call.
 *
 * @generated from message chatto.api.v1.LeaveCallRequest
 */
export class LeaveCallRequest extends Message<LeaveCallRequest> {
  /**
   * Required. Room whose call is being left.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<LeaveCallRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.LeaveCallRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LeaveCallRequest {
    return new LeaveCallRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LeaveCallRequest {
    return new LeaveCallRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LeaveCallRequest {
    return new LeaveCallRequest().fromJsonString(jsonString, options);
  }

  static equals(a: LeaveCallRequest | PlainMessage<LeaveCallRequest> | undefined, b: LeaveCallRequest | PlainMessage<LeaveCallRequest> | undefined): boolean {
    return proto3.util.equals(LeaveCallRequest, a, b);
  }
}

/**
 * Response from recording a leave intent.
 *
 * @generated from message chatto.api.v1.LeaveCallResponse
 */
export class LeaveCallResponse extends Message<LeaveCallResponse> {
  /**
   * True when a leave fact was recorded.
   *
   * @generated from field: bool left = 1;
   */
  left = false;

  constructor(data?: PartialMessage<LeaveCallResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.LeaveCallResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "left", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LeaveCallResponse {
    return new LeaveCallResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LeaveCallResponse {
    return new LeaveCallResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LeaveCallResponse {
    return new LeaveCallResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LeaveCallResponse | PlainMessage<LeaveCallResponse> | undefined, b: LeaveCallResponse | PlainMessage<LeaveCallResponse> | undefined): boolean {
    return proto3.util.equals(LeaveCallResponse, a, b);
  }
}
