// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/voice_calls.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BatchGetActiveCallsRequest, BatchGetActiveCallsResponse, CreateCallMediaPublisherTokenRequest, CreateCallMediaPublisherTokenResponse, GetActiveCallRequest, GetActiveCallResponse, GetCallTokenRequest, GetCallTokenResponse, JoinCallRequest, JoinCallResponse, LeaveCallRequest, LeaveCallResponse, ListActiveCallsRequest, ListActiveCallsResponse, ListCallParticipantsRequest, ListCallParticipantsResponse } from "./voice_calls_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Voice-call request/response APIs backed by Chatto call-state projections.
 *
 * @generated from service chatto.api.v1.VoiceCallService
 */
export const VoiceCallService = {
  typeName: "chatto.api.v1.VoiceCallService",
  methods: {
    /**
     * Lists member rooms that currently have active calls as a finite
     * runtime snapshot. Rooms the caller is not a member of are omitted.
     *
     * Returns an empty list when LiveKit is not configured.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.ListActiveCalls
     */
    listActiveCalls: {
      name: "ListActiveCalls",
      I: ListActiveCallsRequest,
      O: ListActiveCallsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets the current active call snapshot for one room.
     *
     * The caller must be a member of the room. Returns NOT_FOUND when the room
     * does not exist, currently has no active call, or voice calls are not
     * configured. The returned call_id lets clients ignore stale realtime call
     * events from previous calls in the same room.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.GetActiveCall
     */
    getActiveCall: {
      name: "GetActiveCall",
      I: GetActiveCallRequest,
      O: GetActiveCallResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets current active call snapshots for many rooms.
     *
     * Rooms that do not exist, are inaccessible, or currently have no active call
     * are omitted. Results preserve first-seen request order and repeated room
     * IDs are de-duplicated. Returns an empty list when LiveKit is not configured.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.BatchGetActiveCalls
     */
    batchGetActiveCalls: {
      name: "BatchGetActiveCalls",
      I: BatchGetActiveCallsRequest,
      O: BatchGetActiveCallsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists participants currently observed in a room's active call as a finite
     * runtime snapshot.
     *
     * The caller must be a member of the room.
     * Returns NOT_FOUND when the room does not exist and PERMISSION_DENIED when
     * the caller is not a room member.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.ListCallParticipants
     */
    listCallParticipants: {
      name: "ListCallParticipants",
      I: ListCallParticipantsRequest,
      O: ListCallParticipantsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Records the caller's intent to join a room call.
     *
     * Returns joined=false when LiveKit is not configured.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.JoinCall
     */
    joinCall: {
      name: "JoinCall",
      I: JoinCallRequest,
      O: JoinCallResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Issues a LiveKit token for joining the room's active call.
     *
     * The caller must be a member of the room and a call must already be active.
     * Returns NOT_FOUND when the room does not exist, PERMISSION_DENIED when the
     * caller is not a room member, and FAILED_PRECONDITION when no call is active
     * or voice and video calls are not configured.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.GetCallToken
     */
    getCallToken: {
      name: "GetCallToken",
      I: GetCallTokenRequest,
      O: GetCallTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Issues a short-lived LiveKit token for a native companion publisher owned
     * by the caller. Companion publishers contribute media to the caller's
     * logical participant without becoming call participants themselves.
     *
     * The caller must already participate in the active call. Returns
     * FAILED_PRECONDITION when no call is active, the caller has not joined it,
     * or voice and video calls are not configured.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.CreateCallMediaPublisherToken
     */
    createCallMediaPublisherToken: {
      name: "CreateCallMediaPublisherToken",
      I: CreateCallMediaPublisherTokenRequest,
      O: CreateCallMediaPublisherTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Records the caller's intent to leave a room call.
     *
     * Returns left=false when LiveKit is not configured.
     *
     * @generated from rpc chatto.api.v1.VoiceCallService.LeaveCall
     */
    leaveCall: {
      name: "LeaveCall",
      I: LeaveCallRequest,
      O: LeaveCallResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
