// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/admin/v1/diagnostics.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetSystemInfoRequest, GetSystemInfoResponse } from "./diagnostics_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Provides server diagnostics for the admin system page.
 *
 * @generated from service chatto.admin.v1.AdminDiagnosticsService
 */
export const AdminDiagnosticsService = {
  typeName: "chatto.admin.v1.AdminDiagnosticsService",
  methods: {
    /**
     * Returns broker, JetStream, and projection diagnostics. Requires the
     * server owner role.
     *
     * @generated from rpc chatto.admin.v1.AdminDiagnosticsService.GetSystemInfo
     */
    getSystemInfo: {
      name: "GetSystemInfo",
      I: GetSystemInfoRequest,
      O: GetSystemInfoResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
