// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/admin/v1/diagnostics.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * Operator-facing state derived from a durable consumer.
 *
 * @generated from enum chatto.admin.v1.AdminDurableWorkerHealth
 */
export enum AdminDurableWorkerHealth {
  /**
   * @generated from enum value: ADMIN_DURABLE_WORKER_HEALTH_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * This optional worker is not required by current server configuration.
   *
   * @generated from enum value: ADMIN_DURABLE_WORKER_HEALTH_INACTIVE = 1;
   */
  INACTIVE = 1,

  /**
   * A worker is waiting and all known work is acknowledged.
   *
   * @generated from enum value: ADMIN_DURABLE_WORKER_HEALTH_HEALTHY = 2;
   */
  HEALTHY = 2,

  /**
   * A worker is available and unacknowledged work remains.
   *
   * @generated from enum value: ADMIN_DURABLE_WORKER_HEALTH_WORKING = 3;
   */
  WORKING = 3,

  /**
   * An acknowledgement is pending, but broker state cannot prove whether a
   * handler is active or the delivery is awaiting recovery after a crash.
   *
   * @generated from enum value: ADMIN_DURABLE_WORKER_HEALTH_UNCONFIRMED = 4;
   */
  UNCONFIRMED = 4,

  /**
   * The consumer exists but has neither a waiting pull nor an ack-pending delivery.
   *
   * @generated from enum value: ADMIN_DURABLE_WORKER_HEALTH_STALLED = 5;
   */
  STALLED = 5,

  /**
   * The required consumer is unavailable.
   *
   * @generated from enum value: ADMIN_DURABLE_WORKER_HEALTH_UNAVAILABLE = 6;
   */
  UNAVAILABLE = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(AdminDurableWorkerHealth)
proto3.util.setEnumType(AdminDurableWorkerHealth, "chatto.admin.v1.AdminDurableWorkerHealth", [
  { no: 0, name: "ADMIN_DURABLE_WORKER_HEALTH_UNSPECIFIED" },
  { no: 1, name: "ADMIN_DURABLE_WORKER_HEALTH_INACTIVE" },
  { no: 2, name: "ADMIN_DURABLE_WORKER_HEALTH_HEALTHY" },
  { no: 3, name: "ADMIN_DURABLE_WORKER_HEALTH_WORKING" },
  { no: 4, name: "ADMIN_DURABLE_WORKER_HEALTH_UNCONFIRMED" },
  { no: 5, name: "ADMIN_DURABLE_WORKER_HEALTH_STALLED" },
  { no: 6, name: "ADMIN_DURABLE_WORKER_HEALTH_UNAVAILABLE" },
]);

/**
 * Operator-facing state for the shared durable asset cleanup queue.
 *
 * @generated from enum chatto.admin.v1.AdminAssetCleanupHealth
 */
export enum AdminAssetCleanupHealth {
  /**
   * @generated from enum value: ADMIN_ASSET_CLEANUP_HEALTH_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ADMIN_ASSET_CLEANUP_HEALTH_INACTIVE = 1;
   */
  INACTIVE = 1,

  /**
   * @generated from enum value: ADMIN_ASSET_CLEANUP_HEALTH_INITIALIZING = 2;
   */
  INITIALIZING = 2,

  /**
   * @generated from enum value: ADMIN_ASSET_CLEANUP_HEALTH_HEALTHY = 3;
   */
  HEALTHY = 3,

  /**
   * @generated from enum value: ADMIN_ASSET_CLEANUP_HEALTH_RETRYING = 4;
   */
  RETRYING = 4,

  /**
   * @generated from enum value: ADMIN_ASSET_CLEANUP_HEALTH_STALLED = 5;
   */
  STALLED = 5,

  /**
   * Cleanup diagnostics could not be read; other system diagnostics remain valid.
   *
   * @generated from enum value: ADMIN_ASSET_CLEANUP_HEALTH_UNAVAILABLE = 6;
   */
  UNAVAILABLE = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(AdminAssetCleanupHealth)
proto3.util.setEnumType(AdminAssetCleanupHealth, "chatto.admin.v1.AdminAssetCleanupHealth", [
  { no: 0, name: "ADMIN_ASSET_CLEANUP_HEALTH_UNSPECIFIED" },
  { no: 1, name: "ADMIN_ASSET_CLEANUP_HEALTH_INACTIVE" },
  { no: 2, name: "ADMIN_ASSET_CLEANUP_HEALTH_INITIALIZING" },
  { no: 3, name: "ADMIN_ASSET_CLEANUP_HEALTH_HEALTHY" },
  { no: 4, name: "ADMIN_ASSET_CLEANUP_HEALTH_RETRYING" },
  { no: 5, name: "ADMIN_ASSET_CLEANUP_HEALTH_STALLED" },
  { no: 6, name: "ADMIN_ASSET_CLEANUP_HEALTH_UNAVAILABLE" },
]);

/**
 * Request to read owner-only server diagnostics.
 *
 * @generated from message chatto.admin.v1.GetSystemInfoRequest
 */
export class GetSystemInfoRequest extends Message<GetSystemInfoRequest> {
  constructor(data?: PartialMessage<GetSystemInfoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetSystemInfoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSystemInfoRequest {
    return new GetSystemInfoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSystemInfoRequest {
    return new GetSystemInfoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSystemInfoRequest {
    return new GetSystemInfoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSystemInfoRequest | PlainMessage<GetSystemInfoRequest> | undefined, b: GetSystemInfoRequest | PlainMessage<GetSystemInfoRequest> | undefined): boolean {
    return proto3.util.equals(GetSystemInfoRequest, a, b);
  }
}

/**
 * Owner-only operational diagnostics for the Chatto server.
 *
 * @generated from message chatto.admin.v1.GetSystemInfoResponse
 */
export class GetSystemInfoResponse extends Message<GetSystemInfoResponse> {
  /**
   * Broker connection, account, and JetStream state.
   *
   * @generated from field: chatto.admin.v1.AdminSystemInfo system_info = 1;
   */
  systemInfo?: AdminSystemInfo;

  /**
   * Event-sourced projection health and memory estimates.
   *
   * @generated from field: repeated chatto.admin.v1.AdminProjectionState projections = 2;
   */
  projections: AdminProjectionState[] = [];

  /**
   * Recoverable physical deletion worker health.
   *
   * @generated from field: chatto.admin.v1.AdminAssetCleanupStatus asset_cleanup = 3;
   */
  assetCleanup?: AdminAssetCleanupStatus;

  /**
   * Known durable worker queues and their current broker-derived health.
   *
   * @generated from field: repeated chatto.admin.v1.AdminDurableWorkerStatus durable_workers = 4;
   */
  durableWorkers: AdminDurableWorkerStatus[] = [];

  /**
   * Whether projection diagnostics were collected successfully.
   *
   * @generated from field: optional bool projections_available = 5;
   */
  projectionsAvailable?: boolean;

  constructor(data?: PartialMessage<GetSystemInfoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetSystemInfoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "system_info", kind: "message", T: AdminSystemInfo },
    { no: 2, name: "projections", kind: "message", T: AdminProjectionState, repeated: true },
    { no: 3, name: "asset_cleanup", kind: "message", T: AdminAssetCleanupStatus },
    { no: 4, name: "durable_workers", kind: "message", T: AdminDurableWorkerStatus, repeated: true },
    { no: 5, name: "projections_available", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSystemInfoResponse {
    return new GetSystemInfoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSystemInfoResponse {
    return new GetSystemInfoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSystemInfoResponse {
    return new GetSystemInfoResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetSystemInfoResponse | PlainMessage<GetSystemInfoResponse> | undefined, b: GetSystemInfoResponse | PlainMessage<GetSystemInfoResponse> | undefined): boolean {
    return proto3.util.equals(GetSystemInfoResponse, a, b);
  }
}

/**
 * Broker-derived health for one known durable worker queue.
 *
 * @generated from message chatto.admin.v1.AdminDurableWorkerStatus
 */
export class AdminDurableWorkerStatus extends Message<AdminDurableWorkerStatus> {
  /**
   * Stable machine-readable worker key.
   *
   * @generated from field: string key = 1;
   */
  key = "";

  /**
   * Current availability and work state.
   *
   * @generated from field: chatto.admin.v1.AdminDurableWorkerHealth health = 2;
   */
  health = AdminDurableWorkerHealth.UNSPECIFIED;

  /**
   * Deliveries not yet handed to a handler.
   *
   * @generated from field: string pending_count = 3;
   */
  pendingCount = "";

  /**
   * Deliveries awaiting acknowledgement; this does not prove handler liveness.
   *
   * @generated from field: string ack_pending_count = 4;
   */
  ackPendingCount = "";

  /**
   * Pull requests currently waiting for work.
   *
   * @generated from field: string waiting_count = 5;
   */
  waitingCount = "";

  /**
   * Redelivered messages that remain unacknowledged.
   *
   * @generated from field: string redelivered_count = 6;
   */
  redeliveredCount = "";

  /**
   * Latest EVT stream sequence delivered to this queue.
   *
   * @generated from field: string last_delivered_sequence = 7;
   */
  lastDeliveredSequence = "";

  /**
   * Highest contiguous EVT stream sequence acknowledged by this queue.
   *
   * @generated from field: string ack_floor_sequence = 8;
   */
  ackFloorSequence = "";

  constructor(data?: PartialMessage<AdminDurableWorkerStatus>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminDurableWorkerStatus";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "health", kind: "enum", T: proto3.getEnumType(AdminDurableWorkerHealth) },
    { no: 3, name: "pending_count", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "ack_pending_count", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "waiting_count", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "redelivered_count", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "last_delivered_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "ack_floor_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminDurableWorkerStatus {
    return new AdminDurableWorkerStatus().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminDurableWorkerStatus {
    return new AdminDurableWorkerStatus().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminDurableWorkerStatus {
    return new AdminDurableWorkerStatus().fromJsonString(jsonString, options);
  }

  static equals(a: AdminDurableWorkerStatus | PlainMessage<AdminDurableWorkerStatus> | undefined, b: AdminDurableWorkerStatus | PlainMessage<AdminDurableWorkerStatus> | undefined): boolean {
    return proto3.util.equals(AdminDurableWorkerStatus, a, b);
  }
}

/**
 * Current health of recoverable message-owned asset deletion.
 *
 * @generated from message chatto.admin.v1.AdminAssetCleanupStatus
 */
export class AdminAssetCleanupStatus extends Message<AdminAssetCleanupStatus> {
  /**
   * Operator-facing state derived from the shared durable consumer.
   *
   * @generated from field: chatto.admin.v1.AdminAssetCleanupHealth health = 1;
   */
  health = AdminAssetCleanupHealth.UNSPECIFIED;

  /**
   * Deletion effects currently waiting for a successful retry.
   *
   * @generated from field: int64 pending_count = 2;
   */
  pendingCount = protoInt64.zero;

  /**
   * Deprecated. Shared durable consumers do not expose this value.
   *
   * @generated from field: google.protobuf.Timestamp oldest_pending_at = 3 [deprecated = true];
   * @deprecated
   */
  oldestPendingAt?: Timestamp;

  /**
   * Deprecated. Shared durable consumers run continuously rather than in passes.
   *
   * @generated from field: bool pass_in_progress = 4 [deprecated = true];
   * @deprecated
   */
  passInProgress = false;

  /**
   * Deprecated. Shared durable consumers run continuously rather than in passes.
   *
   * @generated from field: google.protobuf.Timestamp last_pass_at = 5 [deprecated = true];
   * @deprecated
   */
  lastPassAt?: Timestamp;

  /**
   * Deprecated. Shared durable consumers run continuously rather than in passes.
   *
   * @generated from field: google.protobuf.Timestamp last_successful_pass_at = 6 [deprecated = true];
   * @deprecated
   */
  lastSuccessfulPassAt?: Timestamp;

  /**
   * Deprecated. Shared durable consumers do not publish a liveness heartbeat.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 7 [deprecated = true];
   * @deprecated
   */
  updatedAt?: Timestamp;

  /**
   * Deprecated. Use health and pending_count instead.
   *
   * @generated from field: bool last_pass_failed = 8 [deprecated = true];
   * @deprecated
   */
  lastPassFailed = false;

  /**
   * Global EVT sequence of the most recently delivered deletion fact.
   *
   * @generated from field: string last_inspected_sequence = 9;
   */
  lastInspectedSequence = "";

  /**
   * Current latest global EVT sequence matching asset deletion facts.
   *
   * @generated from field: string latest_deletion_sequence = 10;
   */
  latestDeletionSequence = "";

  constructor(data?: PartialMessage<AdminAssetCleanupStatus>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminAssetCleanupStatus";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "health", kind: "enum", T: proto3.getEnumType(AdminAssetCleanupHealth) },
    { no: 2, name: "pending_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "oldest_pending_at", kind: "message", T: Timestamp },
    { no: 4, name: "pass_in_progress", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "last_pass_at", kind: "message", T: Timestamp },
    { no: 6, name: "last_successful_pass_at", kind: "message", T: Timestamp },
    { no: 7, name: "updated_at", kind: "message", T: Timestamp },
    { no: 8, name: "last_pass_failed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "last_inspected_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "latest_deletion_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminAssetCleanupStatus {
    return new AdminAssetCleanupStatus().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminAssetCleanupStatus {
    return new AdminAssetCleanupStatus().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminAssetCleanupStatus {
    return new AdminAssetCleanupStatus().fromJsonString(jsonString, options);
  }

  static equals(a: AdminAssetCleanupStatus | PlainMessage<AdminAssetCleanupStatus> | undefined, b: AdminAssetCleanupStatus | PlainMessage<AdminAssetCleanupStatus> | undefined): boolean {
    return proto3.util.equals(AdminAssetCleanupStatus, a, b);
  }
}

/**
 * Broker and application diagnostics shown on the server admin system page.
 *
 * @generated from message chatto.admin.v1.AdminSystemInfo
 */
export class AdminSystemInfo extends Message<AdminSystemInfo> {
  /**
   * Current NATS server connection metadata.
   *
   * @generated from field: chatto.admin.v1.AdminConnectionInfo connection = 1;
   */
  connection?: AdminConnectionInfo;

  /**
   * JetStream account limits and usage.
   *
   * @generated from field: chatto.admin.v1.AdminAccountInfo account = 2;
   */
  account?: AdminAccountInfo;

  /**
   * JetStream stream and consumer diagnostics.
   *
   * @generated from field: chatto.admin.v1.AdminNatsStats nats = 3;
   */
  nats?: AdminNatsStats;

  /**
   * Aggregate Chatto object counts.
   *
   * @generated from field: chatto.admin.v1.AdminServerStats stats = 4;
   */
  stats?: AdminServerStats;

  constructor(data?: PartialMessage<AdminSystemInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminSystemInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "connection", kind: "message", T: AdminConnectionInfo },
    { no: 2, name: "account", kind: "message", T: AdminAccountInfo },
    { no: 3, name: "nats", kind: "message", T: AdminNatsStats },
    { no: 4, name: "stats", kind: "message", T: AdminServerStats },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminSystemInfo {
    return new AdminSystemInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminSystemInfo {
    return new AdminSystemInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminSystemInfo {
    return new AdminSystemInfo().fromJsonString(jsonString, options);
  }

  static equals(a: AdminSystemInfo | PlainMessage<AdminSystemInfo> | undefined, b: AdminSystemInfo | PlainMessage<AdminSystemInfo> | undefined): boolean {
    return proto3.util.equals(AdminSystemInfo, a, b);
  }
}

/**
 * Current NATS server connection metadata.
 *
 * @generated from message chatto.admin.v1.AdminConnectionInfo
 */
export class AdminConnectionInfo extends Message<AdminConnectionInfo> {
  /**
   * Whether Chatto is currently connected to NATS.
   *
   * @generated from field: bool connected = 1;
   */
  connected = false;

  /**
   * Connected NATS server ID.
   *
   * @generated from field: string server_id = 2;
   */
  serverId = "";

  /**
   * Connected NATS server name.
   *
   * @generated from field: string server_name = 3;
   */
  serverName = "";

  /**
   * Connected NATS server version.
   *
   * @generated from field: string version = 4;
   */
  version = "";

  /**
   * Maximum payload accepted by the connected NATS server.
   *
   * @generated from field: int64 max_payload = 5;
   */
  maxPayload = protoInt64.zero;

  /**
   * Round-trip latency to the connected NATS server.
   *
   * @generated from field: string rtt = 6;
   */
  rtt = "";

  constructor(data?: PartialMessage<AdminConnectionInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminConnectionInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "connected", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "server_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "server_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "max_payload", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "rtt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminConnectionInfo {
    return new AdminConnectionInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminConnectionInfo {
    return new AdminConnectionInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminConnectionInfo {
    return new AdminConnectionInfo().fromJsonString(jsonString, options);
  }

  static equals(a: AdminConnectionInfo | PlainMessage<AdminConnectionInfo> | undefined, b: AdminConnectionInfo | PlainMessage<AdminConnectionInfo> | undefined): boolean {
    return proto3.util.equals(AdminConnectionInfo, a, b);
  }
}

/**
 * JetStream account limits and usage.
 *
 * @generated from message chatto.admin.v1.AdminAccountInfo
 */
export class AdminAccountInfo extends Message<AdminAccountInfo> {
  /**
   * Maximum memory storage in bytes. Values less than or equal to zero mean unlimited.
   *
   * @generated from field: int64 memory = 1;
   */
  memory = protoInt64.zero;

  /**
   * Used memory storage in bytes.
   *
   * @generated from field: int64 memory_used = 2;
   */
  memoryUsed = protoInt64.zero;

  /**
   * Maximum file storage in bytes. Values less than or equal to zero mean unlimited.
   *
   * @generated from field: int64 storage = 3;
   */
  storage = protoInt64.zero;

  /**
   * Used file storage in bytes.
   *
   * @generated from field: int64 storage_used = 4;
   */
  storageUsed = protoInt64.zero;

  /**
   * Maximum number of streams. Values less than or equal to zero mean unlimited.
   *
   * @generated from field: int32 streams = 5;
   */
  streams = 0;

  /**
   * Current number of streams.
   *
   * @generated from field: int32 streams_used = 6;
   */
  streamsUsed = 0;

  /**
   * Maximum number of consumers. Values less than or equal to zero mean unlimited.
   *
   * @generated from field: int32 consumers = 7;
   */
  consumers = 0;

  /**
   * Current number of consumers.
   *
   * @generated from field: int32 consumers_used = 8;
   */
  consumersUsed = 0;

  constructor(data?: PartialMessage<AdminAccountInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminAccountInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "memory", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "memory_used", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "storage", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "storage_used", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "streams", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "streams_used", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "consumers", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "consumers_used", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminAccountInfo {
    return new AdminAccountInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminAccountInfo {
    return new AdminAccountInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminAccountInfo {
    return new AdminAccountInfo().fromJsonString(jsonString, options);
  }

  static equals(a: AdminAccountInfo | PlainMessage<AdminAccountInfo> | undefined, b: AdminAccountInfo | PlainMessage<AdminAccountInfo> | undefined): boolean {
    return proto3.util.equals(AdminAccountInfo, a, b);
  }
}

/**
 * Aggregate Chatto object counts.
 *
 * @generated from message chatto.admin.v1.AdminServerStats
 */
export class AdminServerStats extends Message<AdminServerStats> {
  /**
   * Registered user count.
   *
   * @generated from field: int32 user_count = 1;
   */
  userCount = 0;

  /**
   * Channel room count.
   *
   * @generated from field: int32 channel_room_count = 2;
   */
  channelRoomCount = 0;

  /**
   * Direct-message room count.
   *
   * @generated from field: int32 dm_room_count = 3;
   */
  dmRoomCount = 0;

  constructor(data?: PartialMessage<AdminServerStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminServerStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "channel_room_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "dm_room_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminServerStats {
    return new AdminServerStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminServerStats {
    return new AdminServerStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminServerStats {
    return new AdminServerStats().fromJsonString(jsonString, options);
  }

  static equals(a: AdminServerStats | PlainMessage<AdminServerStats> | undefined, b: AdminServerStats | PlainMessage<AdminServerStats> | undefined): boolean {
    return proto3.util.equals(AdminServerStats, a, b);
  }
}

/**
 * JetStream stream and consumer diagnostics.
 *
 * @generated from message chatto.admin.v1.AdminNatsStats
 */
export class AdminNatsStats extends Message<AdminNatsStats> {
  /**
   * Total messages stored across all streams.
   *
   * @generated from field: int64 total_messages = 1;
   */
  totalMessages = protoInt64.zero;

  /**
   * Total bytes stored across all streams.
   *
   * @generated from field: int64 total_bytes = 2;
   */
  totalBytes = protoInt64.zero;

  /**
   * Total pending messages across all consumers.
   *
   * @generated from field: int64 total_consumer_pending = 3;
   */
  totalConsumerPending = protoInt64.zero;

  /**
   * Total messages currently waiting for acknowledgement.
   *
   * @generated from field: int32 total_ack_pending = 4;
   */
  totalAckPending = 0;

  /**
   * Streams sorted by name.
   *
   * @generated from field: repeated chatto.admin.v1.AdminNatsStreamInfo streams = 5;
   */
  streams: AdminNatsStreamInfo[] = [];

  /**
   * Consumers sorted by stream and name.
   *
   * @generated from field: repeated chatto.admin.v1.AdminNatsConsumerInfo consumers = 6;
   */
  consumers: AdminNatsConsumerInfo[] = [];

  constructor(data?: PartialMessage<AdminNatsStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminNatsStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "total_messages", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "total_bytes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "total_consumer_pending", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "total_ack_pending", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "streams", kind: "message", T: AdminNatsStreamInfo, repeated: true },
    { no: 6, name: "consumers", kind: "message", T: AdminNatsConsumerInfo, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminNatsStats {
    return new AdminNatsStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminNatsStats {
    return new AdminNatsStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminNatsStats {
    return new AdminNatsStats().fromJsonString(jsonString, options);
  }

  static equals(a: AdminNatsStats | PlainMessage<AdminNatsStats> | undefined, b: AdminNatsStats | PlainMessage<AdminNatsStats> | undefined): boolean {
    return proto3.util.equals(AdminNatsStats, a, b);
  }
}

/**
 * JetStream stream state.
 *
 * @generated from message chatto.admin.v1.AdminNatsStreamInfo
 */
export class AdminNatsStreamInfo extends Message<AdminNatsStreamInfo> {
  /**
   * Stream name.
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Stream description.
   *
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * Subjects stored in the stream.
   *
   * @generated from field: repeated string subjects = 3;
   */
  subjects: string[] = [];

  /**
   * Storage backend name.
   *
   * @generated from field: string storage = 4;
   */
  storage = "";

  /**
   * Number of messages in the stream.
   *
   * @generated from field: int64 messages = 5;
   */
  messages = protoInt64.zero;

  /**
   * Number of bytes in the stream.
   *
   * @generated from field: int64 bytes = 6;
   */
  bytes = protoInt64.zero;

  /**
   * First stream sequence.
   *
   * @generated from field: string first_sequence = 7;
   */
  firstSequence = "";

  /**
   * Last stream sequence.
   *
   * @generated from field: string last_sequence = 8;
   */
  lastSequence = "";

  /**
   * Number of stream consumers.
   *
   * @generated from field: int32 consumer_count = 9;
   */
  consumerCount = 0;

  /**
   * Configured stream replica count.
   *
   * @generated from field: int32 replicas = 10;
   */
  replicas = 0;

  /**
   * Current cluster leader, when reported by NATS.
   *
   * @generated from field: string cluster_leader = 11;
   */
  clusterLeader = "";

  constructor(data?: PartialMessage<AdminNatsStreamInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminNatsStreamInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "subjects", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "storage", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "messages", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "bytes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "first_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "last_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "consumer_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "replicas", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "cluster_leader", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminNatsStreamInfo {
    return new AdminNatsStreamInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminNatsStreamInfo {
    return new AdminNatsStreamInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminNatsStreamInfo {
    return new AdminNatsStreamInfo().fromJsonString(jsonString, options);
  }

  static equals(a: AdminNatsStreamInfo | PlainMessage<AdminNatsStreamInfo> | undefined, b: AdminNatsStreamInfo | PlainMessage<AdminNatsStreamInfo> | undefined): boolean {
    return proto3.util.equals(AdminNatsStreamInfo, a, b);
  }
}

/**
 * JetStream consumer state.
 *
 * @generated from message chatto.admin.v1.AdminNatsConsumerInfo
 */
export class AdminNatsConsumerInfo extends Message<AdminNatsConsumerInfo> {
  /**
   * Stream that owns the consumer.
   *
   * @generated from field: string stream = 1;
   */
  stream = "";

  /**
   * Consumer name.
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * Durable name, when the consumer is durable.
   *
   * @generated from field: string durable = 3;
   */
  durable = "";

  /**
   * Single filter subject, when configured.
   *
   * @generated from field: string filter_subject = 4;
   */
  filterSubject = "";

  /**
   * Multiple filter subjects, when configured.
   *
   * @generated from field: repeated string filter_subjects = 5;
   */
  filterSubjects: string[] = [];

  /**
   * NATS acknowledgement policy.
   *
   * @generated from field: string ack_policy = 6;
   */
  ackPolicy = "";

  /**
   * Whether this is a pull consumer.
   *
   * @generated from field: bool pull_based = 7;
   */
  pullBased = false;

  /**
   * Whether this push consumer has an active subscription.
   *
   * @generated from field: bool push_bound = 8;
   */
  pushBound = false;

  /**
   * Pending messages for this consumer.
   *
   * @generated from field: int64 pending = 9;
   */
  pending = protoInt64.zero;

  /**
   * Messages waiting for acknowledgement.
   *
   * @generated from field: int32 ack_pending = 10;
   */
  ackPending = 0;

  /**
   * Redelivered message count.
   *
   * @generated from field: int32 redelivered = 11;
   */
  redelivered = 0;

  /**
   * Pull requests waiting for messages.
   *
   * @generated from field: int32 waiting = 12;
   */
  waiting = 0;

  /**
   * Delivered consumer sequence.
   *
   * @generated from field: string delivered_consumer_sequence = 13;
   */
  deliveredConsumerSequence = "";

  /**
   * Delivered stream sequence.
   *
   * @generated from field: string delivered_stream_sequence = 14;
   */
  deliveredStreamSequence = "";

  /**
   * Acknowledgement floor consumer sequence.
   *
   * @generated from field: string ack_floor_consumer_sequence = 15;
   */
  ackFloorConsumerSequence = "";

  /**
   * Acknowledgement floor stream sequence.
   *
   * @generated from field: string ack_floor_stream_sequence = 16;
   */
  ackFloorStreamSequence = "";

  constructor(data?: PartialMessage<AdminNatsConsumerInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminNatsConsumerInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "stream", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "durable", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "filter_subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "filter_subjects", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "ack_policy", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "pull_based", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "push_bound", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "pending", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "ack_pending", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "redelivered", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "waiting", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 13, name: "delivered_consumer_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "delivered_stream_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "ack_floor_consumer_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "ack_floor_stream_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminNatsConsumerInfo {
    return new AdminNatsConsumerInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminNatsConsumerInfo {
    return new AdminNatsConsumerInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminNatsConsumerInfo {
    return new AdminNatsConsumerInfo().fromJsonString(jsonString, options);
  }

  static equals(a: AdminNatsConsumerInfo | PlainMessage<AdminNatsConsumerInfo> | undefined, b: AdminNatsConsumerInfo | PlainMessage<AdminNatsConsumerInfo> | undefined): boolean {
    return proto3.util.equals(AdminNatsConsumerInfo, a, b);
  }
}

/**
 * Event-sourced projection health and memory estimates.
 *
 * @generated from message chatto.admin.v1.AdminProjectionState
 */
export class AdminProjectionState extends Message<AdminProjectionState> {
  /**
   * Stable projection key.
   *
   * @generated from field: string key = 1;
   */
  key = "";

  /**
   * Display name.
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * EVT subjects consumed by this projection.
   *
   * @generated from field: repeated string subjects = 3;
   */
  subjects: string[] = [];

  /**
   * Whether the projection projector is running.
   *
   * @generated from field: bool started = 4;
   */
  started = false;

  /**
   * Startup duration in seconds, set after startup completes.
   *
   * @generated from field: optional double startup_duration_seconds = 5;
   */
  startupDurationSeconds?: number;

  /**
   * Last event sequence applied by the projection.
   *
   * @generated from field: string last_applied_sequence = 6;
   */
  lastAppliedSequence = "";

  /**
   * Target sequence among the projection's matching subjects.
   *
   * @generated from field: string matching_stream_sequence = 7;
   */
  matchingStreamSequence = "";

  /**
   * Current last sequence of the EVT stream.
   *
   * @generated from field: string stream_last_sequence = 8;
   */
  streamLastSequence = "";

  /**
   * Matching-subject lag between target and applied sequence.
   *
   * @generated from field: int64 lag = 9;
   */
  lag = protoInt64.zero;

  /**
   * Whether the projection failed.
   *
   * @generated from field: bool failed = 10;
   */
  failed = false;

  /**
   * Sequence that failed, when failed is true.
   *
   * @generated from field: string failed_sequence = 11;
   */
  failedSequence = "";

  /**
   * Failure message, when failed is true.
   *
   * @generated from field: string failure = 12;
   */
  failure = "";

  /**
   * Estimated number of entries held by the projection.
   *
   * @generated from field: int64 entry_count = 13;
   */
  entryCount = protoInt64.zero;

  /**
   * Estimated memory used by the projection in bytes.
   *
   * @generated from field: int64 estimated_bytes = 14;
   */
  estimatedBytes = protoInt64.zero;

  /**
   * Estimated average memory per entry in bytes.
   *
   * @generated from field: int64 average_entry_bytes = 15;
   */
  averageEntryBytes = protoInt64.zero;

  /**
   * Projection-specific diagnostic metrics.
   *
   * @generated from field: repeated chatto.admin.v1.AdminProjectionMetric metrics = 16;
   */
  metrics: AdminProjectionMetric[] = [];

  constructor(data?: PartialMessage<AdminProjectionState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminProjectionState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "subjects", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "started", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "startup_duration_seconds", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 6, name: "last_applied_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "matching_stream_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "stream_last_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "lag", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "failed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 11, name: "failed_sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "failure", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "entry_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 14, name: "estimated_bytes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 15, name: "average_entry_bytes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 16, name: "metrics", kind: "message", T: AdminProjectionMetric, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminProjectionState {
    return new AdminProjectionState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminProjectionState {
    return new AdminProjectionState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminProjectionState {
    return new AdminProjectionState().fromJsonString(jsonString, options);
  }

  static equals(a: AdminProjectionState | PlainMessage<AdminProjectionState> | undefined, b: AdminProjectionState | PlainMessage<AdminProjectionState> | undefined): boolean {
    return proto3.util.equals(AdminProjectionState, a, b);
  }
}

/**
 * Projection-specific diagnostic metric.
 *
 * @generated from message chatto.admin.v1.AdminProjectionMetric
 */
export class AdminProjectionMetric extends Message<AdminProjectionMetric> {
  /**
   * Metric name.
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Metric value.
   *
   * @generated from field: int64 value = 2;
   */
  value = protoInt64.zero;

  /**
   * Estimated memory represented by this metric in bytes.
   *
   * @generated from field: int64 bytes = 3;
   */
  bytes = protoInt64.zero;

  constructor(data?: PartialMessage<AdminProjectionMetric>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminProjectionMetric";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "bytes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminProjectionMetric {
    return new AdminProjectionMetric().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminProjectionMetric {
    return new AdminProjectionMetric().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminProjectionMetric {
    return new AdminProjectionMetric().fromJsonString(jsonString, options);
  }

  static equals(a: AdminProjectionMetric | PlainMessage<AdminProjectionMetric> | undefined, b: AdminProjectionMetric | PlainMessage<AdminProjectionMetric> | undefined): boolean {
    return proto3.util.equals(AdminProjectionMetric, a, b);
  }
}
