// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/admin/v1/event_log.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * Filter for owner/auditor event-log inspection.
 *
 * @generated from message chatto.admin.v1.AdminEventLogFilter
 */
export class AdminEventLogFilter extends Message<AdminEventLogFilter> {
  /**
   * Event oneof payload type, such as MessagePostedEvent.
   *
   * @generated from field: string event_type = 1;
   */
  eventType = "";

  /**
   * Actor user ID.
   *
   * @generated from field: string actor_id = 2;
   */
  actorId = "";

  /**
   * Inclusive lower creation timestamp bound.
   *
   * @generated from field: google.protobuf.Timestamp created_at_from = 3;
   */
  createdAtFrom?: Timestamp;

  /**
   * Inclusive upper creation timestamp bound.
   *
   * @generated from field: google.protobuf.Timestamp created_at_to = 4;
   */
  createdAtTo?: Timestamp;

  constructor(data?: PartialMessage<AdminEventLogFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminEventLogFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created_at_from", kind: "message", T: Timestamp },
    { no: 4, name: "created_at_to", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminEventLogFilter {
    return new AdminEventLogFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminEventLogFilter {
    return new AdminEventLogFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminEventLogFilter {
    return new AdminEventLogFilter().fromJsonString(jsonString, options);
  }

  static equals(a: AdminEventLogFilter | PlainMessage<AdminEventLogFilter> | undefined, b: AdminEventLogFilter | PlainMessage<AdminEventLogFilter> | undefined): boolean {
    return proto3.util.equals(AdminEventLogFilter, a, b);
  }
}

/**
 * Request to list durable EVT entries newest-first.
 *
 * @generated from message chatto.admin.v1.ListEventsRequest
 */
export class ListEventsRequest extends Message<ListEventsRequest> {
  /**
   * Maximum entries to return. The server clamps this to its diagnostic limit.
   *
   * @generated from field: int32 limit = 1;
   */
  limit = 0;

  /**
   * Exclusive sequence cursor. Returned entries are older than this sequence.
   *
   * @generated from field: optional string before = 2;
   */
  before?: string;

  /**
   * Optional filter. Filtered scans inspect a bounded window per request.
   *
   * @generated from field: chatto.admin.v1.AdminEventLogFilter filter = 3;
   */
  filter?: AdminEventLogFilter;

  constructor(data?: PartialMessage<ListEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "before", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "filter", kind: "message", T: AdminEventLogFilter },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventsRequest | PlainMessage<ListEventsRequest> | undefined, b: ListEventsRequest | PlainMessage<ListEventsRequest> | undefined): boolean {
    return proto3.util.equals(ListEventsRequest, a, b);
  }
}

/**
 * Newest-first page of durable EVT entries.
 *
 * @generated from message chatto.admin.v1.ListEventsResponse
 */
export class ListEventsResponse extends Message<ListEventsResponse> {
  /**
   * Event-log rows.
   *
   * @generated from field: repeated chatto.admin.v1.AdminEventLogEntry entries = 1;
   */
  entries: AdminEventLogEntry[] = [];

  /**
   * Whether older rows may be fetched with end_cursor.
   *
   * @generated from field: bool has_older = 2;
   */
  hasOlder = false;

  /**
   * Sequence cursor for loading older rows.
   *
   * @generated from field: optional string end_cursor = 3;
   */
  endCursor?: string;

  /**
   * Total EVT message count reported by JetStream.
   *
   * @generated from field: int64 total_count = 4;
   */
  totalCount = protoInt64.zero;

  /**
   * Number of stream sequences inspected while building this page.
   *
   * @generated from field: int32 scanned_count = 5;
   */
  scannedCount = 0;

  /**
   * Maximum number of stream sequences inspected for this page.
   *
   * @generated from field: int32 scan_limit = 6;
   */
  scanLimit = 0;

  /**
   * True when a filtered request reached scan_limit before finding a full page.
   *
   * @generated from field: bool scan_limited = 7;
   */
  scanLimited = false;

  constructor(data?: PartialMessage<ListEventsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListEventsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entries", kind: "message", T: AdminEventLogEntry, repeated: true },
    { no: 2, name: "has_older", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "end_cursor", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "total_count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "scanned_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "scan_limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "scan_limited", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventsResponse | PlainMessage<ListEventsResponse> | undefined, b: ListEventsResponse | PlainMessage<ListEventsResponse> | undefined): boolean {
    return proto3.util.equals(ListEventsResponse, a, b);
  }
}

/**
 * Request to list filterable event types.
 *
 * @generated from message chatto.admin.v1.ListEventTypesRequest
 */
export class ListEventTypesRequest extends Message<ListEventTypesRequest> {
  constructor(data?: PartialMessage<ListEventTypesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListEventTypesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventTypesRequest {
    return new ListEventTypesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventTypesRequest {
    return new ListEventTypesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventTypesRequest {
    return new ListEventTypesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventTypesRequest | PlainMessage<ListEventTypesRequest> | undefined, b: ListEventTypesRequest | PlainMessage<ListEventTypesRequest> | undefined): boolean {
    return proto3.util.equals(ListEventTypesRequest, a, b);
  }
}

/**
 * Finite snapshot of event types accepted by event-log filters.
 *
 * @generated from message chatto.admin.v1.ListEventTypesResponse
 */
export class ListEventTypesResponse extends Message<ListEventTypesResponse> {
  /**
   * Sorted event type names.
   *
   * @generated from field: repeated string event_types = 1;
   */
  eventTypes: string[] = [];

  constructor(data?: PartialMessage<ListEventTypesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListEventTypesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_types", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventTypesResponse {
    return new ListEventTypesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventTypesResponse {
    return new ListEventTypesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventTypesResponse {
    return new ListEventTypesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventTypesResponse | PlainMessage<ListEventTypesResponse> | undefined, b: ListEventTypesResponse | PlainMessage<ListEventTypesResponse> | undefined): boolean {
    return proto3.util.equals(ListEventTypesResponse, a, b);
  }
}

/**
 * Request to read one durable EVT entry by stream sequence.
 *
 * @generated from message chatto.admin.v1.GetEventRequest
 */
export class GetEventRequest extends Message<GetEventRequest> {
  /**
   * Required EVT stream sequence.
   *
   * @generated from field: string sequence = 1;
   */
  sequence = "";

  constructor(data?: PartialMessage<GetEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventRequest {
    return new GetEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventRequest {
    return new GetEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventRequest {
    return new GetEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventRequest | PlainMessage<GetEventRequest> | undefined, b: GetEventRequest | PlainMessage<GetEventRequest> | undefined): boolean {
    return proto3.util.equals(GetEventRequest, a, b);
  }
}

/**
 * Result of reading one durable EVT entry.
 *
 * @generated from message chatto.admin.v1.GetEventResponse
 */
export class GetEventResponse extends Message<GetEventResponse> {
  /**
   * Requested event-log entry.
   *
   * @generated from field: chatto.admin.v1.AdminEventLogEntry entry = 1;
   */
  entry?: AdminEventLogEntry;

  constructor(data?: PartialMessage<GetEventResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetEventResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entry", kind: "message", T: AdminEventLogEntry },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventResponse {
    return new GetEventResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventResponse {
    return new GetEventResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventResponse {
    return new GetEventResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventResponse | PlainMessage<GetEventResponse> | undefined, b: GetEventResponse | PlainMessage<GetEventResponse> | undefined): boolean {
    return proto3.util.equals(GetEventResponse, a, b);
  }
}

/**
 * One durable EVT entry decoded for operator inspection.
 *
 * @generated from message chatto.admin.v1.AdminEventLogEntry
 */
export class AdminEventLogEntry extends Message<AdminEventLogEntry> {
  /**
   * EVT stream sequence.
   *
   * @generated from field: string sequence = 1;
   */
  sequence = "";

  /**
   * NATS subject.
   *
   * @generated from field: string subject = 2;
   */
  subject = "";

  /**
   * Aggregate type parsed from the subject.
   *
   * @generated from field: string aggregate_type = 3;
   */
  aggregateType = "";

  /**
   * Aggregate ID parsed from the subject.
   *
   * @generated from field: string aggregate_id = 4;
   */
  aggregateId = "";

  /**
   * Event oneof payload type, or decode-error when decoding failed.
   *
   * @generated from field: string event_type = 5;
   */
  eventType = "";

  /**
   * Durable event ID.
   *
   * @generated from field: string event_id = 6;
   */
  eventId = "";

  /**
   * Actor user ID stored on the event.
   *
   * @generated from field: string actor_id = 7;
   */
  actorId = "";

  /**
   * Event creation timestamp.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * Pretty-printed, sanitized JSON representation of the event payload.
   * Password verifiers are omitted.
   *
   * @generated from field: string payload_json = 9;
   */
  payloadJson = "";

  constructor(data?: PartialMessage<AdminEventLogEntry>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminEventLogEntry";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sequence", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "aggregate_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "aggregate_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "event_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "created_at", kind: "message", T: Timestamp },
    { no: 9, name: "payload_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminEventLogEntry {
    return new AdminEventLogEntry().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminEventLogEntry {
    return new AdminEventLogEntry().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminEventLogEntry {
    return new AdminEventLogEntry().fromJsonString(jsonString, options);
  }

  static equals(a: AdminEventLogEntry | PlainMessage<AdminEventLogEntry> | undefined, b: AdminEventLogEntry | PlainMessage<AdminEventLogEntry> | undefined): boolean {
    return proto3.util.equals(AdminEventLogEntry, a, b);
  }
}
