// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/admin/v1/oauth_clients.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { PageInfo, PageRequest } from "../../api/v1/pagination_pb.js";

/**
 * How a public OAuth client establishes its identity with this server.
 *
 * @generated from enum chatto.admin.v1.OAuthClientSource
 */
export enum OAuthClientSource {
  /**
   * The server does not recognize the source value.
   *
   * @generated from enum value: OAUTH_CLIENT_SOURCE_UNSPECIFIED = 0;
   */
  OAUTH_CLIENT_SOURCE_UNSPECIFIED = 0,

  /**
   * The client identifies itself with an HTTPS Client ID Metadata Document.
   *
   * @generated from enum value: OAUTH_CLIENT_SOURCE_CIMD = 1;
   */
  OAUTH_CLIENT_SOURCE_CIMD = 1,

  /**
   * The client uses a registration built into this Chatto release.
   *
   * @generated from enum value: OAUTH_CLIENT_SOURCE_BUILT_IN = 2;
   */
  OAUTH_CLIENT_SOURCE_BUILT_IN = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(OAuthClientSource)
proto3.util.setEnumType(OAuthClientSource, "chatto.admin.v1.OAuthClientSource", [
  { no: 0, name: "OAUTH_CLIENT_SOURCE_UNSPECIFIED" },
  { no: 1, name: "OAUTH_CLIENT_SOURCE_CIMD" },
  { no: 2, name: "OAUTH_CLIENT_SOURCE_BUILT_IN" },
]);

/**
 * Administrator policy for a public OAuth client. Trusted is an informational
 * blessing and never bypasses individual user consent.
 *
 * @generated from enum chatto.admin.v1.OAuthClientPolicy
 */
export enum OAuthClientPolicy {
  /**
   * No valid policy was supplied.
   *
   * @generated from enum value: OAUTH_CLIENT_POLICY_UNSPECIFIED = 0;
   */
  OAUTH_CLIENT_POLICY_UNSPECIFIED = 0,

  /**
   * The client follows the normal open-client authorization policy.
   *
   * @generated from enum value: OAUTH_CLIENT_POLICY_DEFAULT = 1;
   */
  OAUTH_CLIENT_POLICY_DEFAULT = 1,

  /**
   * Administrators have labelled the client as trusted without changing consent.
   *
   * @generated from enum value: OAUTH_CLIENT_POLICY_TRUSTED = 2;
   */
  OAUTH_CLIENT_POLICY_TRUSTED = 2,

  /**
   * The client cannot authorize or use its existing OAuth access tokens.
   *
   * @generated from enum value: OAUTH_CLIENT_POLICY_BLOCKED = 3;
   */
  OAUTH_CLIENT_POLICY_BLOCKED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(OAuthClientPolicy)
proto3.util.setEnumType(OAuthClientPolicy, "chatto.admin.v1.OAuthClientPolicy", [
  { no: 0, name: "OAUTH_CLIENT_POLICY_UNSPECIFIED" },
  { no: 1, name: "OAUTH_CLIENT_POLICY_DEFAULT" },
  { no: 2, name: "OAUTH_CLIENT_POLICY_TRUSTED" },
  { no: 3, name: "OAUTH_CLIENT_POLICY_BLOCKED" },
]);

/**
 * An OAuth client that completed at least one successful user authorization.
 *
 * @generated from message chatto.admin.v1.OAuthClient
 */
export class OAuthClient extends Message<OAuthClient> {
  /**
   * Stable client identifier: a CIMD URL or built-in application URI.
   *
   * @generated from field: string client_id = 1;
   */
  clientId = "";

  /**
   * Display name from validated client metadata.
   *
   * @generated from field: string client_name = 2;
   */
  clientName = "";

  /**
   * Privacy-safe canonical origin derived from validated client metadata.
   *
   * @generated from field: string client_origin = 3;
   */
  clientOrigin = "";

  /**
   * How the client identity was established.
   *
   * @generated from field: chatto.admin.v1.OAuthClientSource source = 4;
   */
  source = OAuthClientSource.OAUTH_CLIENT_SOURCE_UNSPECIFIED;

  /**
   * Current server-administrator policy for the client.
   *
   * @generated from field: chatto.admin.v1.OAuthClientPolicy policy = 5;
   */
  policy = OAuthClientPolicy.OAUTH_CLIENT_POLICY_UNSPECIFIED;

  /**
   * When this server first completed an authorization for the client.
   *
   * @generated from field: google.protobuf.Timestamp first_authorization_at = 6;
   */
  firstAuthorizationAt?: Timestamp;

  /**
   * When this server most recently completed an authorization for the client.
   *
   * @generated from field: google.protobuf.Timestamp last_authorization_at = 7;
   */
  lastAuthorizationAt?: Timestamp;

  /**
   * Canonical web origins or native callback schemes seen during authorization.
   *
   * @generated from field: repeated string redirect_origins = 8;
   */
  redirectOrigins: string[] = [];

  /**
   * Number of distinct users who have authorized this client.
   *
   * @generated from field: uint32 authorized_user_count = 9;
   */
  authorizedUserCount = 0;

  constructor(data?: PartialMessage<OAuthClient>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.OAuthClient";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "client_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "client_origin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "source", kind: "enum", T: proto3.getEnumType(OAuthClientSource) },
    { no: 5, name: "policy", kind: "enum", T: proto3.getEnumType(OAuthClientPolicy) },
    { no: 6, name: "first_authorization_at", kind: "message", T: Timestamp },
    { no: 7, name: "last_authorization_at", kind: "message", T: Timestamp },
    { no: 8, name: "redirect_origins", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 9, name: "authorized_user_count", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OAuthClient {
    return new OAuthClient().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OAuthClient {
    return new OAuthClient().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OAuthClient {
    return new OAuthClient().fromJsonString(jsonString, options);
  }

  static equals(a: OAuthClient | PlainMessage<OAuthClient> | undefined, b: OAuthClient | PlainMessage<OAuthClient> | undefined): boolean {
    return proto3.util.equals(OAuthClient, a, b);
  }
}

/**
 * Lists OAuth clients with recorded authorizations using offset pagination.
 *
 * @generated from message chatto.admin.v1.ListOAuthClientsRequest
 */
export class ListOAuthClientsRequest extends Message<ListOAuthClientsRequest> {
  /**
   * Requested offset and page size.
   *
   * @generated from field: chatto.api.v1.PageRequest page = 1;
   */
  page?: PageRequest;

  constructor(data?: PartialMessage<ListOAuthClientsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListOAuthClientsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListOAuthClientsRequest {
    return new ListOAuthClientsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListOAuthClientsRequest {
    return new ListOAuthClientsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListOAuthClientsRequest {
    return new ListOAuthClientsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListOAuthClientsRequest | PlainMessage<ListOAuthClientsRequest> | undefined, b: ListOAuthClientsRequest | PlainMessage<ListOAuthClientsRequest> | undefined): boolean {
    return proto3.util.equals(ListOAuthClientsRequest, a, b);
  }
}

/**
 * One page of OAuth clients in stable first-authorization order.
 *
 * @generated from message chatto.admin.v1.ListOAuthClientsResponse
 */
export class ListOAuthClientsResponse extends Message<ListOAuthClientsResponse> {
  /**
   * Clients visible to the caller in this page.
   *
   * @generated from field: repeated chatto.admin.v1.OAuthClient oauth_clients = 1;
   */
  oauthClients: OAuthClient[] = [];

  /**
   * Total count and whether another page is available.
   *
   * @generated from field: chatto.api.v1.PageInfo page = 2;
   */
  page?: PageInfo;

  constructor(data?: PartialMessage<ListOAuthClientsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListOAuthClientsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "oauth_clients", kind: "message", T: OAuthClient, repeated: true },
    { no: 2, name: "page", kind: "message", T: PageInfo },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListOAuthClientsResponse {
    return new ListOAuthClientsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListOAuthClientsResponse {
    return new ListOAuthClientsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListOAuthClientsResponse {
    return new ListOAuthClientsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListOAuthClientsResponse | PlainMessage<ListOAuthClientsResponse> | undefined, b: ListOAuthClientsResponse | PlainMessage<ListOAuthClientsResponse> | undefined): boolean {
    return proto3.util.equals(ListOAuthClientsResponse, a, b);
  }
}

/**
 * Identifies one OAuth client by its exact stable client ID.
 *
 * @generated from message chatto.admin.v1.GetOAuthClientRequest
 */
export class GetOAuthClientRequest extends Message<GetOAuthClientRequest> {
  /**
   * Exact CIMD URL or built-in application URI.
   *
   * @generated from field: string client_id = 1;
   */
  clientId = "";

  constructor(data?: PartialMessage<GetOAuthClientRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetOAuthClientRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetOAuthClientRequest {
    return new GetOAuthClientRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetOAuthClientRequest {
    return new GetOAuthClientRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetOAuthClientRequest {
    return new GetOAuthClientRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetOAuthClientRequest | PlainMessage<GetOAuthClientRequest> | undefined, b: GetOAuthClientRequest | PlainMessage<GetOAuthClientRequest> | undefined): boolean {
    return proto3.util.equals(GetOAuthClientRequest, a, b);
  }
}

/**
 * Returns one OAuth client with a recorded authorization.
 *
 * @generated from message chatto.admin.v1.GetOAuthClientResponse
 */
export class GetOAuthClientResponse extends Message<GetOAuthClientResponse> {
  /**
   * The requested client.
   *
   * @generated from field: chatto.admin.v1.OAuthClient oauth_client = 1;
   */
  oauthClient?: OAuthClient;

  constructor(data?: PartialMessage<GetOAuthClientResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetOAuthClientResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "oauth_client", kind: "message", T: OAuthClient },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetOAuthClientResponse {
    return new GetOAuthClientResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetOAuthClientResponse {
    return new GetOAuthClientResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetOAuthClientResponse {
    return new GetOAuthClientResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetOAuthClientResponse | PlainMessage<GetOAuthClientResponse> | undefined, b: GetOAuthClientResponse | PlainMessage<GetOAuthClientResponse> | undefined): boolean {
    return proto3.util.equals(GetOAuthClientResponse, a, b);
  }
}

/**
 * Replaces the administrative policy for one OAuth client.
 *
 * @generated from message chatto.admin.v1.UpdateOAuthClientPolicyRequest
 */
export class UpdateOAuthClientPolicyRequest extends Message<UpdateOAuthClientPolicyRequest> {
  /**
   * Exact CIMD URL or built-in application URI.
   *
   * @generated from field: string client_id = 1;
   */
  clientId = "";

  /**
   * New complete policy value. Default removes any trusted or blocked label.
   *
   * @generated from field: chatto.admin.v1.OAuthClientPolicy policy = 2;
   */
  policy = OAuthClientPolicy.OAUTH_CLIENT_POLICY_UNSPECIFIED;

  constructor(data?: PartialMessage<UpdateOAuthClientPolicyRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateOAuthClientPolicyRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "policy", kind: "enum", T: proto3.getEnumType(OAuthClientPolicy) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateOAuthClientPolicyRequest {
    return new UpdateOAuthClientPolicyRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateOAuthClientPolicyRequest {
    return new UpdateOAuthClientPolicyRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateOAuthClientPolicyRequest {
    return new UpdateOAuthClientPolicyRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateOAuthClientPolicyRequest | PlainMessage<UpdateOAuthClientPolicyRequest> | undefined, b: UpdateOAuthClientPolicyRequest | PlainMessage<UpdateOAuthClientPolicyRequest> | undefined): boolean {
    return proto3.util.equals(UpdateOAuthClientPolicyRequest, a, b);
  }
}

/**
 * Returns the OAuth client with its updated policy.
 *
 * @generated from message chatto.admin.v1.UpdateOAuthClientPolicyResponse
 */
export class UpdateOAuthClientPolicyResponse extends Message<UpdateOAuthClientPolicyResponse> {
  /**
   * The updated client.
   *
   * @generated from field: chatto.admin.v1.OAuthClient oauth_client = 1;
   */
  oauthClient?: OAuthClient;

  constructor(data?: PartialMessage<UpdateOAuthClientPolicyResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateOAuthClientPolicyResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "oauth_client", kind: "message", T: OAuthClient },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateOAuthClientPolicyResponse {
    return new UpdateOAuthClientPolicyResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateOAuthClientPolicyResponse {
    return new UpdateOAuthClientPolicyResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateOAuthClientPolicyResponse {
    return new UpdateOAuthClientPolicyResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateOAuthClientPolicyResponse | PlainMessage<UpdateOAuthClientPolicyResponse> | undefined, b: UpdateOAuthClientPolicyResponse | PlainMessage<UpdateOAuthClientPolicyResponse> | undefined): boolean {
    return proto3.util.equals(UpdateOAuthClientPolicyResponse, a, b);
  }
}
