// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/admin/v1/oauth_clients.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetOAuthClientRequest, GetOAuthClientResponse, ListOAuthClientsRequest, ListOAuthClientsResponse, UpdateOAuthClientPolicyRequest, UpdateOAuthClientPolicyResponse } from "./oauth_clients_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Manages OAuth clients authorized through this server. Requires server.manage.
 *
 * @generated from service chatto.admin.v1.AdminOAuthClientService
 */
export const AdminOAuthClientService = {
  typeName: "chatto.admin.v1.AdminOAuthClientService",
  methods: {
    /**
     * Lists clients that completed at least one authorization. Requires server.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminOAuthClientService.ListOAuthClients
     */
    listOAuthClients: {
      name: "ListOAuthClients",
      I: ListOAuthClientsRequest,
      O: ListOAuthClientsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets one recorded client or returns NOT_FOUND. Requires server.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminOAuthClientService.GetOAuthClient
     */
    getOAuthClient: {
      name: "GetOAuthClient",
      I: GetOAuthClientRequest,
      O: GetOAuthClientResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Replaces a client's policy and revokes tokens when blocked. Requires server.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminOAuthClientService.UpdateOAuthClientPolicy
     */
    updateOAuthClientPolicy: {
      name: "UpdateOAuthClientPolicy",
      I: UpdateOAuthClientPolicyRequest,
      O: UpdateOAuthClientPolicyResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
