// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/admin/v1/permissions.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ExplainPermissionsRequest, ExplainPermissionsResponse, GetRolePermissionMatrixRequest, GetRolePermissionMatrixResponse, GetRolePermissionTierMatrixRequest, GetRolePermissionTierMatrixResponse, GetUserPermissionMatrixRequest, GetUserPermissionMatrixResponse, ListRolePermissionDecisionsRequest, ListRolePermissionDecisionsResponse, ListUserPermissionDecisionsRequest, ListUserPermissionDecisionsResponse, SetRolePermissionRequest, SetRolePermissionResponse, SetUserPermissionRequest, SetUserPermissionResponse } from "./permissions_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Provides permission matrix reads and admin permission writes.
 *
 * @generated from service chatto.admin.v1.AdminPermissionService
 */
export const AdminPermissionService = {
  typeName: "chatto.admin.v1.AdminPermissionService",
  methods: {
    /**
     * Gets the role-permission matrix for a single tier. Server scope requires
     * role.manage; group and room scopes require role.manage or effective
     * room.manage at the requested resource.
     *
     * @generated from rpc chatto.admin.v1.AdminPermissionService.GetRolePermissionTierMatrix
     */
    getRolePermissionTierMatrix: {
      name: "GetRolePermissionTierMatrix",
      I: GetRolePermissionTierMatrixRequest,
      O: GetRolePermissionTierMatrixResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets one role's full permission matrix. Requires role.manage. Returns
     * NOT_FOUND when the role does not exist.
     *
     * @generated from rpc chatto.admin.v1.AdminPermissionService.GetRolePermissionMatrix
     */
    getRolePermissionMatrix: {
      name: "GetRolePermissionMatrix",
      I: GetRolePermissionMatrixRequest,
      O: GetRolePermissionMatrixResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists one role's permission decisions as resource-oriented rows. Requires
     * role.manage. Returns NOT_FOUND when the role does not exist.
     *
     * @generated from rpc chatto.admin.v1.AdminPermissionService.ListRolePermissionDecisions
     */
    listRolePermissionDecisions: {
      name: "ListRolePermissionDecisions",
      I: ListRolePermissionDecisionsRequest,
      O: ListRolePermissionDecisionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets one user's full permission matrix. Human targets require
     * user.manage-permissions; bot targets require ownership or bot.manage.
     * Returns NOT_FOUND when the user does not exist.
     *
     * @generated from rpc chatto.admin.v1.AdminPermissionService.GetUserPermissionMatrix
     */
    getUserPermissionMatrix: {
      name: "GetUserPermissionMatrix",
      I: GetUserPermissionMatrixRequest,
      O: GetUserPermissionMatrixResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists one user's permission decisions as resource-oriented rows. Human
     * targets require user.manage-permissions; bot targets require ownership or
     * bot.manage. Returns NOT_FOUND when the user does not exist.
     *
     * @generated from rpc chatto.admin.v1.AdminPermissionService.ListUserPermissionDecisions
     */
    listUserPermissionDecisions: {
      name: "ListUserPermissionDecisions",
      I: ListUserPermissionDecisionsRequest,
      O: ListUserPermissionDecisionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Explains permission resolution for another user. Requires role.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminPermissionService.ExplainPermissions
     */
    explainPermissions: {
      name: "ExplainPermissions",
      I: ExplainPermissionsRequest,
      O: ExplainPermissionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sets one role permission decision. Server scope requires role.manage;
     * group and room scopes also accept effective room.manage at that resource.
     *
     * @generated from rpc chatto.admin.v1.AdminPermissionService.SetRolePermission
     */
    setRolePermission: {
      name: "SetRolePermission",
      I: SetRolePermissionRequest,
      O: SetRolePermissionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sets one user permission decision. Human targets require
     * user.manage-permissions; bot targets require ownership or bot.manage and
     * accept only allow or clear within the bot owner's current authority.
     *
     * @generated from rpc chatto.admin.v1.AdminPermissionService.SetUserPermission
     */
    setUserPermission: {
      name: "SetUserPermission",
      I: SetUserPermissionRequest,
      O: SetUserPermissionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
