// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/admin/v1/room_layout.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Room } from "../../api/v1/rooms_pb.js";
import { SidebarLink } from "../../api/v1/room_directory_pb.js";

/**
 * Sidebar item kind used in reorder requests.
 *
 * @generated from enum chatto.admin.v1.AdminRoomLayoutItemKind
 */
export enum AdminRoomLayoutItemKind {
  /**
   * The item kind was not specified.
   *
   * @generated from enum value: ADMIN_ROOM_LAYOUT_ITEM_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Channel room entry.
   *
   * @generated from enum value: ADMIN_ROOM_LAYOUT_ITEM_KIND_ROOM = 1;
   */
  ROOM = 1,

  /**
   * Sidebar link entry.
   *
   * @generated from enum value: ADMIN_ROOM_LAYOUT_ITEM_KIND_SIDEBAR_LINK = 2;
   */
  SIDEBAR_LINK = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(AdminRoomLayoutItemKind)
proto3.util.setEnumType(AdminRoomLayoutItemKind, "chatto.admin.v1.AdminRoomLayoutItemKind", [
  { no: 0, name: "ADMIN_ROOM_LAYOUT_ITEM_KIND_UNSPECIFIED" },
  { no: 1, name: "ADMIN_ROOM_LAYOUT_ITEM_KIND_ROOM" },
  { no: 2, name: "ADMIN_ROOM_LAYOUT_ITEM_KIND_SIDEBAR_LINK" },
]);

/**
 * One ordered sidebar item in an admin room group layout.
 *
 * @generated from message chatto.admin.v1.AdminRoomLayoutItem
 */
export class AdminRoomLayoutItem extends Message<AdminRoomLayoutItem> {
  /**
   * @generated from oneof chatto.admin.v1.AdminRoomLayoutItem.item
   */
  item: {
    /**
     * Channel room entry.
     *
     * @generated from field: chatto.api.v1.Room room = 1;
     */
    value: Room;
    case: "room";
  } | {
    /**
     * Sidebar link entry.
     *
     * @generated from field: chatto.api.v1.SidebarLink sidebar_link = 2;
     */
    value: SidebarLink;
    case: "sidebarLink";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<AdminRoomLayoutItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminRoomLayoutItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room", kind: "message", T: Room, oneof: "item" },
    { no: 2, name: "sidebar_link", kind: "message", T: SidebarLink, oneof: "item" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminRoomLayoutItem {
    return new AdminRoomLayoutItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminRoomLayoutItem {
    return new AdminRoomLayoutItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminRoomLayoutItem {
    return new AdminRoomLayoutItem().fromJsonString(jsonString, options);
  }

  static equals(a: AdminRoomLayoutItem | PlainMessage<AdminRoomLayoutItem> | undefined, b: AdminRoomLayoutItem | PlainMessage<AdminRoomLayoutItem> | undefined): boolean {
    return proto3.util.equals(AdminRoomLayoutItem, a, b);
  }
}

/**
 * Ordered room group returned after admin layout mutations.
 *
 * @generated from message chatto.admin.v1.AdminRoomLayoutGroup
 */
export class AdminRoomLayoutGroup extends Message<AdminRoomLayoutGroup> {
  /**
   * Stable room group ID.
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Display name.
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * Public group description, when set.
   *
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * Mixed room/sidebar-link entries in sidebar order.
   *
   * @generated from field: repeated chatto.admin.v1.AdminRoomLayoutItem items = 5;
   */
  items: AdminRoomLayoutItem[] = [];

  /**
   * Whether the viewer can create rooms in this group.
   *
   * @generated from field: bool can_create_room = 6;
   */
  canCreateRoom = false;

  constructor(data?: PartialMessage<AdminRoomLayoutGroup>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminRoomLayoutGroup";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "items", kind: "message", T: AdminRoomLayoutItem, repeated: true },
    { no: 6, name: "can_create_room", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminRoomLayoutGroup {
    return new AdminRoomLayoutGroup().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminRoomLayoutGroup {
    return new AdminRoomLayoutGroup().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminRoomLayoutGroup {
    return new AdminRoomLayoutGroup().fromJsonString(jsonString, options);
  }

  static equals(a: AdminRoomLayoutGroup | PlainMessage<AdminRoomLayoutGroup> | undefined, b: AdminRoomLayoutGroup | PlainMessage<AdminRoomLayoutGroup> | undefined): boolean {
    return proto3.util.equals(AdminRoomLayoutGroup, a, b);
  }
}

/**
 * Request for management-authorized channel room metadata.
 *
 * @generated from message chatto.admin.v1.GetRoomRequest
 */
export class GetRoomRequest extends Message<GetRoomRequest> {
  /**
   * Required channel room ID.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<GetRoomRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetRoomRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRoomRequest {
    return new GetRoomRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRoomRequest {
    return new GetRoomRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRoomRequest {
    return new GetRoomRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRoomRequest | PlainMessage<GetRoomRequest> | undefined, b: GetRoomRequest | PlainMessage<GetRoomRequest> | undefined): boolean {
    return proto3.util.equals(GetRoomRequest, a, b);
  }
}

/**
 * Channel room metadata and the caller's management capabilities.
 *
 * @generated from message chatto.admin.v1.GetRoomResponse
 */
export class GetRoomResponse extends Message<GetRoomResponse> {
  /**
   * Requested channel room. This read does not require ordinary directory
   * visibility when the caller can configure the room's role permissions.
   *
   * @generated from field: chatto.api.v1.Room room = 1;
   */
  room?: Room;

  /**
   * Whether the caller can update the room's general settings.
   *
   * @generated from field: bool viewer_can_manage_room = 2;
   */
  viewerCanManageRoom = false;

  /**
   * Whether the caller can configure role permissions for the room.
   *
   * @generated from field: bool viewer_can_manage_permissions = 3;
   */
  viewerCanManagePermissions = false;

  constructor(data?: PartialMessage<GetRoomResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetRoomResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room", kind: "message", T: Room },
    { no: 2, name: "viewer_can_manage_room", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "viewer_can_manage_permissions", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRoomResponse {
    return new GetRoomResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRoomResponse {
    return new GetRoomResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRoomResponse {
    return new GetRoomResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetRoomResponse | PlainMessage<GetRoomResponse> | undefined, b: GetRoomResponse | PlainMessage<GetRoomResponse> | undefined): boolean {
    return proto3.util.equals(GetRoomResponse, a, b);
  }
}

/**
 * Request for management-authorized room group metadata.
 *
 * @generated from message chatto.admin.v1.GetRoomGroupRequest
 */
export class GetRoomGroupRequest extends Message<GetRoomGroupRequest> {
  /**
   * Required room group ID.
   *
   * @generated from field: string group_id = 1;
   */
  groupId = "";

  constructor(data?: PartialMessage<GetRoomGroupRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetRoomGroupRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRoomGroupRequest {
    return new GetRoomGroupRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRoomGroupRequest {
    return new GetRoomGroupRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRoomGroupRequest {
    return new GetRoomGroupRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRoomGroupRequest | PlainMessage<GetRoomGroupRequest> | undefined, b: GetRoomGroupRequest | PlainMessage<GetRoomGroupRequest> | undefined): boolean {
    return proto3.util.equals(GetRoomGroupRequest, a, b);
  }
}

/**
 * Room group metadata and the caller's management capabilities.
 *
 * @generated from message chatto.admin.v1.GetRoomGroupResponse
 */
export class GetRoomGroupResponse extends Message<GetRoomGroupResponse> {
  /**
   * Requested room group metadata. Ordered room and link entries are omitted so
   * role permission managers do not gain visibility into private room names.
   *
   * @generated from field: chatto.admin.v1.AdminRoomLayoutGroup group = 1;
   */
  group?: AdminRoomLayoutGroup;

  /**
   * Whether the caller can update the room group's general settings.
   *
   * @generated from field: bool viewer_can_manage_group = 2;
   */
  viewerCanManageGroup = false;

  /**
   * Whether the caller can configure role permissions for the room group.
   *
   * @generated from field: bool viewer_can_manage_permissions = 3;
   */
  viewerCanManagePermissions = false;

  constructor(data?: PartialMessage<GetRoomGroupResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetRoomGroupResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: AdminRoomLayoutGroup },
    { no: 2, name: "viewer_can_manage_group", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "viewer_can_manage_permissions", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRoomGroupResponse {
    return new GetRoomGroupResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRoomGroupResponse {
    return new GetRoomGroupResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRoomGroupResponse {
    return new GetRoomGroupResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetRoomGroupResponse | PlainMessage<GetRoomGroupResponse> | undefined, b: GetRoomGroupResponse | PlainMessage<GetRoomGroupResponse> | undefined): boolean {
    return proto3.util.equals(GetRoomGroupResponse, a, b);
  }
}

/**
 * Request for the server-admin room group layout.
 *
 * @generated from message chatto.admin.v1.ListRoomGroupsRequest
 */
export class ListRoomGroupsRequest extends Message<ListRoomGroupsRequest> {
  constructor(data?: PartialMessage<ListRoomGroupsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListRoomGroupsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRoomGroupsRequest {
    return new ListRoomGroupsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRoomGroupsRequest {
    return new ListRoomGroupsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRoomGroupsRequest {
    return new ListRoomGroupsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListRoomGroupsRequest | PlainMessage<ListRoomGroupsRequest> | undefined, b: ListRoomGroupsRequest | PlainMessage<ListRoomGroupsRequest> | undefined): boolean {
    return proto3.util.equals(ListRoomGroupsRequest, a, b);
  }
}

/**
 * Server-admin room group layout response.
 *
 * @generated from message chatto.admin.v1.ListRoomGroupsResponse
 */
export class ListRoomGroupsResponse extends Message<ListRoomGroupsResponse> {
  /**
   * Ordered room groups, including archived rooms the caller can manage.
   *
   * @generated from field: repeated chatto.admin.v1.AdminRoomLayoutGroup groups = 1;
   */
  groups: AdminRoomLayoutGroup[] = [];

  constructor(data?: PartialMessage<ListRoomGroupsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListRoomGroupsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "groups", kind: "message", T: AdminRoomLayoutGroup, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListRoomGroupsResponse {
    return new ListRoomGroupsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListRoomGroupsResponse {
    return new ListRoomGroupsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListRoomGroupsResponse {
    return new ListRoomGroupsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListRoomGroupsResponse | PlainMessage<ListRoomGroupsResponse> | undefined, b: ListRoomGroupsResponse | PlainMessage<ListRoomGroupsResponse> | undefined): boolean {
    return proto3.util.equals(ListRoomGroupsResponse, a, b);
  }
}

/**
 * One item reference in a sidebar order replacement.
 *
 * @generated from message chatto.admin.v1.AdminRoomLayoutItemInput
 */
export class AdminRoomLayoutItemInput extends Message<AdminRoomLayoutItemInput> {
  /**
   * Item kind.
   *
   * @generated from field: chatto.admin.v1.AdminRoomLayoutItemKind kind = 1;
   */
  kind = AdminRoomLayoutItemKind.UNSPECIFIED;

  /**
   * Room ID when kind is ROOM, sidebar link ID when kind is SIDEBAR_LINK.
   *
   * @generated from field: string id = 2;
   */
  id = "";

  constructor(data?: PartialMessage<AdminRoomLayoutItemInput>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.AdminRoomLayoutItemInput";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "kind", kind: "enum", T: proto3.getEnumType(AdminRoomLayoutItemKind) },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdminRoomLayoutItemInput {
    return new AdminRoomLayoutItemInput().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdminRoomLayoutItemInput {
    return new AdminRoomLayoutItemInput().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdminRoomLayoutItemInput {
    return new AdminRoomLayoutItemInput().fromJsonString(jsonString, options);
  }

  static equals(a: AdminRoomLayoutItemInput | PlainMessage<AdminRoomLayoutItemInput> | undefined, b: AdminRoomLayoutItemInput | PlainMessage<AdminRoomLayoutItemInput> | undefined): boolean {
    return proto3.util.equals(AdminRoomLayoutItemInput, a, b);
  }
}

/**
 * Request to create a room group.
 *
 * @generated from message chatto.admin.v1.CreateRoomGroupRequest
 */
export class CreateRoomGroupRequest extends Message<CreateRoomGroupRequest> {
  /**
   * Required group display name.
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Optional public group description.
   *
   * @generated from field: string description = 2;
   */
  description = "";

  constructor(data?: PartialMessage<CreateRoomGroupRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.CreateRoomGroupRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateRoomGroupRequest {
    return new CreateRoomGroupRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateRoomGroupRequest {
    return new CreateRoomGroupRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateRoomGroupRequest {
    return new CreateRoomGroupRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateRoomGroupRequest | PlainMessage<CreateRoomGroupRequest> | undefined, b: CreateRoomGroupRequest | PlainMessage<CreateRoomGroupRequest> | undefined): boolean {
    return proto3.util.equals(CreateRoomGroupRequest, a, b);
  }
}

/**
 * Result of creating a room group.
 *
 * @generated from message chatto.admin.v1.CreateRoomGroupResponse
 */
export class CreateRoomGroupResponse extends Message<CreateRoomGroupResponse> {
  /**
   * Created room group.
   *
   * @generated from field: chatto.admin.v1.AdminRoomLayoutGroup group = 1;
   */
  group?: AdminRoomLayoutGroup;

  constructor(data?: PartialMessage<CreateRoomGroupResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.CreateRoomGroupResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: AdminRoomLayoutGroup },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateRoomGroupResponse {
    return new CreateRoomGroupResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateRoomGroupResponse {
    return new CreateRoomGroupResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateRoomGroupResponse {
    return new CreateRoomGroupResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateRoomGroupResponse | PlainMessage<CreateRoomGroupResponse> | undefined, b: CreateRoomGroupResponse | PlainMessage<CreateRoomGroupResponse> | undefined): boolean {
    return proto3.util.equals(CreateRoomGroupResponse, a, b);
  }
}

/**
 * Request to update a room group.
 *
 * @generated from message chatto.admin.v1.UpdateRoomGroupRequest
 */
export class UpdateRoomGroupRequest extends Message<UpdateRoomGroupRequest> {
  /**
   * Required room group ID.
   *
   * @generated from field: string group_id = 1;
   */
  groupId = "";

  /**
   * New group display name, when changing it.
   *
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * New public group description, when changing it. Empty clears the
   * description.
   *
   * @generated from field: optional string description = 3;
   */
  description?: string;

  constructor(data?: PartialMessage<UpdateRoomGroupRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateRoomGroupRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateRoomGroupRequest {
    return new UpdateRoomGroupRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateRoomGroupRequest {
    return new UpdateRoomGroupRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateRoomGroupRequest {
    return new UpdateRoomGroupRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateRoomGroupRequest | PlainMessage<UpdateRoomGroupRequest> | undefined, b: UpdateRoomGroupRequest | PlainMessage<UpdateRoomGroupRequest> | undefined): boolean {
    return proto3.util.equals(UpdateRoomGroupRequest, a, b);
  }
}

/**
 * Result of updating a room group.
 *
 * @generated from message chatto.admin.v1.UpdateRoomGroupResponse
 */
export class UpdateRoomGroupResponse extends Message<UpdateRoomGroupResponse> {
  /**
   * Updated room group.
   *
   * @generated from field: chatto.admin.v1.AdminRoomLayoutGroup group = 1;
   */
  group?: AdminRoomLayoutGroup;

  constructor(data?: PartialMessage<UpdateRoomGroupResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateRoomGroupResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: AdminRoomLayoutGroup },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateRoomGroupResponse {
    return new UpdateRoomGroupResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateRoomGroupResponse {
    return new UpdateRoomGroupResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateRoomGroupResponse {
    return new UpdateRoomGroupResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateRoomGroupResponse | PlainMessage<UpdateRoomGroupResponse> | undefined, b: UpdateRoomGroupResponse | PlainMessage<UpdateRoomGroupResponse> | undefined): boolean {
    return proto3.util.equals(UpdateRoomGroupResponse, a, b);
  }
}

/**
 * Request to delete an empty room group.
 *
 * @generated from message chatto.admin.v1.DeleteRoomGroupRequest
 */
export class DeleteRoomGroupRequest extends Message<DeleteRoomGroupRequest> {
  /**
   * Required room group ID.
   *
   * @generated from field: string group_id = 1;
   */
  groupId = "";

  constructor(data?: PartialMessage<DeleteRoomGroupRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.DeleteRoomGroupRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteRoomGroupRequest {
    return new DeleteRoomGroupRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteRoomGroupRequest {
    return new DeleteRoomGroupRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteRoomGroupRequest {
    return new DeleteRoomGroupRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteRoomGroupRequest | PlainMessage<DeleteRoomGroupRequest> | undefined, b: DeleteRoomGroupRequest | PlainMessage<DeleteRoomGroupRequest> | undefined): boolean {
    return proto3.util.equals(DeleteRoomGroupRequest, a, b);
  }
}

/**
 * Result of deleting a room group.
 *
 * @generated from message chatto.admin.v1.DeleteRoomGroupResponse
 */
export class DeleteRoomGroupResponse extends Message<DeleteRoomGroupResponse> {
  /**
   * True when the room group was deleted.
   *
   * @generated from field: bool deleted = 1;
   */
  deleted = false;

  constructor(data?: PartialMessage<DeleteRoomGroupResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.DeleteRoomGroupResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteRoomGroupResponse {
    return new DeleteRoomGroupResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteRoomGroupResponse {
    return new DeleteRoomGroupResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteRoomGroupResponse {
    return new DeleteRoomGroupResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteRoomGroupResponse | PlainMessage<DeleteRoomGroupResponse> | undefined, b: DeleteRoomGroupResponse | PlainMessage<DeleteRoomGroupResponse> | undefined): boolean {
    return proto3.util.equals(DeleteRoomGroupResponse, a, b);
  }
}

/**
 * Request to replace the global room group order.
 *
 * @generated from message chatto.admin.v1.ReorderRoomGroupsRequest
 */
export class ReorderRoomGroupsRequest extends Message<ReorderRoomGroupsRequest> {
  /**
   * Ordered room group IDs. The list must include every existing group exactly
   * once.
   *
   * @generated from field: repeated string ordered_group_ids = 1;
   */
  orderedGroupIds: string[] = [];

  constructor(data?: PartialMessage<ReorderRoomGroupsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ReorderRoomGroupsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ordered_group_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReorderRoomGroupsRequest {
    return new ReorderRoomGroupsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReorderRoomGroupsRequest {
    return new ReorderRoomGroupsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReorderRoomGroupsRequest {
    return new ReorderRoomGroupsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ReorderRoomGroupsRequest | PlainMessage<ReorderRoomGroupsRequest> | undefined, b: ReorderRoomGroupsRequest | PlainMessage<ReorderRoomGroupsRequest> | undefined): boolean {
    return proto3.util.equals(ReorderRoomGroupsRequest, a, b);
  }
}

/**
 * Result of replacing the global room group order.
 *
 * @generated from message chatto.admin.v1.ReorderRoomGroupsResponse
 */
export class ReorderRoomGroupsResponse extends Message<ReorderRoomGroupsResponse> {
  /**
   * Room groups in their new order.
   *
   * @generated from field: repeated chatto.admin.v1.AdminRoomLayoutGroup groups = 1;
   */
  groups: AdminRoomLayoutGroup[] = [];

  constructor(data?: PartialMessage<ReorderRoomGroupsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ReorderRoomGroupsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "groups", kind: "message", T: AdminRoomLayoutGroup, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReorderRoomGroupsResponse {
    return new ReorderRoomGroupsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReorderRoomGroupsResponse {
    return new ReorderRoomGroupsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReorderRoomGroupsResponse {
    return new ReorderRoomGroupsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ReorderRoomGroupsResponse | PlainMessage<ReorderRoomGroupsResponse> | undefined, b: ReorderRoomGroupsResponse | PlainMessage<ReorderRoomGroupsResponse> | undefined): boolean {
    return proto3.util.equals(ReorderRoomGroupsResponse, a, b);
  }
}

/**
 * Request to place one room group immediately before another group. When
 * before_group_id is absent, the group moves to the end of the sidebar.
 *
 * @generated from message chatto.admin.v1.MoveRoomGroupRequest
 */
export class MoveRoomGroupRequest extends Message<MoveRoomGroupRequest> {
  /**
   * Required room group to move.
   *
   * @generated from field: string group_id = 1;
   */
  groupId = "";

  /**
   * Group that follows the moved group. Omit to place the group last.
   *
   * @generated from field: optional string before_group_id = 2;
   */
  beforeGroupId?: string;

  constructor(data?: PartialMessage<MoveRoomGroupRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.MoveRoomGroupRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "before_group_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveRoomGroupRequest {
    return new MoveRoomGroupRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveRoomGroupRequest {
    return new MoveRoomGroupRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveRoomGroupRequest {
    return new MoveRoomGroupRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MoveRoomGroupRequest | PlainMessage<MoveRoomGroupRequest> | undefined, b: MoveRoomGroupRequest | PlainMessage<MoveRoomGroupRequest> | undefined): boolean {
    return proto3.util.equals(MoveRoomGroupRequest, a, b);
  }
}

/**
 * Result of moving one room group.
 *
 * @generated from message chatto.admin.v1.MoveRoomGroupResponse
 */
export class MoveRoomGroupResponse extends Message<MoveRoomGroupResponse> {
  /**
   * Room groups in their authoritative order after the move.
   *
   * @generated from field: repeated chatto.admin.v1.AdminRoomLayoutGroup groups = 1;
   */
  groups: AdminRoomLayoutGroup[] = [];

  constructor(data?: PartialMessage<MoveRoomGroupResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.MoveRoomGroupResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "groups", kind: "message", T: AdminRoomLayoutGroup, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveRoomGroupResponse {
    return new MoveRoomGroupResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveRoomGroupResponse {
    return new MoveRoomGroupResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveRoomGroupResponse {
    return new MoveRoomGroupResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MoveRoomGroupResponse | PlainMessage<MoveRoomGroupResponse> | undefined, b: MoveRoomGroupResponse | PlainMessage<MoveRoomGroupResponse> | undefined): boolean {
    return proto3.util.equals(MoveRoomGroupResponse, a, b);
  }
}

/**
 * Request to move a channel room to another room group.
 *
 * @generated from message chatto.admin.v1.MoveRoomToGroupRequest
 */
export class MoveRoomToGroupRequest extends Message<MoveRoomToGroupRequest> {
  /**
   * Required channel room ID.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required destination room group ID.
   *
   * @generated from field: string group_id = 2;
   */
  groupId = "";

  constructor(data?: PartialMessage<MoveRoomToGroupRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.MoveRoomToGroupRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveRoomToGroupRequest {
    return new MoveRoomToGroupRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveRoomToGroupRequest {
    return new MoveRoomToGroupRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveRoomToGroupRequest {
    return new MoveRoomToGroupRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MoveRoomToGroupRequest | PlainMessage<MoveRoomToGroupRequest> | undefined, b: MoveRoomToGroupRequest | PlainMessage<MoveRoomToGroupRequest> | undefined): boolean {
    return proto3.util.equals(MoveRoomToGroupRequest, a, b);
  }
}

/**
 * Result of moving a channel room.
 *
 * @generated from message chatto.admin.v1.MoveRoomToGroupResponse
 */
export class MoveRoomToGroupResponse extends Message<MoveRoomToGroupResponse> {
  /**
   * Moved room after the operation.
   *
   * @generated from field: chatto.api.v1.Room room = 1;
   */
  room?: Room;

  constructor(data?: PartialMessage<MoveRoomToGroupResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.MoveRoomToGroupResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room", kind: "message", T: Room },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveRoomToGroupResponse {
    return new MoveRoomToGroupResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveRoomToGroupResponse {
    return new MoveRoomToGroupResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveRoomToGroupResponse {
    return new MoveRoomToGroupResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MoveRoomToGroupResponse | PlainMessage<MoveRoomToGroupResponse> | undefined, b: MoveRoomToGroupResponse | PlainMessage<MoveRoomToGroupResponse> | undefined): boolean {
    return proto3.util.equals(MoveRoomToGroupResponse, a, b);
  }
}

/**
 * Request to replace the mixed sidebar item order in one group.
 *
 * @generated from message chatto.admin.v1.ReorderSidebarItemsInGroupRequest
 */
export class ReorderSidebarItemsInGroupRequest extends Message<ReorderSidebarItemsInGroupRequest> {
  /**
   * Required room group ID.
   *
   * @generated from field: string group_id = 1;
   */
  groupId = "";

  /**
   * Ordered room/sidebar-link item references.
   *
   * @generated from field: repeated chatto.admin.v1.AdminRoomLayoutItemInput items = 2;
   */
  items: AdminRoomLayoutItemInput[] = [];

  constructor(data?: PartialMessage<ReorderSidebarItemsInGroupRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ReorderSidebarItemsInGroupRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "items", kind: "message", T: AdminRoomLayoutItemInput, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReorderSidebarItemsInGroupRequest {
    return new ReorderSidebarItemsInGroupRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReorderSidebarItemsInGroupRequest {
    return new ReorderSidebarItemsInGroupRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReorderSidebarItemsInGroupRequest {
    return new ReorderSidebarItemsInGroupRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ReorderSidebarItemsInGroupRequest | PlainMessage<ReorderSidebarItemsInGroupRequest> | undefined, b: ReorderSidebarItemsInGroupRequest | PlainMessage<ReorderSidebarItemsInGroupRequest> | undefined): boolean {
    return proto3.util.equals(ReorderSidebarItemsInGroupRequest, a, b);
  }
}

/**
 * Result of replacing the mixed sidebar item order.
 *
 * @generated from message chatto.admin.v1.ReorderSidebarItemsInGroupResponse
 */
export class ReorderSidebarItemsInGroupResponse extends Message<ReorderSidebarItemsInGroupResponse> {
  /**
   * Updated room group.
   *
   * @generated from field: chatto.admin.v1.AdminRoomLayoutGroup group = 1;
   */
  group?: AdminRoomLayoutGroup;

  constructor(data?: PartialMessage<ReorderSidebarItemsInGroupResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ReorderSidebarItemsInGroupResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: AdminRoomLayoutGroup },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReorderSidebarItemsInGroupResponse {
    return new ReorderSidebarItemsInGroupResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReorderSidebarItemsInGroupResponse {
    return new ReorderSidebarItemsInGroupResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReorderSidebarItemsInGroupResponse {
    return new ReorderSidebarItemsInGroupResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ReorderSidebarItemsInGroupResponse | PlainMessage<ReorderSidebarItemsInGroupResponse> | undefined, b: ReorderSidebarItemsInGroupResponse | PlainMessage<ReorderSidebarItemsInGroupResponse> | undefined): boolean {
    return proto3.util.equals(ReorderSidebarItemsInGroupResponse, a, b);
  }
}

/**
 * Request to move one room or sidebar link to an exact sidebar position.
 * The server resolves the complete current layout, including entries that the
 * caller's ordinary room directory does not show.
 *
 * @generated from message chatto.admin.v1.MoveSidebarItemRequest
 */
export class MoveSidebarItemRequest extends Message<MoveSidebarItemRequest> {
  /**
   * Required room or sidebar link to move.
   *
   * @generated from field: chatto.admin.v1.AdminRoomLayoutItemInput item = 1;
   */
  item?: AdminRoomLayoutItemInput;

  /**
   * Required destination room group.
   *
   * @generated from field: string group_id = 2;
   */
  groupId = "";

  /**
   * Item that follows the moved item. Omit to place the item last.
   *
   * @generated from field: chatto.admin.v1.AdminRoomLayoutItemInput before = 3;
   */
  before?: AdminRoomLayoutItemInput;

  constructor(data?: PartialMessage<MoveSidebarItemRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.MoveSidebarItemRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "item", kind: "message", T: AdminRoomLayoutItemInput },
    { no: 2, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "before", kind: "message", T: AdminRoomLayoutItemInput },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveSidebarItemRequest {
    return new MoveSidebarItemRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveSidebarItemRequest {
    return new MoveSidebarItemRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveSidebarItemRequest {
    return new MoveSidebarItemRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MoveSidebarItemRequest | PlainMessage<MoveSidebarItemRequest> | undefined, b: MoveSidebarItemRequest | PlainMessage<MoveSidebarItemRequest> | undefined): boolean {
    return proto3.util.equals(MoveSidebarItemRequest, a, b);
  }
}

/**
 * Result of moving one sidebar item.
 *
 * @generated from message chatto.admin.v1.MoveSidebarItemResponse
 */
export class MoveSidebarItemResponse extends Message<MoveSidebarItemResponse> {
  /**
   * Destination room group after the move.
   *
   * @generated from field: chatto.admin.v1.AdminRoomLayoutGroup group = 1;
   */
  group?: AdminRoomLayoutGroup;

  constructor(data?: PartialMessage<MoveSidebarItemResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.MoveSidebarItemResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group", kind: "message", T: AdminRoomLayoutGroup },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveSidebarItemResponse {
    return new MoveSidebarItemResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveSidebarItemResponse {
    return new MoveSidebarItemResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveSidebarItemResponse {
    return new MoveSidebarItemResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MoveSidebarItemResponse | PlainMessage<MoveSidebarItemResponse> | undefined, b: MoveSidebarItemResponse | PlainMessage<MoveSidebarItemResponse> | undefined): boolean {
    return proto3.util.equals(MoveSidebarItemResponse, a, b);
  }
}

/**
 * Request to create a sidebar link in one room group.
 *
 * @generated from message chatto.admin.v1.CreateSidebarLinkRequest
 */
export class CreateSidebarLinkRequest extends Message<CreateSidebarLinkRequest> {
  /**
   * Required destination room group ID.
   *
   * @generated from field: string group_id = 1;
   */
  groupId = "";

  /**
   * Required display label.
   *
   * @generated from field: string label = 2;
   */
  label = "";

  /**
   * Required absolute http(s) URL or server-local path.
   *
   * @generated from field: string url = 3;
   */
  url = "";

  constructor(data?: PartialMessage<CreateSidebarLinkRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.CreateSidebarLinkRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateSidebarLinkRequest {
    return new CreateSidebarLinkRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateSidebarLinkRequest {
    return new CreateSidebarLinkRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateSidebarLinkRequest {
    return new CreateSidebarLinkRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateSidebarLinkRequest | PlainMessage<CreateSidebarLinkRequest> | undefined, b: CreateSidebarLinkRequest | PlainMessage<CreateSidebarLinkRequest> | undefined): boolean {
    return proto3.util.equals(CreateSidebarLinkRequest, a, b);
  }
}

/**
 * Result of creating a sidebar link.
 *
 * @generated from message chatto.admin.v1.CreateSidebarLinkResponse
 */
export class CreateSidebarLinkResponse extends Message<CreateSidebarLinkResponse> {
  /**
   * Created sidebar link.
   *
   * @generated from field: chatto.api.v1.SidebarLink sidebar_link = 1;
   */
  sidebarLink?: SidebarLink;

  constructor(data?: PartialMessage<CreateSidebarLinkResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.CreateSidebarLinkResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sidebar_link", kind: "message", T: SidebarLink },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateSidebarLinkResponse {
    return new CreateSidebarLinkResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateSidebarLinkResponse {
    return new CreateSidebarLinkResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateSidebarLinkResponse {
    return new CreateSidebarLinkResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateSidebarLinkResponse | PlainMessage<CreateSidebarLinkResponse> | undefined, b: CreateSidebarLinkResponse | PlainMessage<CreateSidebarLinkResponse> | undefined): boolean {
    return proto3.util.equals(CreateSidebarLinkResponse, a, b);
  }
}

/**
 * Request to update a sidebar link.
 *
 * @generated from message chatto.admin.v1.UpdateSidebarLinkRequest
 */
export class UpdateSidebarLinkRequest extends Message<UpdateSidebarLinkRequest> {
  /**
   * Required sidebar link ID.
   *
   * @generated from field: string link_id = 1;
   */
  linkId = "";

  /**
   * New display label, when changing it.
   *
   * @generated from field: optional string label = 2;
   */
  label?: string;

  /**
   * New absolute http(s) URL or server-local path, when changing it.
   *
   * @generated from field: optional string url = 3;
   */
  url?: string;

  constructor(data?: PartialMessage<UpdateSidebarLinkRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateSidebarLinkRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "link_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateSidebarLinkRequest {
    return new UpdateSidebarLinkRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateSidebarLinkRequest {
    return new UpdateSidebarLinkRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateSidebarLinkRequest {
    return new UpdateSidebarLinkRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateSidebarLinkRequest | PlainMessage<UpdateSidebarLinkRequest> | undefined, b: UpdateSidebarLinkRequest | PlainMessage<UpdateSidebarLinkRequest> | undefined): boolean {
    return proto3.util.equals(UpdateSidebarLinkRequest, a, b);
  }
}

/**
 * Result of updating a sidebar link.
 *
 * @generated from message chatto.admin.v1.UpdateSidebarLinkResponse
 */
export class UpdateSidebarLinkResponse extends Message<UpdateSidebarLinkResponse> {
  /**
   * Updated sidebar link.
   *
   * @generated from field: chatto.api.v1.SidebarLink sidebar_link = 1;
   */
  sidebarLink?: SidebarLink;

  constructor(data?: PartialMessage<UpdateSidebarLinkResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateSidebarLinkResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sidebar_link", kind: "message", T: SidebarLink },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateSidebarLinkResponse {
    return new UpdateSidebarLinkResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateSidebarLinkResponse {
    return new UpdateSidebarLinkResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateSidebarLinkResponse {
    return new UpdateSidebarLinkResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateSidebarLinkResponse | PlainMessage<UpdateSidebarLinkResponse> | undefined, b: UpdateSidebarLinkResponse | PlainMessage<UpdateSidebarLinkResponse> | undefined): boolean {
    return proto3.util.equals(UpdateSidebarLinkResponse, a, b);
  }
}

/**
 * Request to delete a sidebar link.
 *
 * @generated from message chatto.admin.v1.DeleteSidebarLinkRequest
 */
export class DeleteSidebarLinkRequest extends Message<DeleteSidebarLinkRequest> {
  /**
   * Required sidebar link ID.
   *
   * @generated from field: string link_id = 1;
   */
  linkId = "";

  constructor(data?: PartialMessage<DeleteSidebarLinkRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.DeleteSidebarLinkRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "link_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteSidebarLinkRequest {
    return new DeleteSidebarLinkRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteSidebarLinkRequest {
    return new DeleteSidebarLinkRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteSidebarLinkRequest {
    return new DeleteSidebarLinkRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteSidebarLinkRequest | PlainMessage<DeleteSidebarLinkRequest> | undefined, b: DeleteSidebarLinkRequest | PlainMessage<DeleteSidebarLinkRequest> | undefined): boolean {
    return proto3.util.equals(DeleteSidebarLinkRequest, a, b);
  }
}

/**
 * Result of deleting a sidebar link.
 *
 * @generated from message chatto.admin.v1.DeleteSidebarLinkResponse
 */
export class DeleteSidebarLinkResponse extends Message<DeleteSidebarLinkResponse> {
  /**
   * True when the sidebar link was deleted.
   *
   * @generated from field: bool deleted = 1;
   */
  deleted = false;

  constructor(data?: PartialMessage<DeleteSidebarLinkResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.DeleteSidebarLinkResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteSidebarLinkResponse {
    return new DeleteSidebarLinkResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteSidebarLinkResponse {
    return new DeleteSidebarLinkResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteSidebarLinkResponse {
    return new DeleteSidebarLinkResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteSidebarLinkResponse | PlainMessage<DeleteSidebarLinkResponse> | undefined, b: DeleteSidebarLinkResponse | PlainMessage<DeleteSidebarLinkResponse> | undefined): boolean {
    return proto3.util.equals(DeleteSidebarLinkResponse, a, b);
  }
}

/**
 * Request to move a sidebar link to another room group.
 *
 * @generated from message chatto.admin.v1.MoveSidebarLinkToGroupRequest
 */
export class MoveSidebarLinkToGroupRequest extends Message<MoveSidebarLinkToGroupRequest> {
  /**
   * Required sidebar link ID.
   *
   * @generated from field: string link_id = 1;
   */
  linkId = "";

  /**
   * Required destination room group ID.
   *
   * @generated from field: string group_id = 2;
   */
  groupId = "";

  constructor(data?: PartialMessage<MoveSidebarLinkToGroupRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.MoveSidebarLinkToGroupRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "link_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveSidebarLinkToGroupRequest {
    return new MoveSidebarLinkToGroupRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveSidebarLinkToGroupRequest {
    return new MoveSidebarLinkToGroupRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveSidebarLinkToGroupRequest {
    return new MoveSidebarLinkToGroupRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MoveSidebarLinkToGroupRequest | PlainMessage<MoveSidebarLinkToGroupRequest> | undefined, b: MoveSidebarLinkToGroupRequest | PlainMessage<MoveSidebarLinkToGroupRequest> | undefined): boolean {
    return proto3.util.equals(MoveSidebarLinkToGroupRequest, a, b);
  }
}

/**
 * Result of moving a sidebar link.
 *
 * @generated from message chatto.admin.v1.MoveSidebarLinkToGroupResponse
 */
export class MoveSidebarLinkToGroupResponse extends Message<MoveSidebarLinkToGroupResponse> {
  /**
   * Moved sidebar link.
   *
   * @generated from field: chatto.api.v1.SidebarLink sidebar_link = 1;
   */
  sidebarLink?: SidebarLink;

  constructor(data?: PartialMessage<MoveSidebarLinkToGroupResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.MoveSidebarLinkToGroupResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sidebar_link", kind: "message", T: SidebarLink },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveSidebarLinkToGroupResponse {
    return new MoveSidebarLinkToGroupResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveSidebarLinkToGroupResponse {
    return new MoveSidebarLinkToGroupResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveSidebarLinkToGroupResponse {
    return new MoveSidebarLinkToGroupResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MoveSidebarLinkToGroupResponse | PlainMessage<MoveSidebarLinkToGroupResponse> | undefined, b: MoveSidebarLinkToGroupResponse | PlainMessage<MoveSidebarLinkToGroupResponse> | undefined): boolean {
    return proto3.util.equals(MoveSidebarLinkToGroupResponse, a, b);
  }
}
