// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/admin/v1/server.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { ServerPublicProfile } from "../../api/v1/server_pb.js";
import { ImageUpload } from "../../api/v1/common_pb.js";

/**
 * Runtime-editable server profile settings.
 *
 * @generated from message chatto.admin.v1.ServerConfig
 */
export class ServerConfig extends Message<ServerConfig> {
  /**
   * Server name for page titles. Empty means the default is used.
   *
   * @generated from field: string server_name = 1;
   */
  serverName = "";

  /**
   * Short server description for OG link-preview metadata.
   *
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * Message of the day for the authenticated header.
   *
   * @generated from field: string motd = 3;
   */
  motd = "";

  /**
   * Welcome message shown on the login page.
   *
   * @generated from field: string welcome_message = 4;
   */
  welcomeMessage = "";

  constructor(data?: PartialMessage<ServerConfig>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ServerConfig";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "server_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "motd", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "welcome_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerConfig {
    return new ServerConfig().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerConfig {
    return new ServerConfig().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerConfig {
    return new ServerConfig().fromJsonString(jsonString, options);
  }

  static equals(a: ServerConfig | PlainMessage<ServerConfig> | undefined, b: ServerConfig | PlainMessage<ServerConfig> | undefined): boolean {
    return proto3.util.equals(ServerConfig, a, b);
  }
}

/**
 * Request server profile settings.
 *
 * @generated from message chatto.admin.v1.GetServerConfigRequest
 */
export class GetServerConfigRequest extends Message<GetServerConfigRequest> {
  constructor(data?: PartialMessage<GetServerConfigRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetServerConfigRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerConfigRequest {
    return new GetServerConfigRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerConfigRequest {
    return new GetServerConfigRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerConfigRequest {
    return new GetServerConfigRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerConfigRequest | PlainMessage<GetServerConfigRequest> | undefined, b: GetServerConfigRequest | PlainMessage<GetServerConfigRequest> | undefined): boolean {
    return proto3.util.equals(GetServerConfigRequest, a, b);
  }
}

/**
 * Server profile settings plus effective public branding.
 *
 * @generated from message chatto.admin.v1.GetServerConfigResponse
 */
export class GetServerConfigResponse extends Message<GetServerConfigResponse> {
  /**
   * Runtime-editable server profile settings.
   *
   * @generated from field: chatto.admin.v1.ServerConfig config = 1;
   */
  config?: ServerConfig;

  /**
   * Effective public server profile and branding.
   *
   * @generated from field: chatto.api.v1.ServerPublicProfile public_profile = 3;
   */
  publicProfile?: ServerPublicProfile;

  constructor(data?: PartialMessage<GetServerConfigResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetServerConfigResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "config", kind: "message", T: ServerConfig },
    { no: 3, name: "public_profile", kind: "message", T: ServerPublicProfile },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerConfigResponse {
    return new GetServerConfigResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerConfigResponse {
    return new GetServerConfigResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerConfigResponse {
    return new GetServerConfigResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerConfigResponse | PlainMessage<GetServerConfigResponse> | undefined, b: GetServerConfigResponse | PlainMessage<GetServerConfigResponse> | undefined): boolean {
    return proto3.util.equals(GetServerConfigResponse, a, b);
  }
}

/**
 * Request to update runtime-editable server profile settings.
 *
 * @generated from message chatto.admin.v1.UpdateServerConfigRequest
 */
export class UpdateServerConfigRequest extends Message<UpdateServerConfigRequest> {
  /**
   * Optional server name for page titles. Set to empty string to use default.
   *
   * @generated from field: optional string server_name = 1;
   */
  serverName?: string;

  /**
   * Optional short server description for OG link-preview metadata. Set to
   * empty string to clear.
   *
   * @generated from field: optional string description = 2;
   */
  description?: string;

  /**
   * Optional message of the day for the header. Set to empty string to clear.
   *
   * @generated from field: optional string motd = 3;
   */
  motd?: string;

  /**
   * Optional welcome message shown on the login page. Set to empty string to
   * clear.
   *
   * @generated from field: optional string welcome_message = 4;
   */
  welcomeMessage?: string;

  constructor(data?: PartialMessage<UpdateServerConfigRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateServerConfigRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "server_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "motd", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "welcome_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateServerConfigRequest {
    return new UpdateServerConfigRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateServerConfigRequest {
    return new UpdateServerConfigRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateServerConfigRequest {
    return new UpdateServerConfigRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateServerConfigRequest | PlainMessage<UpdateServerConfigRequest> | undefined, b: UpdateServerConfigRequest | PlainMessage<UpdateServerConfigRequest> | undefined): boolean {
    return proto3.util.equals(UpdateServerConfigRequest, a, b);
  }
}

/**
 * Result of updating runtime-editable server profile settings.
 *
 * @generated from message chatto.admin.v1.UpdateServerConfigResponse
 */
export class UpdateServerConfigResponse extends Message<UpdateServerConfigResponse> {
  /**
   * Updated public server profile and branding.
   *
   * @generated from field: chatto.api.v1.ServerPublicProfile public_profile = 3;
   */
  publicProfile?: ServerPublicProfile;

  /**
   * Updated runtime-editable server profile settings.
   *
   * @generated from field: chatto.admin.v1.ServerConfig config = 2;
   */
  config?: ServerConfig;

  constructor(data?: PartialMessage<UpdateServerConfigResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateServerConfigResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "public_profile", kind: "message", T: ServerPublicProfile },
    { no: 2, name: "config", kind: "message", T: ServerConfig },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateServerConfigResponse {
    return new UpdateServerConfigResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateServerConfigResponse {
    return new UpdateServerConfigResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateServerConfigResponse {
    return new UpdateServerConfigResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateServerConfigResponse | PlainMessage<UpdateServerConfigResponse> | undefined, b: UpdateServerConfigResponse | PlainMessage<UpdateServerConfigResponse> | undefined): boolean {
    return proto3.util.equals(UpdateServerConfigResponse, a, b);
  }
}

/**
 * Request to upload and set the public server logo.
 *
 * @generated from message chatto.admin.v1.UploadServerLogoRequest
 */
export class UploadServerLogoRequest extends Message<UploadServerLogoRequest> {
  /**
   * Image payload. The server validates, resizes, and stores a WebP logo.
   *
   * @generated from field: chatto.api.v1.ImageUpload image = 4;
   */
  image?: ImageUpload;

  constructor(data?: PartialMessage<UploadServerLogoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UploadServerLogoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 4, name: "image", kind: "message", T: ImageUpload },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadServerLogoRequest {
    return new UploadServerLogoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadServerLogoRequest {
    return new UploadServerLogoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadServerLogoRequest {
    return new UploadServerLogoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UploadServerLogoRequest | PlainMessage<UploadServerLogoRequest> | undefined, b: UploadServerLogoRequest | PlainMessage<UploadServerLogoRequest> | undefined): boolean {
    return proto3.util.equals(UploadServerLogoRequest, a, b);
  }
}

/**
 * Result of uploading the public server logo.
 *
 * @generated from message chatto.admin.v1.UploadServerLogoResponse
 */
export class UploadServerLogoResponse extends Message<UploadServerLogoResponse> {
  /**
   * Updated public server profile and branding.
   *
   * @generated from field: chatto.api.v1.ServerPublicProfile public_profile = 2;
   */
  publicProfile?: ServerPublicProfile;

  constructor(data?: PartialMessage<UploadServerLogoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UploadServerLogoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "public_profile", kind: "message", T: ServerPublicProfile },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadServerLogoResponse {
    return new UploadServerLogoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadServerLogoResponse {
    return new UploadServerLogoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadServerLogoResponse {
    return new UploadServerLogoResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UploadServerLogoResponse | PlainMessage<UploadServerLogoResponse> | undefined, b: UploadServerLogoResponse | PlainMessage<UploadServerLogoResponse> | undefined): boolean {
    return proto3.util.equals(UploadServerLogoResponse, a, b);
  }
}

/**
 * Request to clear the public server logo.
 *
 * @generated from message chatto.admin.v1.DeleteServerLogoRequest
 */
export class DeleteServerLogoRequest extends Message<DeleteServerLogoRequest> {
  constructor(data?: PartialMessage<DeleteServerLogoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.DeleteServerLogoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteServerLogoRequest {
    return new DeleteServerLogoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteServerLogoRequest {
    return new DeleteServerLogoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteServerLogoRequest {
    return new DeleteServerLogoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteServerLogoRequest | PlainMessage<DeleteServerLogoRequest> | undefined, b: DeleteServerLogoRequest | PlainMessage<DeleteServerLogoRequest> | undefined): boolean {
    return proto3.util.equals(DeleteServerLogoRequest, a, b);
  }
}

/**
 * Result of clearing the public server logo.
 *
 * @generated from message chatto.admin.v1.DeleteServerLogoResponse
 */
export class DeleteServerLogoResponse extends Message<DeleteServerLogoResponse> {
  /**
   * Updated public server profile and branding.
   *
   * @generated from field: chatto.api.v1.ServerPublicProfile public_profile = 2;
   */
  publicProfile?: ServerPublicProfile;

  constructor(data?: PartialMessage<DeleteServerLogoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.DeleteServerLogoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "public_profile", kind: "message", T: ServerPublicProfile },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteServerLogoResponse {
    return new DeleteServerLogoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteServerLogoResponse {
    return new DeleteServerLogoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteServerLogoResponse {
    return new DeleteServerLogoResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteServerLogoResponse | PlainMessage<DeleteServerLogoResponse> | undefined, b: DeleteServerLogoResponse | PlainMessage<DeleteServerLogoResponse> | undefined): boolean {
    return proto3.util.equals(DeleteServerLogoResponse, a, b);
  }
}

/**
 * Request to upload and set the public server banner.
 *
 * @generated from message chatto.admin.v1.UploadServerBannerRequest
 */
export class UploadServerBannerRequest extends Message<UploadServerBannerRequest> {
  /**
   * Image payload. The server validates, resizes, and stores a WebP banner.
   *
   * @generated from field: chatto.api.v1.ImageUpload image = 4;
   */
  image?: ImageUpload;

  constructor(data?: PartialMessage<UploadServerBannerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UploadServerBannerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 4, name: "image", kind: "message", T: ImageUpload },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadServerBannerRequest {
    return new UploadServerBannerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadServerBannerRequest {
    return new UploadServerBannerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadServerBannerRequest {
    return new UploadServerBannerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UploadServerBannerRequest | PlainMessage<UploadServerBannerRequest> | undefined, b: UploadServerBannerRequest | PlainMessage<UploadServerBannerRequest> | undefined): boolean {
    return proto3.util.equals(UploadServerBannerRequest, a, b);
  }
}

/**
 * Result of uploading the public server banner.
 *
 * @generated from message chatto.admin.v1.UploadServerBannerResponse
 */
export class UploadServerBannerResponse extends Message<UploadServerBannerResponse> {
  /**
   * Updated public server profile and branding.
   *
   * @generated from field: chatto.api.v1.ServerPublicProfile public_profile = 2;
   */
  publicProfile?: ServerPublicProfile;

  constructor(data?: PartialMessage<UploadServerBannerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UploadServerBannerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "public_profile", kind: "message", T: ServerPublicProfile },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadServerBannerResponse {
    return new UploadServerBannerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadServerBannerResponse {
    return new UploadServerBannerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadServerBannerResponse {
    return new UploadServerBannerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UploadServerBannerResponse | PlainMessage<UploadServerBannerResponse> | undefined, b: UploadServerBannerResponse | PlainMessage<UploadServerBannerResponse> | undefined): boolean {
    return proto3.util.equals(UploadServerBannerResponse, a, b);
  }
}

/**
 * Request to clear the public server banner.
 *
 * @generated from message chatto.admin.v1.DeleteServerBannerRequest
 */
export class DeleteServerBannerRequest extends Message<DeleteServerBannerRequest> {
  constructor(data?: PartialMessage<DeleteServerBannerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.DeleteServerBannerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteServerBannerRequest {
    return new DeleteServerBannerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteServerBannerRequest {
    return new DeleteServerBannerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteServerBannerRequest {
    return new DeleteServerBannerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteServerBannerRequest | PlainMessage<DeleteServerBannerRequest> | undefined, b: DeleteServerBannerRequest | PlainMessage<DeleteServerBannerRequest> | undefined): boolean {
    return proto3.util.equals(DeleteServerBannerRequest, a, b);
  }
}

/**
 * Result of clearing the public server banner.
 *
 * @generated from message chatto.admin.v1.DeleteServerBannerResponse
 */
export class DeleteServerBannerResponse extends Message<DeleteServerBannerResponse> {
  /**
   * Updated public server profile and branding.
   *
   * @generated from field: chatto.api.v1.ServerPublicProfile public_profile = 2;
   */
  publicProfile?: ServerPublicProfile;

  constructor(data?: PartialMessage<DeleteServerBannerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.DeleteServerBannerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "public_profile", kind: "message", T: ServerPublicProfile },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteServerBannerResponse {
    return new DeleteServerBannerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteServerBannerResponse {
    return new DeleteServerBannerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteServerBannerResponse {
    return new DeleteServerBannerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteServerBannerResponse | PlainMessage<DeleteServerBannerResponse> | undefined, b: DeleteServerBannerResponse | PlainMessage<DeleteServerBannerResponse> | undefined): boolean {
    return proto3.util.equals(DeleteServerBannerResponse, a, b);
  }
}

/**
 * Request for server security configuration.
 *
 * @generated from message chatto.admin.v1.GetServerSecurityConfigRequest
 */
export class GetServerSecurityConfigRequest extends Message<GetServerSecurityConfigRequest> {
  constructor(data?: PartialMessage<GetServerSecurityConfigRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetServerSecurityConfigRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerSecurityConfigRequest {
    return new GetServerSecurityConfigRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerSecurityConfigRequest {
    return new GetServerSecurityConfigRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerSecurityConfigRequest {
    return new GetServerSecurityConfigRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerSecurityConfigRequest | PlainMessage<GetServerSecurityConfigRequest> | undefined, b: GetServerSecurityConfigRequest | PlainMessage<GetServerSecurityConfigRequest> | undefined): boolean {
    return proto3.util.equals(GetServerSecurityConfigRequest, a, b);
  }
}

/**
 * Security-sensitive server configuration. The caller must be allowed to
 * manage server configuration.
 *
 * @generated from message chatto.admin.v1.GetServerSecurityConfigResponse
 */
export class GetServerSecurityConfigResponse extends Message<GetServerSecurityConfigResponse> {
  /**
   * Blocked usernames. Entries are normalized by the server.
   *
   * @generated from field: repeated string blocked_usernames = 1;
   */
  blockedUsernames: string[] = [];

  constructor(data?: PartialMessage<GetServerSecurityConfigResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetServerSecurityConfigResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "blocked_usernames", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerSecurityConfigResponse {
    return new GetServerSecurityConfigResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerSecurityConfigResponse {
    return new GetServerSecurityConfigResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerSecurityConfigResponse {
    return new GetServerSecurityConfigResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerSecurityConfigResponse | PlainMessage<GetServerSecurityConfigResponse> | undefined, b: GetServerSecurityConfigResponse | PlainMessage<GetServerSecurityConfigResponse> | undefined): boolean {
    return proto3.util.equals(GetServerSecurityConfigResponse, a, b);
  }
}

/**
 * Request to update the server blocked-username list.
 *
 * @generated from message chatto.admin.v1.UpdateBlockedUsernamesRequest
 */
export class UpdateBlockedUsernamesRequest extends Message<UpdateBlockedUsernamesRequest> {
  /**
   * Blocked usernames. Empty entries are ignored and entries are normalized by
   * the server.
   *
   * @generated from field: repeated string blocked_usernames = 1;
   */
  blockedUsernames: string[] = [];

  constructor(data?: PartialMessage<UpdateBlockedUsernamesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateBlockedUsernamesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "blocked_usernames", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateBlockedUsernamesRequest {
    return new UpdateBlockedUsernamesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateBlockedUsernamesRequest {
    return new UpdateBlockedUsernamesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateBlockedUsernamesRequest {
    return new UpdateBlockedUsernamesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateBlockedUsernamesRequest | PlainMessage<UpdateBlockedUsernamesRequest> | undefined, b: UpdateBlockedUsernamesRequest | PlainMessage<UpdateBlockedUsernamesRequest> | undefined): boolean {
    return proto3.util.equals(UpdateBlockedUsernamesRequest, a, b);
  }
}

/**
 * Result of updating the server blocked-username list.
 *
 * @generated from message chatto.admin.v1.UpdateBlockedUsernamesResponse
 */
export class UpdateBlockedUsernamesResponse extends Message<UpdateBlockedUsernamesResponse> {
  /**
   * Effective blocked usernames after the update.
   *
   * @generated from field: repeated string blocked_usernames = 1;
   */
  blockedUsernames: string[] = [];

  constructor(data?: PartialMessage<UpdateBlockedUsernamesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateBlockedUsernamesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "blocked_usernames", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateBlockedUsernamesResponse {
    return new UpdateBlockedUsernamesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateBlockedUsernamesResponse {
    return new UpdateBlockedUsernamesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateBlockedUsernamesResponse {
    return new UpdateBlockedUsernamesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateBlockedUsernamesResponse | PlainMessage<UpdateBlockedUsernamesResponse> | undefined, b: UpdateBlockedUsernamesResponse | PlainMessage<UpdateBlockedUsernamesResponse> | undefined): boolean {
    return proto3.util.equals(UpdateBlockedUsernamesResponse, a, b);
  }
}

/**
 * One server advertised in the public Neighbor directory.
 *
 * @generated from message chatto.admin.v1.Neighbor
 */
export class Neighbor extends Message<Neighbor> {
  /**
   * Stable opaque resource ID.
   *
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * Canonical HTTP or HTTPS server origin.
   *
   * @generated from field: string origin = 2;
   */
  origin = "";

  /**
   * Opaque revision required for update and delete requests.
   *
   * @generated from field: string revision = 3;
   */
  revision = "";

  constructor(data?: PartialMessage<Neighbor>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.Neighbor";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "origin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "revision", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Neighbor {
    return new Neighbor().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Neighbor {
    return new Neighbor().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Neighbor {
    return new Neighbor().fromJsonString(jsonString, options);
  }

  static equals(a: Neighbor | PlainMessage<Neighbor> | undefined, b: Neighbor | PlainMessage<Neighbor> | undefined): boolean {
    return proto3.util.equals(Neighbor, a, b);
  }
}

/**
 * Request to list configured Neighbors.
 *
 * @generated from message chatto.admin.v1.ListNeighborsRequest
 */
export class ListNeighborsRequest extends Message<ListNeighborsRequest> {
  constructor(data?: PartialMessage<ListNeighborsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListNeighborsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListNeighborsRequest {
    return new ListNeighborsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListNeighborsRequest {
    return new ListNeighborsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListNeighborsRequest {
    return new ListNeighborsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListNeighborsRequest | PlainMessage<ListNeighborsRequest> | undefined, b: ListNeighborsRequest | PlainMessage<ListNeighborsRequest> | undefined): boolean {
    return proto3.util.equals(ListNeighborsRequest, a, b);
  }
}

/**
 * Configured Neighbors. The response has no ordering contract.
 *
 * @generated from message chatto.admin.v1.ListNeighborsResponse
 */
export class ListNeighborsResponse extends Message<ListNeighborsResponse> {
  /**
   * @generated from field: repeated chatto.admin.v1.Neighbor neighbors = 1;
   */
  neighbors: Neighbor[] = [];

  constructor(data?: PartialMessage<ListNeighborsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.ListNeighborsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "neighbors", kind: "message", T: Neighbor, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListNeighborsResponse {
    return new ListNeighborsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListNeighborsResponse {
    return new ListNeighborsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListNeighborsResponse {
    return new ListNeighborsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListNeighborsResponse | PlainMessage<ListNeighborsResponse> | undefined, b: ListNeighborsResponse | PlainMessage<ListNeighborsResponse> | undefined): boolean {
    return proto3.util.equals(ListNeighborsResponse, a, b);
  }
}

/**
 * Request for one configured Neighbor.
 *
 * @generated from message chatto.admin.v1.GetNeighborRequest
 */
export class GetNeighborRequest extends Message<GetNeighborRequest> {
  /**
   * @generated from field: string neighbor_id = 1;
   */
  neighborId = "";

  constructor(data?: PartialMessage<GetNeighborRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetNeighborRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "neighbor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetNeighborRequest {
    return new GetNeighborRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetNeighborRequest {
    return new GetNeighborRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetNeighborRequest {
    return new GetNeighborRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetNeighborRequest | PlainMessage<GetNeighborRequest> | undefined, b: GetNeighborRequest | PlainMessage<GetNeighborRequest> | undefined): boolean {
    return proto3.util.equals(GetNeighborRequest, a, b);
  }
}

/**
 * One configured Neighbor.
 *
 * @generated from message chatto.admin.v1.GetNeighborResponse
 */
export class GetNeighborResponse extends Message<GetNeighborResponse> {
  /**
   * @generated from field: chatto.admin.v1.Neighbor neighbor = 1;
   */
  neighbor?: Neighbor;

  constructor(data?: PartialMessage<GetNeighborResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.GetNeighborResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "neighbor", kind: "message", T: Neighbor },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetNeighborResponse {
    return new GetNeighborResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetNeighborResponse {
    return new GetNeighborResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetNeighborResponse {
    return new GetNeighborResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetNeighborResponse | PlainMessage<GetNeighborResponse> | undefined, b: GetNeighborResponse | PlainMessage<GetNeighborResponse> | undefined): boolean {
    return proto3.util.equals(GetNeighborResponse, a, b);
  }
}

/**
 * Request to advertise one server origin.
 *
 * @generated from message chatto.admin.v1.CreateNeighborRequest
 */
export class CreateNeighborRequest extends Message<CreateNeighborRequest> {
  /**
   * @generated from field: string origin = 1;
   */
  origin = "";

  constructor(data?: PartialMessage<CreateNeighborRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.CreateNeighborRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "origin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateNeighborRequest {
    return new CreateNeighborRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateNeighborRequest {
    return new CreateNeighborRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateNeighborRequest {
    return new CreateNeighborRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateNeighborRequest | PlainMessage<CreateNeighborRequest> | undefined, b: CreateNeighborRequest | PlainMessage<CreateNeighborRequest> | undefined): boolean {
    return proto3.util.equals(CreateNeighborRequest, a, b);
  }
}

/**
 * Newly configured Neighbor.
 *
 * @generated from message chatto.admin.v1.CreateNeighborResponse
 */
export class CreateNeighborResponse extends Message<CreateNeighborResponse> {
  /**
   * @generated from field: chatto.admin.v1.Neighbor neighbor = 1;
   */
  neighbor?: Neighbor;

  constructor(data?: PartialMessage<CreateNeighborResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.CreateNeighborResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "neighbor", kind: "message", T: Neighbor },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateNeighborResponse {
    return new CreateNeighborResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateNeighborResponse {
    return new CreateNeighborResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateNeighborResponse {
    return new CreateNeighborResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateNeighborResponse | PlainMessage<CreateNeighborResponse> | undefined, b: CreateNeighborResponse | PlainMessage<CreateNeighborResponse> | undefined): boolean {
    return proto3.util.equals(CreateNeighborResponse, a, b);
  }
}

/**
 * Request to change one advertised server origin.
 *
 * @generated from message chatto.admin.v1.UpdateNeighborRequest
 */
export class UpdateNeighborRequest extends Message<UpdateNeighborRequest> {
  /**
   * @generated from field: string neighbor_id = 1;
   */
  neighborId = "";

  /**
   * @generated from field: string origin = 2;
   */
  origin = "";

  /**
   * @generated from field: string revision = 3;
   */
  revision = "";

  constructor(data?: PartialMessage<UpdateNeighborRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateNeighborRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "neighbor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "origin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "revision", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateNeighborRequest {
    return new UpdateNeighborRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateNeighborRequest {
    return new UpdateNeighborRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateNeighborRequest {
    return new UpdateNeighborRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateNeighborRequest | PlainMessage<UpdateNeighborRequest> | undefined, b: UpdateNeighborRequest | PlainMessage<UpdateNeighborRequest> | undefined): boolean {
    return proto3.util.equals(UpdateNeighborRequest, a, b);
  }
}

/**
 * Updated Neighbor.
 *
 * @generated from message chatto.admin.v1.UpdateNeighborResponse
 */
export class UpdateNeighborResponse extends Message<UpdateNeighborResponse> {
  /**
   * @generated from field: chatto.admin.v1.Neighbor neighbor = 1;
   */
  neighbor?: Neighbor;

  constructor(data?: PartialMessage<UpdateNeighborResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.UpdateNeighborResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "neighbor", kind: "message", T: Neighbor },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateNeighborResponse {
    return new UpdateNeighborResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateNeighborResponse {
    return new UpdateNeighborResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateNeighborResponse {
    return new UpdateNeighborResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateNeighborResponse | PlainMessage<UpdateNeighborResponse> | undefined, b: UpdateNeighborResponse | PlainMessage<UpdateNeighborResponse> | undefined): boolean {
    return proto3.util.equals(UpdateNeighborResponse, a, b);
  }
}

/**
 * Request to stop advertising one server origin.
 *
 * @generated from message chatto.admin.v1.DeleteNeighborRequest
 */
export class DeleteNeighborRequest extends Message<DeleteNeighborRequest> {
  /**
   * @generated from field: string neighbor_id = 1;
   */
  neighborId = "";

  /**
   * @generated from field: string revision = 2;
   */
  revision = "";

  constructor(data?: PartialMessage<DeleteNeighborRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.DeleteNeighborRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "neighbor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "revision", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteNeighborRequest {
    return new DeleteNeighborRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteNeighborRequest {
    return new DeleteNeighborRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteNeighborRequest {
    return new DeleteNeighborRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteNeighborRequest | PlainMessage<DeleteNeighborRequest> | undefined, b: DeleteNeighborRequest | PlainMessage<DeleteNeighborRequest> | undefined): boolean {
    return proto3.util.equals(DeleteNeighborRequest, a, b);
  }
}

/**
 * Empty result after a Neighbor is deleted.
 *
 * @generated from message chatto.admin.v1.DeleteNeighborResponse
 */
export class DeleteNeighborResponse extends Message<DeleteNeighborResponse> {
  constructor(data?: PartialMessage<DeleteNeighborResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.admin.v1.DeleteNeighborResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteNeighborResponse {
    return new DeleteNeighborResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteNeighborResponse {
    return new DeleteNeighborResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteNeighborResponse {
    return new DeleteNeighborResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteNeighborResponse | PlainMessage<DeleteNeighborResponse> | undefined, b: DeleteNeighborResponse | PlainMessage<DeleteNeighborResponse> | undefined): boolean {
    return proto3.util.equals(DeleteNeighborResponse, a, b);
  }
}
