// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/admin/v1/server.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateNeighborRequest, CreateNeighborResponse, DeleteNeighborRequest, DeleteNeighborResponse, DeleteServerBannerRequest, DeleteServerBannerResponse, DeleteServerLogoRequest, DeleteServerLogoResponse, GetNeighborRequest, GetNeighborResponse, GetServerConfigRequest, GetServerConfigResponse, GetServerSecurityConfigRequest, GetServerSecurityConfigResponse, ListNeighborsRequest, ListNeighborsResponse, UpdateBlockedUsernamesRequest, UpdateBlockedUsernamesResponse, UpdateNeighborRequest, UpdateNeighborResponse, UpdateServerConfigRequest, UpdateServerConfigResponse, UploadServerBannerRequest, UploadServerBannerResponse, UploadServerLogoRequest, UploadServerLogoResponse } from "./server_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Provides server-administration commands for profile, branding, and security
 * settings.
 *
 * @generated from service chatto.admin.v1.AdminServerService
 */
export const AdminServerService = {
  typeName: "chatto.admin.v1.AdminServerService",
  methods: {
    /**
     * Gets runtime-editable server profile settings. This RPC requires
     * server.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.GetServerConfig
     */
    getServerConfig: {
      name: "GetServerConfig",
      I: GetServerConfigRequest,
      O: GetServerConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates runtime-editable server profile settings. This RPC requires
     * server.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.UpdateServerConfig
     */
    updateServerConfig: {
      name: "UpdateServerConfig",
      I: UpdateServerConfigRequest,
      O: UpdateServerConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Uploads and sets the public server logo. This RPC requires server.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.UploadServerLogo
     */
    uploadServerLogo: {
      name: "UploadServerLogo",
      I: UploadServerLogoRequest,
      O: UploadServerLogoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Clears the public server logo. This RPC requires server.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.DeleteServerLogo
     */
    deleteServerLogo: {
      name: "DeleteServerLogo",
      I: DeleteServerLogoRequest,
      O: DeleteServerLogoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Uploads and sets the public server banner. This RPC requires server.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.UploadServerBanner
     */
    uploadServerBanner: {
      name: "UploadServerBanner",
      I: UploadServerBannerRequest,
      O: UploadServerBannerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Clears the public server banner. This RPC requires server.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.DeleteServerBanner
     */
    deleteServerBanner: {
      name: "DeleteServerBanner",
      I: DeleteServerBannerRequest,
      O: DeleteServerBannerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Returns security-sensitive server configuration. This RPC requires
     * server.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.GetServerSecurityConfig
     */
    getServerSecurityConfig: {
      name: "GetServerSecurityConfig",
      I: GetServerSecurityConfigRequest,
      O: GetServerSecurityConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates the blocked-username list. This RPC requires server.manage.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.UpdateBlockedUsernames
     */
    updateBlockedUsernames: {
      name: "UpdateBlockedUsernames",
      I: UpdateBlockedUsernamesRequest,
      O: UpdateBlockedUsernamesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists configured Neighbors. This RPC requires server.manage-neighbors.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.ListNeighbors
     */
    listNeighbors: {
      name: "ListNeighbors",
      I: ListNeighborsRequest,
      O: ListNeighborsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets one configured Neighbor. This RPC requires server.manage-neighbors.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.GetNeighbor
     */
    getNeighbor: {
      name: "GetNeighbor",
      I: GetNeighborRequest,
      O: GetNeighborResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Advertises one server origin. The origin must not identify this server.
     * This RPC requires server.manage-neighbors.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.CreateNeighbor
     */
    createNeighbor: {
      name: "CreateNeighbor",
      I: CreateNeighborRequest,
      O: CreateNeighborResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Changes one advertised server origin. The new origin must not identify
     * this server. This RPC requires server.manage-neighbors.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.UpdateNeighbor
     */
    updateNeighbor: {
      name: "UpdateNeighbor",
      I: UpdateNeighborRequest,
      O: UpdateNeighborResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Stops advertising one server origin. This RPC requires
     * server.manage-neighbors.
     *
     * @generated from rpc chatto.admin.v1.AdminServerService.DeleteNeighbor
     */
    deleteNeighbor: {
      name: "DeleteNeighbor",
      I: DeleteNeighborRequest,
      O: DeleteNeighborResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
