#!/usr/bin/env sh
set -eu

usage() {
	cat <<'EOF'
Usage: ./init-env.sh [--force] <domain> <owner-email> [smtp-from]

Creates .env and livekit.generated.yaml with matching generated secrets.

Examples:
  ./init-env.sh chat.example.com admin@example.com
  ./init-env.sh --force chat.example.com admin@example.com noreply@example.com
EOF
}

force=false
domain=
owner_email=
smtp_from=

while [ "$#" -gt 0 ]; do
	case "$1" in
		--force)
			force=true
			;;
		-h|--help)
			usage
			exit 0
			;;
		-*)
			echo "Unknown option: $1" >&2
			usage >&2
			exit 1
			;;
		*)
			if [ -z "$domain" ]; then
				domain=$1
			elif [ -z "$owner_email" ]; then
				owner_email=$1
			elif [ -z "$smtp_from" ]; then
				smtp_from=$1
			else
				usage >&2
				exit 1
			fi
			;;
	esac
	shift
done

if [ -z "$domain" ] || [ -z "$owner_email" ]; then
	echo "The domain and owner-email arguments are required." >&2
	usage >&2
	exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
	echo "openssl is required to generate secrets" >&2
	exit 1
fi

if [ -e .env ] && [ "$force" != "true" ]; then
	echo ".env already exists. Use --force to replace it." >&2
	exit 1
fi

if [ -e livekit.generated.yaml ] && [ "$force" != "true" ]; then
	echo "livekit.generated.yaml already exists. Use --force to replace it." >&2
	exit 1
fi

domain=${domain#https://}
domain=${domain#http://}
domain=${domain%/}
smtp_from=${smtp_from:-noreply@example.com}

rand_hex() {
	openssl rand -hex 32
}

nats_token=$(rand_hex)
cookie_signing_secret=$(rand_hex)
cookie_encryption_secret=$(rand_hex)
core_secret_key=$(rand_hex)
assets_signing_secret=$(rand_hex)
livekit_api_key=chatto
livekit_api_secret=$(rand_hex)

cat > .env <<EOF
# Generated by init-env.sh. Review every value before going live.

PUBLIC_URL=${domain}
CHATTO_OWNERS_EMAILS=${owner_email}

PUID=1000
PGID=1000

CHATTO_NATS_EMBEDDED_ENABLED=false
CHATTO_NATS_CLIENT_URL=nats://nats:4222
CHATTO_NATS_CLIENT_AUTH_METHOD=token
CHATTO_NATS_CLIENT_TOKEN=${nats_token}
CHATTO_WEBSERVER_URL=https://${domain}
CHATTO_WEBSERVER_PORT=4000
CHATTO_WEBSERVER_COOKIE_SIGNING_SECRET=${cookie_signing_secret}
CHATTO_WEBSERVER_COOKIE_ENCRYPTION_SECRET=${cookie_encryption_secret}
CHATTO_CORE_SECRET_KEY=${core_secret_key}
CHATTO_CORE_ASSETS_SIGNING_SECRET=${assets_signing_secret}
CHATTO_LOG_LEVEL=info
CHATTO_LOG_FORMAT=json
CHATTO_OPERATOR_API_ENABLED=true
CHATTO_OPERATOR_API_SOCKET_PATH=/tmp/chatto/operator.sock

# SMTP is required for direct email/password registration, email verification,
# and password reset. Replace these placeholders with your provider settings.
CHATTO_SMTP_ENABLED=true
CHATTO_SMTP_HOST=smtp.example.com
CHATTO_SMTP_PORT=587
CHATTO_SMTP_TLS=mandatory
# Use when CHATTO_SMTP_HOST is an IP address or internal alias but the certificate is issued for a DNS name.
# CHATTO_SMTP_TLS_SERVER_NAME=mail.example.com
# Insecure; use only for trusted internal SMTP servers with self-signed or mismatched certificates.
# CHATTO_SMTP_TLS_SKIP_VERIFY=false
CHATTO_SMTP_USERNAME=your-smtp-username
CHATTO_SMTP_PASSWORD=your-smtp-password
CHATTO_SMTP_FROM=${smtp_from}

LIVEKIT_CONFIG_FILE=./livekit.generated.yaml
CHATTO_LIVEKIT_ENABLED=true
CHATTO_LIVEKIT_URL=wss://livekit.${domain}
CHATTO_LIVEKIT_API_KEY=${livekit_api_key}
CHATTO_LIVEKIT_API_SECRET=${livekit_api_secret}
EOF

cat > livekit.generated.yaml <<EOF
port: 7880
rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: true

turn:
  enabled: true
  udp_port: 3478

keys:
  ${livekit_api_key}: ${livekit_api_secret}

webhook:
  urls:
    - https://${domain}/webhooks/livekit
  api_key: ${livekit_api_key}

logging:
  level: info
EOF

cat > nats.conf <<EOF
# NATS server configuration file
# Generated by init-env.sh. Do not commit to version control.

# Authentication configuration
authorization: {
  token: "${nats_token}"
}

# Enable JetStream for event streaming
jetstream: {
  store_dir: /data
}
EOF

chmod 600 .env livekit.generated.yaml nats.conf

cat <<EOF
Wrote .env, nats.conf, and livekit.generated.yaml.

Next steps:
  1. Edit .env and replace the CHATTO_SMTP_* placeholders.
  2. Confirm PUBLIC_URL and CHATTO_OWNERS_EMAILS.
  3. Run: docker compose up -d
EOF
